-- Generated by scripts/render-sync-scene.mjs; edit overview.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=7.6,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=760,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-0",["layer"]=40,["point"]={-5.9,3.38},["role"]="text",["size"]=30,["text"]="Sync / End"}
refs[2] = scene:text {["align"]={1,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-1",["layer"]=40,["point"]={5.9,3.38},["role"]="text",["size"]=22,["text"]="CPU task completion"}
refs[3] = scene:line {["from"]={-5.9,3.02},["id"]="sync-rule-2",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,3.02},["width"]=1}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-3",["layer"]=40,["point"]={-5,2.6},["role"]="text",["size"]=20,["text"]="Update"}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-4",["layer"]=40,["point"]={-2.35,2.6},["role"]="text",["size"]=20,["text"]="Draw / Composite"}
refs[6] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-5",["layer"]=40,["point"]={1,2.6},["role"]="text",["size"]=20,["text"]="postRender()"}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-6",["layer"]=40,["point"]={4.8,2.6},["role"]="text",["size"]=22,["text"]="sync()"}
refs[8] = scene:route {["id"]="sync-route-7",["layer"]=20,["points"]={{-4.4,2.6},{-3.6,2.6}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[9] = scene:route {["id"]="sync-route-8",["layer"]=20,["points"]={{-1.05,2.6},{0.05,2.6}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[10] = scene:route {["id"]="sync-route-9",["layer"]=20,["points"]={{2,2.6},{4.15,2.6}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[11] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-10",["layer"]=40,["point"]={-0.7,2.23},["role"]="text",["size"]=16,["text"]="inside draw()"}
refs[12] = scene:line {["from"]={-3.55,2.39},["id"]="sync-draw-scope-11",["layer"]=5,["stroke"]="#aaaaaa",["to"]={2,2.39},["width"]=1}
refs[13] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-12",["layer"]=40,["point"]={-4.25,1.55},["role"]="text",["size"]=23,["text"]="Canvas::sync()"}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-13",["layer"]=40,["point"]={-0.1,1.55},["role"]="text",["size"]=23,["text"]="Canvas::Impl::sync()"}
refs[15] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-14",["layer"]=40,["point"]={4.35,1.55},["role"]="text",["size"]=23,["text"]="SwRenderer::sync()"}
refs[16] = scene:route {["id"]="sync-route-15",["layer"]=20,["points"]={{-3.05,1.55},{-1.85,1.55}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[17] = scene:route {["id"]="sync-route-16",["layer"]=20,["points"]={{1.6,1.55},{2.7,1.55}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[18] = scene:group {["id"]="sync-wait-17",["opacity"]=0}
refs[19] = refs[18]:rectangle {["center"]={-1.95,-0.73},["dash"]={6,5},["fill"]="#00000000",["id"]="sync-rect-18",["layer"]=12,["size"]={7.9,3.12},["stroke"]="#aaaaaa",["width"]=1.5}
refs[20] = refs[18]:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-19",["layer"]=40,["point"]={-5.6,0.55},["role"]="text",["size"]=19,["text"]="for each task"}
refs[21] = refs[18]:rectangle {["center"]={-4.05,-0.75},["fill"]="#ffffff",["id"]="sync-rect-20",["layer"]=12,["size"]={2.8,0.94},["stroke"]="#202020",["width"]=1.5}
refs[22] = refs[18]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-21",["layer"]=40,["point"]={-4.05,-0.57},["role"]="text",["size"]=23,["text"]="task->done()"}
refs[23] = refs[18]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-22",["layer"]=40,["point"]={-4.05,-0.97},["role"]="text",["size"]=18,["text"]="wait if still pending"}
refs[24] = scene:group {["id"]="sync-release-23",["opacity"]=0}
refs[25] = refs[24]:rectangle {["center"]={-0.15,-0.1},["fill"]="#ffffff",["id"]="sync-rect-24",["layer"]=12,["size"]={3.3,0.94},["stroke"]="#202020",["width"]=1.5}
refs[26] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-25",["layer"]=40,["point"]={-0.15,0.08},["role"]="text",["size"]=23,["text"]="delete task"}
refs[27] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-26",["layer"]=40,["point"]={-0.15,-0.32},["role"]="text",["size"]=18,["text"]="disposed == true"}
refs[28] = refs[24]:rectangle {["center"]={-0.15,-1.55},["fill"]="#ffffff",["id"]="sync-rect-27",["layer"]=12,["size"]={3.3,0.94},["stroke"]="#202020",["width"]=1.5}
refs[29] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-28",["layer"]=40,["point"]={-0.15,-1.37},["role"]="text",["size"]=23,["text"]="pushed = false"}
refs[30] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-29",["layer"]=40,["point"]={-0.15,-1.77},["role"]="text",["size"]=18,["text"]="otherwise: keep RenderData"}
refs[31] = refs[24]:route {["id"]="sync-route-30",["layer"]=20,["points"]={{-2.64,-0.75},{-2.25,-0.75},{-2.25,-0.1},{-1.81,-0.1}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[32] = refs[24]:route {["id"]="sync-route-31",["layer"]=20,["points"]={{-2.25,-0.75},{-2.25,-1.55},{-1.81,-1.55}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[33] = scene:group {["id"]="sync-clear-32",["opacity"]=0}
refs[34] = refs[33]:route {["id"]="sync-route-33",["layer"]=20,["points"]={{2.01,-0.75},{2.78,-0.75}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[35] = refs[33]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-34",["layer"]=40,["point"]={4,0.1},["role"]="text",["size"]=19,["text"]="after all tasks"}
refs[36] = refs[33]:rectangle {["center"]={4.35,-0.75},["fill"]="#ffffff",["id"]="sync-rect-35",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[37] = refs[33]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-36",["layer"]=40,["point"]={4.35,-0.57},["role"]="text",["size"]=23,["text"]="tasks.clear()"}
refs[38] = refs[33]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-37",["layer"]=40,["point"]={4.35,-0.97},["role"]="text",["size"]=18,["text"]="list count = 0"}
refs[39] = scene:group {["id"]="sync-synced-38",["opacity"]=0}
refs[40] = refs[39]:route {["id"]="sync-route-39",["layer"]=20,["points"]={{4.35,-1.23},{4.35,-2.17}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[41] = refs[39]:rectangle {["center"]={4.35,-2.65},["fill"]="#202020",["id"]="sync-rect-40",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[42] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="sync-text-41",["layer"]=40,["point"]={4.35,-2.47},["role"]="text",["size"]=23,["text"]="status = Synced"}
refs[43] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#dddddd",["font"]="Pretendard",["id"]="sync-text-42",["layer"]=40,["point"]={4.35,-2.87},["role"]="text",["size"]=18,["text"]="Canvas::Impl"}
refs[44] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="sync-text-43",["layer"]=40,["point"]={-1.95,-2.91},["role"]="text",["size"]=23,["text"]="Live tasks remain reusable."}
refs[45] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="sync-text-44",["layer"]=40,["point"]={-1.95,-3.31},["role"]="text",["size"]=18,["text"]="Update without Draw also reaches this cleanup."}
scene:wait(1.3)
scene:play({{target=refs[18],opacity=1}},0.55,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[24],opacity=1}},0.55,"ease_in_out",0)
scene:wait(2)
scene:play({{target=refs[33],opacity=1}},0.55,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[39],opacity=1}},0.55,"ease_in_out",0)
scene:wait(2.7)
return scene
