-- Generated by scripts/render-update-scenes.mjs; edit bitmap-data.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=15,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=1500,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#222222",["font"]="Pretendard"},["h1"]={["color"]="#222222",["font"]="Pretendard"},["h2"]={["color"]="#222222",["font"]="Pretendard"},["h3"]={["color"]="#222222",["font"]="Pretendard"},["text"]={["color"]="#222222",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-0",["layer"]=40,["point"]={0,7.03},["size"]=31,["text"]="Picture Bitmap · prepared members"}
refs[2] = scene:rectangle {["center"]={-5.4,6.32},["fill"]="#e66121",["id"]="bitmap-data-1",["layer"]=15,["size"]={0.38,0.38},["stroke"]="#00000000",["width"]=1.2}
refs[3] = scene:rectangle {["center"]={-5.02,6.32},["fill"]="#1f66c4",["id"]="bitmap-data-2",["layer"]=15,["size"]={0.38,0.38},["stroke"]="#00000000",["width"]=1.2}
refs[4] = scene:rectangle {["center"]={-5.4,5.94},["fill"]="#dedede",["id"]="bitmap-data-3",["layer"]=15,["size"]={0.38,0.38},["stroke"]="#00000000",["width"]=1.2}
refs[5] = scene:rectangle {["center"]={-5.02,5.94},["fill"]="#ffffff",["id"]="bitmap-data-4",["layer"]=15,["size"]={0.38,0.38},["stroke"]="#00000000",["width"]=1.2}
refs[6] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-5",["layer"]=40,["point"]={-2.28,6.39},["size"]=23,["text"]="image.data = source->data"}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-6",["layer"]=40,["point"]={-2.28,5.94},["size"]=21,["text"]="w = 2 · h = 2 · stride = 2"}
refs[8] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-7",["layer"]=40,["point"]={2.98,6.39},["size"]=23,["text"]="image.filter = Bilinear"}
refs[9] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-8",["layer"]=40,["point"]={2.98,5.94},["size"]=21,["text"]="task.transform · task.curBox"}
refs[10] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-9",["layer"]=10,["points"]={{-5.95,5.51},{5.95,5.51}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[11] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-10",["layer"]=40,["point"]={-4.22,5.1},["size"]=26,["text"]="Direct"}
refs[12] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-11",["layer"]=40,["point"]={-4.22,4.72},["size"]=19,["text"]="task.transform"}
refs[13] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-12",["layer"]=40,["point"]={-4.22,4.38},["size"]=22,["text"]="[ 1    0    3 ]"}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-13",["layer"]=40,["point"]={-4.22,4.03},["size"]=22,["text"]="[ 0    1    4 ]"}
refs[15] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-14",["layer"]=5,["points"]={{-5.54,3.65},{-5.54,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[16] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-15",["layer"]=5,["points"]={{-5.54,3.65},{-2.9,3.65}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[17] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-16",["layer"]=5,["points"]={{-5.32,3.65},{-5.32,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[18] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-17",["layer"]=5,["points"]={{-5.54,3.43},{-2.9,3.43}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[19] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-18",["layer"]=5,["points"]={{-5.1,3.65},{-5.1,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[20] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-19",["layer"]=5,["points"]={{-5.54,3.21},{-2.9,3.21}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[21] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-20",["layer"]=5,["points"]={{-4.88,3.65},{-4.88,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[22] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-21",["layer"]=5,["points"]={{-5.54,2.99},{-2.9,2.99}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[23] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-22",["layer"]=5,["points"]={{-4.66,3.65},{-4.66,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[24] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-23",["layer"]=5,["points"]={{-5.54,2.77},{-2.9,2.77}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[25] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-24",["layer"]=5,["points"]={{-4.44,3.65},{-4.44,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[26] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-25",["layer"]=5,["points"]={{-5.54,2.55},{-2.9,2.55}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[27] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-26",["layer"]=5,["points"]={{-4.22,3.65},{-4.22,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[28] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-27",["layer"]=5,["points"]={{-5.54,2.33},{-2.9,2.33}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[29] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-28",["layer"]=5,["points"]={{-4,3.65},{-4,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[30] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-29",["layer"]=5,["points"]={{-5.54,2.11},{-2.9,2.11}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[31] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-30",["layer"]=5,["points"]={{-3.78,3.65},{-3.78,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[32] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-31",["layer"]=5,["points"]={{-5.54,1.89},{-2.9,1.89}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[33] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-32",["layer"]=5,["points"]={{-3.56,3.65},{-3.56,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[34] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-33",["layer"]=5,["points"]={{-5.54,1.67},{-2.9,1.67}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[35] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-34",["layer"]=5,["points"]={{-3.34,3.65},{-3.34,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[36] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-35",["layer"]=5,["points"]={{-5.54,1.45},{-2.9,1.45}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[37] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-36",["layer"]=5,["points"]={{-3.12,3.65},{-3.12,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[38] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-37",["layer"]=5,["points"]={{-5.54,1.23},{-2.9,1.23}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[39] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-38",["layer"]=5,["points"]={{-2.9,3.65},{-2.9,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[40] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-39",["layer"]=5,["points"]={{-5.54,1.01},{-2.9,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[41] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-40",["layer"]=40,["point"]={-5.69,3.65},["size"]=16,["text"]="0"}
refs[42] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-41",["layer"]=40,["point"]={-2.9,0.82},["size"]=16,["text"]="12"}
refs[43] = scene:group {["id"]="bitmap-data-42",["matrix"]={1,0,0,-5.54,0,1,0,3.65,0,0,1,0,0,0,0,1}}
refs[44] = refs[43]:rectangle {["center"]={0.11,-0.11},["fill"]="#e66121",["id"]="bitmap-data-43",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[45] = refs[43]:rectangle {["center"]={0.33,-0.11},["fill"]="#1f66c4",["id"]="bitmap-data-44",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[46] = refs[43]:rectangle {["center"]={0.11,-0.33},["fill"]="#dedede",["id"]="bitmap-data-45",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[47] = refs[43]:rectangle {["center"]={0.33,-0.33},["fill"]="#ffffff",["id"]="bitmap-data-46",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[48] = scene:group {["id"]="bitmap-data-47",["opacity"]=0}
refs[49] = scene:group {["id"]="bitmap-data-48",["opacity"]=0}
refs[50] = refs[49]:route {["dash"]={5,4},["fill"]="#00000000",["id"]="bitmap-data-49",["layer"]=30,["points"]={{-4.88,2.77},{-4.44,2.77},{-4.44,2.33},{-4.88,2.33},{-4.88,2.77}},["stroke"]="#737373",["tip"]=0,["width"]=1.3}
refs[51] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-50",["layer"]=40,["point"]={-4.22,0.6},["size"]=20,["text"]="image.outline → task.curBox"}
refs[52] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-51",["layer"]=40,["point"]={-4.22,0.12},["size"]=19,["text"]="image.direct = true"}
refs[53] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-52",["layer"]=40,["point"]={-4.22,-0.31},["size"]=21,["text"]="image.ox / oy = (-3, -4)"}
refs[54] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-53",["layer"]=40,["point"]={-4.22,-0.74},["size"]=21,["text"]="image.rle = nullptr"}
refs[55] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-54",["layer"]=40,["point"]={-4.22,-1.16},["size"]=19,["text"]="curBox = (3, 4) → (5, 6)"}
refs[56] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-55",["layer"]=40,["point"]={0,5.1},["size"]=26,["text"]="Scaled"}
refs[57] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-56",["layer"]=40,["point"]={0,4.72},["size"]=19,["text"]="task.transform"}
refs[58] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-57",["layer"]=40,["point"]={0,4.38},["size"]=22,["text"]="[ 3    0    3 ]"}
refs[59] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-58",["layer"]=40,["point"]={0,4.03},["size"]=22,["text"]="[ 0    2    4 ]"}
refs[60] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-59",["layer"]=5,["points"]={{-1.32,3.65},{-1.32,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[61] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-60",["layer"]=5,["points"]={{-1.32,3.65},{1.32,3.65}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[62] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-61",["layer"]=5,["points"]={{-1.1,3.65},{-1.1,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[63] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-62",["layer"]=5,["points"]={{-1.32,3.43},{1.32,3.43}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[64] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-63",["layer"]=5,["points"]={{-0.88,3.65},{-0.88,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[65] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-64",["layer"]=5,["points"]={{-1.32,3.21},{1.32,3.21}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[66] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-65",["layer"]=5,["points"]={{-0.66,3.65},{-0.66,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[67] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-66",["layer"]=5,["points"]={{-1.32,2.99},{1.32,2.99}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[68] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-67",["layer"]=5,["points"]={{-0.44,3.65},{-0.44,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[69] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-68",["layer"]=5,["points"]={{-1.32,2.77},{1.32,2.77}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[70] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-69",["layer"]=5,["points"]={{-0.22,3.65},{-0.22,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[71] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-70",["layer"]=5,["points"]={{-1.32,2.55},{1.32,2.55}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[72] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-71",["layer"]=5,["points"]={{0,3.65},{0,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[73] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-72",["layer"]=5,["points"]={{-1.32,2.33},{1.32,2.33}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[74] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-73",["layer"]=5,["points"]={{0.22,3.65},{0.22,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[75] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-74",["layer"]=5,["points"]={{-1.32,2.11},{1.32,2.11}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[76] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-75",["layer"]=5,["points"]={{0.44,3.65},{0.44,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[77] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-76",["layer"]=5,["points"]={{-1.32,1.89},{1.32,1.89}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[78] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-77",["layer"]=5,["points"]={{0.66,3.65},{0.66,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[79] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-78",["layer"]=5,["points"]={{-1.32,1.67},{1.32,1.67}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[80] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-79",["layer"]=5,["points"]={{0.88,3.65},{0.88,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[81] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-80",["layer"]=5,["points"]={{-1.32,1.45},{1.32,1.45}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[82] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-81",["layer"]=5,["points"]={{1.1,3.65},{1.1,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[83] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-82",["layer"]=5,["points"]={{-1.32,1.23},{1.32,1.23}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[84] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-83",["layer"]=5,["points"]={{1.32,3.65},{1.32,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[85] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-84",["layer"]=5,["points"]={{-1.32,1.01},{1.32,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[86] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-85",["layer"]=40,["point"]={-1.47,3.65},["size"]=16,["text"]="0"}
refs[87] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-86",["layer"]=40,["point"]={1.32,0.82},["size"]=16,["text"]="12"}
refs[88] = scene:group {["id"]="bitmap-data-87",["matrix"]={1,0,0,-1.32,0,1,0,3.65,0,0,1,0,0,0,0,1}}
refs[89] = refs[88]:rectangle {["center"]={0.11,-0.11},["fill"]="#e66121",["id"]="bitmap-data-88",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[90] = refs[88]:rectangle {["center"]={0.33,-0.11},["fill"]="#1f66c4",["id"]="bitmap-data-89",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[91] = refs[88]:rectangle {["center"]={0.11,-0.33},["fill"]="#dedede",["id"]="bitmap-data-90",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[92] = refs[88]:rectangle {["center"]={0.33,-0.33},["fill"]="#ffffff",["id"]="bitmap-data-91",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[93] = scene:group {["id"]="bitmap-data-92",["opacity"]=0}
refs[94] = scene:group {["id"]="bitmap-data-93",["opacity"]=0}
refs[95] = refs[94]:route {["dash"]={5,4},["fill"]="#00000000",["id"]="bitmap-data-94",["layer"]=30,["points"]={{-0.66,2.77},{0.66,2.77},{0.66,1.89},{-0.66,1.89},{-0.66,2.77}},["stroke"]="#737373",["tip"]=0,["width"]=1.3}
refs[96] = refs[93]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-95",["layer"]=40,["point"]={0,0.6},["size"]=20,["text"]="image.outline → task.curBox"}
refs[97] = refs[93]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-96",["layer"]=40,["point"]={0,0.12},["size"]=19,["text"]="direct = false · scaled = true"}
refs[98] = refs[93]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-97",["layer"]=40,["point"]={0,-0.31},["size"]=21,["text"]="image.scale = 3"}
refs[99] = refs[93]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-98",["layer"]=40,["point"]={0,-0.74},["size"]=21,["text"]="image.rle = nullptr"}
refs[100] = refs[93]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-99",["layer"]=40,["point"]={0,-1.16},["size"]=19,["text"]="curBox = (3, 4) → (9, 8)"}
refs[101] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-100",["layer"]=40,["point"]={4.22,5.1},["size"]=26,["text"]="Transformed"}
refs[102] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-101",["layer"]=40,["point"]={4.22,4.72},["size"]=19,["text"]="task.transform"}
refs[103] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-102",["layer"]=40,["point"]={4.22,4.38},["size"]=22,["text"]="[ 3    -1    4 ]"}
refs[104] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-103",["layer"]=40,["point"]={4.22,4.03},["size"]=22,["text"]="[ 1    3    2 ]"}
refs[105] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-104",["layer"]=5,["points"]={{2.9,3.65},{2.9,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[106] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-105",["layer"]=5,["points"]={{2.9,3.65},{5.54,3.65}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[107] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-106",["layer"]=5,["points"]={{3.12,3.65},{3.12,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[108] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-107",["layer"]=5,["points"]={{2.9,3.43},{5.54,3.43}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[109] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-108",["layer"]=5,["points"]={{3.34,3.65},{3.34,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[110] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-109",["layer"]=5,["points"]={{2.9,3.21},{5.54,3.21}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[111] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-110",["layer"]=5,["points"]={{3.56,3.65},{3.56,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[112] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-111",["layer"]=5,["points"]={{2.9,2.99},{5.54,2.99}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[113] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-112",["layer"]=5,["points"]={{3.78,3.65},{3.78,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[114] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-113",["layer"]=5,["points"]={{2.9,2.77},{5.54,2.77}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[115] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-114",["layer"]=5,["points"]={{4,3.65},{4,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[116] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-115",["layer"]=5,["points"]={{2.9,2.55},{5.54,2.55}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[117] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-116",["layer"]=5,["points"]={{4.22,3.65},{4.22,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[118] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-117",["layer"]=5,["points"]={{2.9,2.33},{5.54,2.33}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[119] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-118",["layer"]=5,["points"]={{4.44,3.65},{4.44,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[120] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-119",["layer"]=5,["points"]={{2.9,2.11},{5.54,2.11}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[121] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-120",["layer"]=5,["points"]={{4.66,3.65},{4.66,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[122] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-121",["layer"]=5,["points"]={{2.9,1.89},{5.54,1.89}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[123] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-122",["layer"]=5,["points"]={{4.88,3.65},{4.88,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[124] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-123",["layer"]=5,["points"]={{2.9,1.67},{5.54,1.67}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[125] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-124",["layer"]=5,["points"]={{5.1,3.65},{5.1,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[126] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-125",["layer"]=5,["points"]={{2.9,1.45},{5.54,1.45}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[127] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-126",["layer"]=5,["points"]={{5.32,3.65},{5.32,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[128] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-127",["layer"]=5,["points"]={{2.9,1.23},{5.54,1.23}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[129] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-128",["layer"]=5,["points"]={{5.54,3.65},{5.54,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[130] = scene:route {["fill"]="#00000000",["id"]="bitmap-data-129",["layer"]=5,["points"]={{2.9,1.01},{5.54,1.01}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[131] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-130",["layer"]=40,["point"]={2.75,3.65},["size"]=16,["text"]="0"}
refs[132] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-131",["layer"]=40,["point"]={5.54,0.82},["size"]=16,["text"]="12"}
refs[133] = scene:group {["id"]="bitmap-data-132",["matrix"]={1,0,0,2.9,0,1,0,3.65,0,0,1,0,0,0,0,1}}
refs[134] = refs[133]:rectangle {["center"]={0.11,-0.11},["fill"]="#e66121",["id"]="bitmap-data-133",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[135] = refs[133]:rectangle {["center"]={0.33,-0.11},["fill"]="#1f66c4",["id"]="bitmap-data-134",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[136] = refs[133]:rectangle {["center"]={0.11,-0.33},["fill"]="#dedede",["id"]="bitmap-data-135",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[137] = refs[133]:rectangle {["center"]={0.33,-0.33},["fill"]="#ffffff",["id"]="bitmap-data-136",["layer"]=20,["size"]={0.22,0.22},["stroke"]="#222222",["width"]=1}
refs[138] = scene:group {["id"]="bitmap-data-137",["opacity"]=0}
refs[139] = scene:group {["id"]="bitmap-data-138",["opacity"]=0}
refs[140] = refs[139]:route {["dash"]={5,4},["fill"]="#00000000",["id"]="bitmap-data-139",["layer"]=30,["points"]={{3.34,3.21},{5.1,3.21},{5.1,1.45},{3.34,1.45},{3.34,3.21}},["stroke"]="#737373",["tip"]=0,["width"]=1.3}
refs[141] = refs[138]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-140",["layer"]=40,["point"]={4.22,0.6},["size"]=20,["text"]="image.outline → task.curBox"}
refs[142] = refs[138]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-141",["layer"]=40,["point"]={4.22,0.12},["size"]=19,["text"]="direct = false · scaled = false"}
refs[143] = refs[138]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-142",["layer"]=40,["point"]={4.22,-0.31},["size"]=21,["text"]="image.scale = 3.1623"}
refs[144] = refs[138]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-143",["layer"]=40,["point"]={4.22,-0.74},["size"]=21,["text"]="image.rle = nullptr"}
refs[145] = refs[138]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-144",["layer"]=40,["point"]={4.22,-1.16},["size"]=19,["text"]="curBox = (2, 2) → (10, 10)"}
refs[146] = scene:group {["id"]="bitmap-data-145",["opacity"]=0}
refs[147] = scene:group {["id"]="bitmap-data-146",["opacity"]=0}
refs[148] = scene:group {["id"]="bitmap-data-147",["opacity"]=0}
refs[149] = scene:group {["id"]="bitmap-data-148",["opacity"]=0}
refs[150] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-149",["layer"]=10,["points"]={{-5.95,-1.63},{5.95,-1.63}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[151] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-150",["layer"]=40,["point"]={0,-2.09},["size"]=25,["text"]="Transformed + Clip · picture->clip(shape)"}
refs[152] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-151",["layer"]=5,["points"]={{-5.32,-2.63},{-5.32,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[153] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-152",["layer"]=5,["points"]={{-5.32,-2.63},{-2.68,-2.63}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[154] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-153",["layer"]=5,["points"]={{-5.1,-2.63},{-5.1,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[155] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-154",["layer"]=5,["points"]={{-5.32,-2.85},{-2.68,-2.85}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[156] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-155",["layer"]=5,["points"]={{-4.88,-2.63},{-4.88,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[157] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-156",["layer"]=5,["points"]={{-5.32,-3.07},{-2.68,-3.07}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[158] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-157",["layer"]=5,["points"]={{-4.66,-2.63},{-4.66,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[159] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-158",["layer"]=5,["points"]={{-5.32,-3.29},{-2.68,-3.29}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[160] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-159",["layer"]=5,["points"]={{-4.44,-2.63},{-4.44,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[161] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-160",["layer"]=5,["points"]={{-5.32,-3.51},{-2.68,-3.51}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[162] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-161",["layer"]=5,["points"]={{-4.22,-2.63},{-4.22,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[163] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-162",["layer"]=5,["points"]={{-5.32,-3.73},{-2.68,-3.73}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[164] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-163",["layer"]=5,["points"]={{-4,-2.63},{-4,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[165] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-164",["layer"]=5,["points"]={{-5.32,-3.95},{-2.68,-3.95}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[166] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-165",["layer"]=5,["points"]={{-3.78,-2.63},{-3.78,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[167] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-166",["layer"]=5,["points"]={{-5.32,-4.17},{-2.68,-4.17}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[168] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-167",["layer"]=5,["points"]={{-3.56,-2.63},{-3.56,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[169] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-168",["layer"]=5,["points"]={{-5.32,-4.39},{-2.68,-4.39}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[170] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-169",["layer"]=5,["points"]={{-3.34,-2.63},{-3.34,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[171] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-170",["layer"]=5,["points"]={{-5.32,-4.61},{-2.68,-4.61}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[172] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-171",["layer"]=5,["points"]={{-3.12,-2.63},{-3.12,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[173] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-172",["layer"]=5,["points"]={{-5.32,-4.83},{-2.68,-4.83}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[174] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-173",["layer"]=5,["points"]={{-2.9,-2.63},{-2.9,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[175] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-174",["layer"]=5,["points"]={{-5.32,-5.05},{-2.68,-5.05}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[176] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-175",["layer"]=5,["points"]={{-2.68,-2.63},{-2.68,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[177] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-176",["layer"]=5,["points"]={{-5.32,-5.27},{-2.68,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[178] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-177",["layer"]=40,["point"]={-5.47,-2.63},["size"]=16,["text"]="0"}
refs[179] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-178",["layer"]=40,["point"]={-2.68,-5.46},["size"]=16,["text"]="12"}
refs[180] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-179",["layer"]=5,["points"]={{2.68,-2.63},{2.68,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[181] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-180",["layer"]=5,["points"]={{2.68,-2.63},{5.32,-2.63}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[182] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-181",["layer"]=5,["points"]={{2.9,-2.63},{2.9,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[183] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-182",["layer"]=5,["points"]={{2.68,-2.85},{5.32,-2.85}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[184] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-183",["layer"]=5,["points"]={{3.12,-2.63},{3.12,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[185] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-184",["layer"]=5,["points"]={{2.68,-3.07},{5.32,-3.07}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[186] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-185",["layer"]=5,["points"]={{3.34,-2.63},{3.34,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[187] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-186",["layer"]=5,["points"]={{2.68,-3.29},{5.32,-3.29}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[188] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-187",["layer"]=5,["points"]={{3.56,-2.63},{3.56,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[189] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-188",["layer"]=5,["points"]={{2.68,-3.51},{5.32,-3.51}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[190] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-189",["layer"]=5,["points"]={{3.78,-2.63},{3.78,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[191] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-190",["layer"]=5,["points"]={{2.68,-3.73},{5.32,-3.73}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[192] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-191",["layer"]=5,["points"]={{4,-2.63},{4,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[193] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-192",["layer"]=5,["points"]={{2.68,-3.95},{5.32,-3.95}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[194] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-193",["layer"]=5,["points"]={{4.22,-2.63},{4.22,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[195] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-194",["layer"]=5,["points"]={{2.68,-4.17},{5.32,-4.17}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[196] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-195",["layer"]=5,["points"]={{4.44,-2.63},{4.44,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[197] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-196",["layer"]=5,["points"]={{2.68,-4.39},{5.32,-4.39}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[198] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-197",["layer"]=5,["points"]={{4.66,-2.63},{4.66,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[199] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-198",["layer"]=5,["points"]={{2.68,-4.61},{5.32,-4.61}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[200] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-199",["layer"]=5,["points"]={{4.88,-2.63},{4.88,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[201] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-200",["layer"]=5,["points"]={{2.68,-4.83},{5.32,-4.83}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[202] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-201",["layer"]=5,["points"]={{5.1,-2.63},{5.1,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[203] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-202",["layer"]=5,["points"]={{2.68,-5.05},{5.32,-5.05}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[204] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-203",["layer"]=5,["points"]={{5.32,-2.63},{5.32,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[205] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-204",["layer"]=5,["points"]={{2.68,-5.27},{5.32,-5.27}},["stroke"]="#dedede",["tip"]=0,["width"]=1.3}
refs[206] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-205",["layer"]=40,["point"]={2.53,-2.63},["size"]=16,["text"]="0"}
refs[207] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-206",["layer"]=40,["point"]={5.32,-5.46},["size"]=16,["text"]="12"}
refs[208] = refs[146]:route {["fill"]="#00000000",["id"]="bitmap-data-207",["layer"]=15,["points"]={{-4.44,-3.07},{-3.12,-3.51},{-3.56,-4.83},{-4.88,-4.39},{-4.44,-3.07}},["stroke"]="#b7b7b7",["tip"]=0,["width"]=1.3}
refs[209] = refs[147]:route {["fill"]="#00000000",["id"]="bitmap-data-208",["layer"]=25,["points"]={{-4.66,-3.29},{-3.12,-3.51},{-4,-4.83},{-4.66,-3.29}},["stroke"]="#222222",["tip"]=0,["width"]=1.3}
refs[210] = refs[147]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-209",["layer"]=40,["point"]={-4,-5.73},["size"]=21,["text"]="task.clips.count = 1"}
refs[211] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-210",["layer"]=40,["point"]={0,-3.39},["size"]=23,["text"]="SwImageTask::run()"}
refs[212] = refs[148]:rectangle {["center"]={0,-4.24},["fill"]="#f7f7f7",["id"]="bitmap-data-211",["layer"]=15,["size"]={3.54,1.18},["stroke"]="#222222",["width"]=1.2}
refs[213] = refs[148]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-212",["layer"]=40,["point"]={0,-4},["size"]=22,["text"]="imageGenRle()"}
refs[214] = refs[148]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-213",["layer"]=40,["point"]={0,-4.46},["size"]=21,["text"]="clipper->clip(image.rle)"}
refs[215] = refs[148]:route {["dash"]={5,4},["fill"]="#00000000",["id"]="bitmap-data-214",["layer"]=10,["points"]={{-2.57,-4.1},{-1.87,-4.1}},["stroke"]="#222222",["tip"]=8,["width"]=1.3}
refs[216] = refs[148]:route {["dash"]={5,4},["fill"]="#00000000",["id"]="bitmap-data-215",["layer"]=10,["points"]={{1.87,-4.1},{2.55,-4.1}},["stroke"]="#222222",["tip"]=8,["width"]=1.3}
refs[217] = scene:group {["id"]="bitmap-data-216",["opacity"]=0}
refs[218] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-217",["layer"]=25,["points"]={{3.45,-3.4},{3.67,-3.4}},["stroke"]="#222222b8",["tip"]=0,["width"]=1.3}
refs[219] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-218",["layer"]=25,["points"]={{3.67,-3.37},{3.67,-3.43}},["stroke"]="#222222b8",["tip"]=0,["width"]=1.3}
refs[220] = refs[217]:rectangle {["center"]={3.45,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-219",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[221] = refs[217]:rectangle {["center"]={3.45,-3.4},["fill"]="#222222b8",["id"]="bitmap-data-220",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[222] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-221",["layer"]=25,["points"]={{3.67,-3.4},{3.89,-3.4}},["stroke"]="#222222ca",["tip"]=0,["width"]=1.3}
refs[223] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-222",["layer"]=25,["points"]={{3.89,-3.37},{3.89,-3.43}},["stroke"]="#222222ca",["tip"]=0,["width"]=1.3}
refs[224] = refs[217]:rectangle {["center"]={3.67,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-223",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[225] = refs[217]:rectangle {["center"]={3.67,-3.4},["fill"]="#222222ca",["id"]="bitmap-data-224",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[226] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-225",["layer"]=25,["points"]={{3.89,-3.4},{4.11,-3.4}},["stroke"]="#222222a5",["tip"]=0,["width"]=1.3}
refs[227] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-226",["layer"]=25,["points"]={{4.11,-3.37},{4.11,-3.43}},["stroke"]="#222222a5",["tip"]=0,["width"]=1.3}
refs[228] = refs[217]:rectangle {["center"]={3.89,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-227",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[229] = refs[217]:rectangle {["center"]={3.89,-3.4},["fill"]="#222222a5",["id"]="bitmap-data-228",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[230] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-229",["layer"]=25,["points"]={{4.11,-3.4},{4.33,-3.4}},["stroke"]="#22222281",["tip"]=0,["width"]=1.3}
refs[231] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-230",["layer"]=25,["points"]={{4.33,-3.37},{4.33,-3.43}},["stroke"]="#22222281",["tip"]=0,["width"]=1.3}
refs[232] = refs[217]:rectangle {["center"]={4.11,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-231",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[233] = refs[217]:rectangle {["center"]={4.11,-3.4},["fill"]="#22222281",["id"]="bitmap-data-232",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[234] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-233",["layer"]=25,["points"]={{4.33,-3.4},{4.55,-3.4}},["stroke"]="#2222225c",["tip"]=0,["width"]=1.3}
refs[235] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-234",["layer"]=25,["points"]={{4.55,-3.37},{4.55,-3.43}},["stroke"]="#2222225c",["tip"]=0,["width"]=1.3}
refs[236] = refs[217]:rectangle {["center"]={4.33,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-235",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[237] = refs[217]:rectangle {["center"]={4.33,-3.4},["fill"]="#2222225c",["id"]="bitmap-data-236",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[238] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-237",["layer"]=25,["points"]={{4.55,-3.4},{4.77,-3.4}},["stroke"]="#22222238",["tip"]=0,["width"]=1.3}
refs[239] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-238",["layer"]=25,["points"]={{4.77,-3.37},{4.77,-3.43}},["stroke"]="#22222238",["tip"]=0,["width"]=1.3}
refs[240] = refs[217]:rectangle {["center"]={4.55,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-239",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[241] = refs[217]:rectangle {["center"]={4.55,-3.4},["fill"]="#22222238",["id"]="bitmap-data-240",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[242] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-241",["layer"]=25,["points"]={{4.77,-3.4},{4.99,-3.4}},["stroke"]="#22222213",["tip"]=0,["width"]=1.3}
refs[243] = refs[217]:route {["fill"]="#00000000",["id"]="bitmap-data-242",["layer"]=25,["points"]={{4.99,-3.37},{4.99,-3.43}},["stroke"]="#22222213",["tip"]=0,["width"]=1.3}
refs[244] = refs[217]:rectangle {["center"]={4.77,-3.4},["fill"]="#ffffff",["id"]="bitmap-data-243",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[245] = refs[217]:rectangle {["center"]={4.77,-3.4},["fill"]="#22222213",["id"]="bitmap-data-244",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[246] = scene:group {["id"]="bitmap-data-245",["opacity"]=0}
refs[247] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-246",["layer"]=25,["points"]={{3.45,-3.62},{3.67,-3.62}},["stroke"]="#2222225c",["tip"]=0,["width"]=1.3}
refs[248] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-247",["layer"]=25,["points"]={{3.67,-3.59},{3.67,-3.65}},["stroke"]="#2222225c",["tip"]=0,["width"]=1.3}
refs[249] = refs[246]:rectangle {["center"]={3.45,-3.62},["fill"]="#ffffff",["id"]="bitmap-data-248",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[250] = refs[246]:rectangle {["center"]={3.45,-3.62},["fill"]="#2222225c",["id"]="bitmap-data-249",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[251] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-250",["layer"]=25,["points"]={{3.67,-3.62},{4.77,-3.62}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[252] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-251",["layer"]=25,["points"]={{4.77,-3.59},{4.77,-3.65}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[253] = refs[246]:rectangle {["center"]={3.67,-3.62},["fill"]="#ffffff",["id"]="bitmap-data-252",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[254] = refs[246]:rectangle {["center"]={3.67,-3.62},["fill"]="#222222ff",["id"]="bitmap-data-253",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[255] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-254",["layer"]=25,["points"]={{4.77,-3.62},{4.99,-3.62}},["stroke"]="#222222ab",["tip"]=0,["width"]=1.3}
refs[256] = refs[246]:route {["fill"]="#00000000",["id"]="bitmap-data-255",["layer"]=25,["points"]={{4.99,-3.59},{4.99,-3.65}},["stroke"]="#222222ab",["tip"]=0,["width"]=1.3}
refs[257] = refs[246]:rectangle {["center"]={4.77,-3.62},["fill"]="#ffffff",["id"]="bitmap-data-256",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[258] = refs[246]:rectangle {["center"]={4.77,-3.62},["fill"]="#222222ab",["id"]="bitmap-data-257",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[259] = scene:group {["id"]="bitmap-data-258",["opacity"]=0}
refs[260] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-259",["layer"]=25,["points"]={{3.45,-3.84},{3.67,-3.84}},["stroke"]="#22222207",["tip"]=0,["width"]=1.3}
refs[261] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-260",["layer"]=25,["points"]={{3.67,-3.81},{3.67,-3.87}},["stroke"]="#22222207",["tip"]=0,["width"]=1.3}
refs[262] = refs[259]:rectangle {["center"]={3.45,-3.84},["fill"]="#ffffff",["id"]="bitmap-data-261",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[263] = refs[259]:rectangle {["center"]={3.45,-3.84},["fill"]="#22222207",["id"]="bitmap-data-262",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[264] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-263",["layer"]=25,["points"]={{3.67,-3.84},{3.89,-3.84}},["stroke"]="#222222e8",["tip"]=0,["width"]=1.3}
refs[265] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-264",["layer"]=25,["points"]={{3.89,-3.81},{3.89,-3.87}},["stroke"]="#222222e8",["tip"]=0,["width"]=1.3}
refs[266] = refs[259]:rectangle {["center"]={3.67,-3.84},["fill"]="#ffffff",["id"]="bitmap-data-265",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[267] = refs[259]:rectangle {["center"]={3.67,-3.84},["fill"]="#222222e8",["id"]="bitmap-data-266",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[268] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-267",["layer"]=25,["points"]={{3.89,-3.84},{4.55,-3.84}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[269] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-268",["layer"]=25,["points"]={{4.55,-3.81},{4.55,-3.87}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[270] = refs[259]:rectangle {["center"]={3.89,-3.84},["fill"]="#ffffff",["id"]="bitmap-data-269",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[271] = refs[259]:rectangle {["center"]={3.89,-3.84},["fill"]="#222222ff",["id"]="bitmap-data-270",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[272] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-271",["layer"]=25,["points"]={{4.55,-3.84},{4.77,-3.84}},["stroke"]="#222222eb",["tip"]=0,["width"]=1.3}
refs[273] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-272",["layer"]=25,["points"]={{4.77,-3.81},{4.77,-3.87}},["stroke"]="#222222eb",["tip"]=0,["width"]=1.3}
refs[274] = refs[259]:rectangle {["center"]={4.55,-3.84},["fill"]="#ffffff",["id"]="bitmap-data-273",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[275] = refs[259]:rectangle {["center"]={4.55,-3.84},["fill"]="#222222eb",["id"]="bitmap-data-274",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[276] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-275",["layer"]=25,["points"]={{4.77,-3.84},{4.99,-3.84}},["stroke"]="#22222216",["tip"]=0,["width"]=1.3}
refs[277] = refs[259]:route {["fill"]="#00000000",["id"]="bitmap-data-276",["layer"]=25,["points"]={{4.99,-3.81},{4.99,-3.87}},["stroke"]="#22222216",["tip"]=0,["width"]=1.3}
refs[278] = refs[259]:rectangle {["center"]={4.77,-3.84},["fill"]="#ffffff",["id"]="bitmap-data-277",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[279] = refs[259]:rectangle {["center"]={4.77,-3.84},["fill"]="#22222216",["id"]="bitmap-data-278",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[280] = scene:group {["id"]="bitmap-data-279",["opacity"]=0}
refs[281] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-280",["layer"]=25,["points"]={{3.67,-4.06},{3.89,-4.06}},["stroke"]="#22222281",["tip"]=0,["width"]=1.3}
refs[282] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-281",["layer"]=25,["points"]={{3.89,-4.03},{3.89,-4.09}},["stroke"]="#22222281",["tip"]=0,["width"]=1.3}
refs[283] = refs[280]:rectangle {["center"]={3.67,-4.06},["fill"]="#ffffff",["id"]="bitmap-data-282",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[284] = refs[280]:rectangle {["center"]={3.67,-4.06},["fill"]="#22222281",["id"]="bitmap-data-283",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[285] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-284",["layer"]=25,["points"]={{3.89,-4.06},{4.55,-4.06}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[286] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-285",["layer"]=25,["points"]={{4.55,-4.03},{4.55,-4.09}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[287] = refs[280]:rectangle {["center"]={3.89,-4.06},["fill"]="#ffffff",["id"]="bitmap-data-286",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[288] = refs[280]:rectangle {["center"]={3.89,-4.06},["fill"]="#222222ff",["id"]="bitmap-data-287",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[289] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-288",["layer"]=25,["points"]={{4.55,-4.06},{4.77,-4.06}},["stroke"]="#22222255",["tip"]=0,["width"]=1.3}
refs[290] = refs[280]:route {["fill"]="#00000000",["id"]="bitmap-data-289",["layer"]=25,["points"]={{4.77,-4.03},{4.77,-4.09}},["stroke"]="#22222255",["tip"]=0,["width"]=1.3}
refs[291] = refs[280]:rectangle {["center"]={4.55,-4.06},["fill"]="#ffffff",["id"]="bitmap-data-290",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[292] = refs[280]:rectangle {["center"]={4.55,-4.06},["fill"]="#22222255",["id"]="bitmap-data-291",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[293] = scene:group {["id"]="bitmap-data-292",["opacity"]=0}
refs[294] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-293",["layer"]=25,["points"]={{3.67,-4.28},{3.89,-4.28}},["stroke"]="#22222219",["tip"]=0,["width"]=1.3}
refs[295] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-294",["layer"]=25,["points"]={{3.89,-4.25},{3.89,-4.31}},["stroke"]="#22222219",["tip"]=0,["width"]=1.3}
refs[296] = refs[293]:rectangle {["center"]={3.67,-4.28},["fill"]="#ffffff",["id"]="bitmap-data-295",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[297] = refs[293]:rectangle {["center"]={3.67,-4.28},["fill"]="#22222219",["id"]="bitmap-data-296",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[298] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-297",["layer"]=25,["points"]={{3.89,-4.28},{4.11,-4.28}},["stroke"]="#222222fa",["tip"]=0,["width"]=1.3}
refs[299] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-298",["layer"]=25,["points"]={{4.11,-4.25},{4.11,-4.31}},["stroke"]="#222222fa",["tip"]=0,["width"]=1.3}
refs[300] = refs[293]:rectangle {["center"]={3.89,-4.28},["fill"]="#ffffff",["id"]="bitmap-data-299",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[301] = refs[293]:rectangle {["center"]={3.89,-4.28},["fill"]="#222222fa",["id"]="bitmap-data-300",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[302] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-301",["layer"]=25,["points"]={{4.11,-4.28},{4.33,-4.28}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[303] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-302",["layer"]=25,["points"]={{4.33,-4.25},{4.33,-4.31}},["stroke"]="#222222ff",["tip"]=0,["width"]=1.3}
refs[304] = refs[293]:rectangle {["center"]={4.11,-4.28},["fill"]="#ffffff",["id"]="bitmap-data-303",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[305] = refs[293]:rectangle {["center"]={4.11,-4.28},["fill"]="#222222ff",["id"]="bitmap-data-304",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[306] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-305",["layer"]=25,["points"]={{4.33,-4.28},{4.55,-4.28}},["stroke"]="#222222ab",["tip"]=0,["width"]=1.3}
refs[307] = refs[293]:route {["fill"]="#00000000",["id"]="bitmap-data-306",["layer"]=25,["points"]={{4.55,-4.25},{4.55,-4.31}},["stroke"]="#222222ab",["tip"]=0,["width"]=1.3}
refs[308] = refs[293]:rectangle {["center"]={4.33,-4.28},["fill"]="#ffffff",["id"]="bitmap-data-307",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[309] = refs[293]:rectangle {["center"]={4.33,-4.28},["fill"]="#222222ab",["id"]="bitmap-data-308",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[310] = scene:group {["id"]="bitmap-data-309",["opacity"]=0}
refs[311] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-310",["layer"]=25,["points"]={{3.89,-4.5},{4.11,-4.5}},["stroke"]="#222222a5",["tip"]=0,["width"]=1.3}
refs[312] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-311",["layer"]=25,["points"]={{4.11,-4.47},{4.11,-4.53}},["stroke"]="#222222a5",["tip"]=0,["width"]=1.3}
refs[313] = refs[310]:rectangle {["center"]={3.89,-4.5},["fill"]="#ffffff",["id"]="bitmap-data-312",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[314] = refs[310]:rectangle {["center"]={3.89,-4.5},["fill"]="#222222a5",["id"]="bitmap-data-313",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[315] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-314",["layer"]=25,["points"]={{4.11,-4.5},{4.33,-4.5}},["stroke"]="#222222eb",["tip"]=0,["width"]=1.3}
refs[316] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-315",["layer"]=25,["points"]={{4.33,-4.47},{4.33,-4.53}},["stroke"]="#222222eb",["tip"]=0,["width"]=1.3}
refs[317] = refs[310]:rectangle {["center"]={4.11,-4.5},["fill"]="#ffffff",["id"]="bitmap-data-316",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[318] = refs[310]:rectangle {["center"]={4.11,-4.5},["fill"]="#222222eb",["id"]="bitmap-data-317",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[319] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-318",["layer"]=25,["points"]={{4.33,-4.5},{4.55,-4.5}},["stroke"]="#22222216",["tip"]=0,["width"]=1.3}
refs[320] = refs[310]:route {["fill"]="#00000000",["id"]="bitmap-data-319",["layer"]=25,["points"]={{4.55,-4.47},{4.55,-4.53}},["stroke"]="#22222216",["tip"]=0,["width"]=1.3}
refs[321] = refs[310]:rectangle {["center"]={4.33,-4.5},["fill"]="#ffffff",["id"]="bitmap-data-320",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[322] = refs[310]:rectangle {["center"]={4.33,-4.5},["fill"]="#22222216",["id"]="bitmap-data-321",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[323] = scene:group {["id"]="bitmap-data-322",["opacity"]=0}
refs[324] = refs[323]:route {["fill"]="#00000000",["id"]="bitmap-data-323",["layer"]=25,["points"]={{3.89,-4.72},{4.11,-4.72}},["stroke"]="#22222238",["tip"]=0,["width"]=1.3}
refs[325] = refs[323]:route {["fill"]="#00000000",["id"]="bitmap-data-324",["layer"]=25,["points"]={{4.11,-4.69},{4.11,-4.75}},["stroke"]="#22222238",["tip"]=0,["width"]=1.3}
refs[326] = refs[323]:rectangle {["center"]={3.89,-4.72},["fill"]="#ffffff",["id"]="bitmap-data-325",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[327] = refs[323]:rectangle {["center"]={3.89,-4.72},["fill"]="#22222238",["id"]="bitmap-data-326",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[328] = refs[323]:route {["fill"]="#00000000",["id"]="bitmap-data-327",["layer"]=25,["points"]={{4.11,-4.72},{4.33,-4.72}},["stroke"]="#22222255",["tip"]=0,["width"]=1.3}
refs[329] = refs[323]:route {["fill"]="#00000000",["id"]="bitmap-data-328",["layer"]=25,["points"]={{4.33,-4.69},{4.33,-4.75}},["stroke"]="#22222255",["tip"]=0,["width"]=1.3}
refs[330] = refs[323]:rectangle {["center"]={4.11,-4.72},["fill"]="#ffffff",["id"]="bitmap-data-329",["layer"]=26,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[331] = refs[323]:rectangle {["center"]={4.11,-4.72},["fill"]="#22222255",["id"]="bitmap-data-330",["layer"]=27,["size"]={0.11,0.11},["stroke"]="#00000000",["width"]=1.2}
refs[332] = refs[149]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-331",["layer"]=40,["point"]={4,-5.73},["size"]=22,["text"]="image.rle → SwRle::spans"}
refs[333] = refs[149]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-332",["layer"]=40,["point"]={4,-6.12},["size"]=20,["text"]="x · y · len · coverage"}
refs[334] = scene:group {["id"]="bitmap-data-333",["opacity"]=0}
refs[335] = refs[334]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="bitmap-data-334",["layer"]=40,["point"]={0,-6.71},["size"]=23,["text"]="task.curBox · task.transform · image.data → Draw"}
refs[336] = refs[334]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="bitmap-data-335",["layer"]=40,["point"]={0,-7.14},["size"]=20,["text"]="Outline → pool     RLE → task.image.rle"}
scene:wait(1)
scene:play({{target=refs[43],transform={1,0,0,-4.88,0,1,0,2.77,0,0,1,0,0,0,0,1}}},1.1,"ease_in_out",0)
scene:play({{target=refs[49],opacity=1}},0.15,"ease_in_out",0)
scene:create(refs[50],0.35,"linear",0)
scene:play({{target=refs[48],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.2)
scene:play({{target=refs[88],transform={3,0,0,-0.66,0,2,0,2.77,0,0,1,0,0,0,0,1}}},1.1,"ease_in_out",0)
scene:play({{target=refs[94],opacity=1}},0.15,"ease_in_out",0)
scene:create(refs[95],0.35,"linear",0)
scene:play({{target=refs[93],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.2)
scene:play({{target=refs[133],transform={3,1,0,3.78,-1,3,0,3.21,0,0,1,0,0,0,0,1}}},1.1,"ease_in_out",0)
scene:play({{target=refs[139],opacity=1}},0.15,"ease_in_out",0)
scene:create(refs[140],0.35,"linear",0)
scene:play({{target=refs[138],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.2)
scene:play({{target=refs[146],opacity=1}},0.5,"ease_in_out",0)
scene:play({{target=refs[147],opacity=1}},0.2,"ease_in_out",0)
scene:create(refs[209],0.7,"linear",0)
scene:wait(1)
scene:play({{target=refs[148],opacity=1}},0.4,"ease_in_out",0)
scene:create({refs[215],refs[216]},0.3,"linear",0)
scene:play({{target=refs[217],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[218],refs[222],refs[226],refs[230],refs[234],refs[238],refs[242]},0.09,"linear",0)
scene:play({{target=refs[246],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[247],refs[251],refs[255]},0.09,"linear",0)
scene:play({{target=refs[259],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[260],refs[264],refs[268],refs[272],refs[276]},0.09,"linear",0)
scene:play({{target=refs[280],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[281],refs[285],refs[289]},0.09,"linear",0)
scene:play({{target=refs[293],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[294],refs[298],refs[302],refs[306]},0.09,"linear",0)
scene:play({{target=refs[310],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[311],refs[315],refs[319]},0.09,"linear",0)
scene:play({{target=refs[323],opacity=1}},0.06,"ease_in_out",0)
scene:create({refs[324],refs[328]},0.09,"linear",0)
scene:play({{target=refs[149],opacity=1}},0.35,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[334],opacity=1}},0.4,"ease_in_out",0)
scene:wait(2.2)
return scene
