-- Generated by scripts/render-update-scenes.mjs; edit rle.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=8,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=800,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1200}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-0",["layer"]=50,["point"]={0,3.58},["role"]="text",["size"]=30,["text"]="Path → band-local cells"}
refs[2] = scene:line {["from"]={-5.55,3.2},["id"]="update-cells-line-1",["layer"]=25,["stroke"]="#cccccc",["to"]={5.55,3.2},["width"]=1}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-2",["layer"]=50,["point"]={-4.45,2.85},["role"]="text",["size"]=23,["text"]="Outline"}
refs[4] = scene:arrow {["dash"]={6,5},["from"]={-3.83,2.85},["id"]="update-cells-arrow-3",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={-3.1,2.85},["width"]=1.5}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-4",["layer"]=50,["point"]={-2.53,2.85},["role"]="text",["size"]=23,["text"]="26.6"}
refs[6] = scene:arrow {["dash"]={6,5},["from"]={-1.98,2.85},["id"]="update-cells-arrow-5",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={-1.25,2.85},["width"]=1.5}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-6",["layer"]=50,["point"]={-0.68,2.85},["role"]="text",["size"]=23,["text"]="24.8"}
refs[8] = scene:arrow {["dash"]={6,5},["from"]={-0.13,2.85},["id"]="update-cells-arrow-7",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={0.6,2.85},["width"]=1.5}
refs[9] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-8",["layer"]=50,["point"]={1.24,2.85},["role"]="text",["size"]=23,["text"]="Band"}
refs[10] = scene:arrow {["dash"]={6,5},["from"]={1.8,2.85},["id"]="update-cells-arrow-9",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.53,2.85},["width"]=1.5}
refs[11] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-10",["layer"]=50,["point"]={3.83,2.85},["role"]="text",["size"]=23,["text"]="cover / area"}
refs[12] = scene:group {["id"]="update-cells-group-11"}
refs[13] = refs[12]:line {["from"]={-5.35,2.1},["id"]="update-cells-line-12",["layer"]=25,["stroke"]="#cccccc",["to"]={-5.35,-2.04},["width"]=1}
refs[14] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-13",["layer"]=50,["point"]={-5.35,2.3},["role"]="text",["size"]=16,["text"]="0"}
refs[15] = refs[12]:line {["from"]={-4.66,2.1},["id"]="update-cells-line-14",["layer"]=25,["stroke"]="#cccccc",["to"]={-4.66,-2.04},["width"]=1}
refs[16] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-15",["layer"]=50,["point"]={-4.66,2.3},["role"]="text",["size"]=16,["text"]="1"}
refs[17] = refs[12]:line {["from"]={-3.97,2.1},["id"]="update-cells-line-16",["layer"]=25,["stroke"]="#cccccc",["to"]={-3.97,-2.04},["width"]=1}
refs[18] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-17",["layer"]=50,["point"]={-3.97,2.3},["role"]="text",["size"]=16,["text"]="2"}
refs[19] = refs[12]:line {["from"]={-3.28,2.1},["id"]="update-cells-line-18",["layer"]=25,["stroke"]="#cccccc",["to"]={-3.28,-2.04},["width"]=1}
refs[20] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-19",["layer"]=50,["point"]={-3.28,2.3},["role"]="text",["size"]=16,["text"]="3"}
refs[21] = refs[12]:line {["from"]={-2.59,2.1},["id"]="update-cells-line-20",["layer"]=25,["stroke"]="#cccccc",["to"]={-2.59,-2.04},["width"]=1}
refs[22] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-21",["layer"]=50,["point"]={-2.59,2.3},["role"]="text",["size"]=16,["text"]="4"}
refs[23] = refs[12]:line {["from"]={-1.9,2.1},["id"]="update-cells-line-22",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.9,-2.04},["width"]=1}
refs[24] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-23",["layer"]=50,["point"]={-1.9,2.3},["role"]="text",["size"]=16,["text"]="5"}
refs[25] = refs[12]:line {["from"]={-1.21,2.1},["id"]="update-cells-line-24",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.21,-2.04},["width"]=1}
refs[26] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-25",["layer"]=50,["point"]={-1.21,2.3},["role"]="text",["size"]=16,["text"]="6"}
refs[27] = refs[12]:line {["from"]={-0.52,2.1},["id"]="update-cells-line-26",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,-2.04},["width"]=1}
refs[28] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-27",["layer"]=50,["point"]={-0.52,2.3},["role"]="text",["size"]=16,["text"]="7"}
refs[29] = refs[12]:line {["from"]={-5.35,2.1},["id"]="update-cells-line-28",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,2.1},["width"]=1}
refs[30] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-29",["layer"]=50,["point"]={-5.57,2.1},["role"]="text",["size"]=16,["text"]="0"}
refs[31] = refs[12]:line {["from"]={-5.35,1.41},["id"]="update-cells-line-30",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,1.41},["width"]=1}
refs[32] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-31",["layer"]=50,["point"]={-5.57,1.41},["role"]="text",["size"]=16,["text"]="1"}
refs[33] = refs[12]:line {["from"]={-5.35,0.72},["id"]="update-cells-line-32",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,0.72},["width"]=1}
refs[34] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-33",["layer"]=50,["point"]={-5.57,0.72},["role"]="text",["size"]=16,["text"]="2"}
refs[35] = refs[12]:line {["from"]={-5.35,0.03},["id"]="update-cells-line-34",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,0.03},["width"]=1}
refs[36] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-35",["layer"]=50,["point"]={-5.57,0.03},["role"]="text",["size"]=16,["text"]="3"}
refs[37] = refs[12]:line {["from"]={-5.35,-0.66},["id"]="update-cells-line-36",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,-0.66},["width"]=1}
refs[38] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-37",["layer"]=50,["point"]={-5.57,-0.66},["role"]="text",["size"]=16,["text"]="4"}
refs[39] = refs[12]:line {["from"]={-5.35,-1.35},["id"]="update-cells-line-38",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,-1.35},["width"]=1}
refs[40] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-39",["layer"]=50,["point"]={-5.57,-1.35},["role"]="text",["size"]=16,["text"]="5"}
refs[41] = refs[12]:line {["from"]={-5.35,-2.04},["id"]="update-cells-line-40",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.52,-2.04},["width"]=1}
refs[42] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-41",["layer"]=50,["point"]={-5.57,-2.04},["role"]="text",["size"]=16,["text"]="6"}
refs[43] = refs[12]:path {["commands"]={{["to"]={-4.4875,1.2375},["type"]="move"},{["to"]={-4.4875,-0.8325},["type"]="line"},{["control1"]={-3.28,-1.5225},["control2"]={-1.3825,-0.8325},["to"]={-1.7275,0.8925},["type"]="cubic"},{["type"]="close"}},["fill"]="#df792b12",["id"]="update-cells-outline-42",["layer"]=20,["stroke"]="#202020",["width"]=2.2}
refs[44] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-43",["layer"]=50,["point"]={-2.96,-2.58},["role"]="text",["size"]=18,["text"]="Screen coordinates · +y ↓"}
refs[45] = scene:group {["id"]="update-cells-group-44"}
refs[46] = refs[45]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-45",["layer"]=50,["point"]={2.83,1.85},["role"]="text",["size"]=23,["text"]="MoveTo → LineTo → CubicTo → Close"}
refs[47] = refs[45]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-46",["layer"]=50,["point"]={2.9,1.1},["role"]="text",["size"]=28,["text"]="(1.25, 1.25)"}
refs[48] = scene:group {["id"]="update-cells-group-47"}
refs[49] = refs[48]:arrow {["from"]={2.9,0.75},["id"]="update-cells-arrow-48",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.9,0.33},["width"]=1.6}
refs[50] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-49",["layer"]=50,["point"]={2.9,-0.08},["role"]="text",["size"]=31,["text"]="(80, 80)"}
refs[51] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-50",["layer"]=50,["point"]={4.6,-0.08},["role"]="text",["size"]=18,["text"]="× 64"}
refs[52] = refs[48]:arrow {["from"]={2.9,-0.41},["id"]="update-cells-arrow-51",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.9,-0.82},["width"]=1.6}
refs[53] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-52",["layer"]=50,["point"]={2.9,-1.24},["role"]="text",["size"]=31,["text"]="(320, 320)"}
refs[54] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-53",["layer"]=50,["point"]={4.6,-1.24},["role"]="text",["size"]=18,["text"]="<< 2"}
refs[55] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-54",["layer"]=50,["point"]={2.9,-1.93},["role"]="text",["size"]=22,["text"]="1 pixel = 256 subpixels"}
refs[56] = scene:point {["fill"]="#df792b",["id"]="update-cells-start-point-55",["layer"]=40,["point"]={-4.4875,1.2375},["radius"]=6}
refs[57] = scene:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-56",["layer"]=50,["point"]={-4.6675,1.4175},["role"]="text",["size"]=18,["text"]="A"}
scene:wait(1)
scene:fade_in(refs[48],{["curve"]="ease_out",["duration"]=0.65,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.3)
scene:fade_out(refs[45],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[48],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
refs[58] = scene:group {["id"]="update-cells-group-57"}
refs[59] = refs[58]:rectangle {["center"]={-2.935,0.03},["fill"]="#20202009",["id"]="update-cells-rect-58",["layer"]=8,["size"]={4.83,1.38},["stroke"]="#00000000",["width"]=0}
refs[60] = refs[58]:line {["dash"]={7,5},["from"]={-5.35,0.72},["id"]="update-cells-line-59",["layer"]=25,["stroke"]="#202020",["to"]={-0.52,0.72},["width"]=2}
refs[61] = refs[58]:line {["dash"]={7,5},["from"]={-5.35,-0.66},["id"]="update-cells-line-60",["layer"]=25,["stroke"]="#202020",["to"]={-0.52,-0.66},["width"]=2}
refs[62] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-61",["layer"]=50,["point"]={2.87,1.9},["role"]="text",["size"]=26,["text"]="Band [2, 4)"}
refs[63] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-62",["layer"]=50,["point"]={2.87,1.44},["role"]="text",["size"]=23,["text"]="local y = world y − 2"}
refs[64] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-63",["layer"]=50,["point"]={2.87,1.1},["role"]="text",["size"]=21,["text"]="local x = world x − 1"}
scene:fade_in(refs[58],{["curve"]="ease_out",["duration"]=0.5,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.8)
refs[65] = scene:group {["id"]="update-cells-group-64"}
refs[66] = refs[65]:rectangle {["center"]={2.5,-0.05},["fill"]="#ffffff",["id"]="update-cells-rect-65",["layer"]=15,["size"]={1.8,1.8},["stroke"]="#202020",["width"]=2}
refs[67] = scene:group {["id"]="update-cells-group-66"}
refs[68] = refs[67]:rectangle {["center"]={1.825,-0.05},["fill"]="#df792b55",["id"]="update-cells-rect-67",["layer"]=19,["size"]={0.45,1.8},["stroke"]="#00000000",["width"]=0}
refs[69] = refs[67]:line {["from"]={2.05,0.85},["id"]="update-cells-line-68",["layer"]=25,["stroke"]="#df792b",["to"]={2.05,-0.95},["width"]=5}
refs[70] = refs[67]:arrow {["from"]={3.75,0.85},["id"]="update-cells-arrow-69",["layer"]=25,["stroke"]="#df792b",["tip"]=9,["to"]={3.75,-0.95},["width"]=2}
refs[71] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-70",["layer"]=50,["point"]={4.27,-0.05},["role"]="text",["size"]=23,["text"]="+256"}
refs[72] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-71",["layer"]=50,["point"]={2.46,-1.45},["role"]="text",["size"]=25,["text"]="cover +256"}
refs[73] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-72",["layer"]=50,["point"]={2.46,-1.88},["role"]="text",["size"]=25,["text"]="area 32,768"}
refs[74] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-73",["layer"]=50,["point"]={2.46,-2.32},["role"]="text",["size"]=21,["text"]="2 × x × Δy"}
refs[75] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-74",["layer"]=50,["point"]={2.46,-3},["role"]="text",["size"]=22,["text"]="Cell (1, 2)"}
refs[76] = scene:line {["from"]={-4.4875,1.2375},["id"]="update-cells-line-75",["layer"]=25,["stroke"]="#df792b",["to"]={-4.4875,-0.8325},["width"]=5}
refs[77] = scene:rectangle {["center"]={-4.315,0.375},["fill"]="#df792b25",["id"]="update-cells-rect-76",["layer"]=17,["size"]={0.69,0.69},["stroke"]="#df792b",["width"]=2}
refs[78] = scene:rectangle {["center"]={-1.555,0.375},["fill"]="#3f7cce25",["id"]="update-cells-rect-77",["layer"]=17,["size"]={0.69,0.69},["stroke"]="#3f7cce",["width"]=2}
refs[79] = scene:rectangle {["center"]={-4.315,-0.315},["fill"]="#df792b25",["id"]="update-cells-rect-78",["layer"]=17,["size"]={0.69,0.69},["stroke"]="#df792b",["width"]=2}
refs[80] = scene:rectangle {["center"]={-2.245,-0.315},["fill"]="#3f7cce25",["id"]="update-cells-rect-79",["layer"]=17,["size"]={0.69,0.69},["stroke"]="#3f7cce",["width"]=2}
refs[81] = scene:rectangle {["center"]={-1.555,-0.315},["fill"]="#3f7cce25",["id"]="update-cells-rect-80",["layer"]=17,["size"]={0.69,0.69},["stroke"]="#3f7cce",["width"]=2}
scene:create(refs[76],1,"linear",0)
scene:fade_in(refs[65],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[67],{["curve"]="ease_out",["duration"]=0.7,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[77],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[79],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.4)
scene:fade_out(refs[65],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[67],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
refs[82] = scene:group {["id"]="update-cells-group-81"}
refs[83] = refs[82]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-82",["layer"]=50,["point"]={2.86,0.74},["role"]="text",["size"]=26,["text"]="CubicTo → accepted chords"}
refs[84] = scene:group {["id"]="update-cells-group-83"}
refs[85] = refs[84]:line {["dash"]={6,5},["from"]={-4.4875,-0.8325},["id"]="update-cells-line-84",["layer"]=25,["stroke"]="#3f7cce",["to"]={-3.28,-1.5225},["width"]=1.4}
refs[86] = refs[84]:line {["dash"]={6,5},["from"]={-1.3825,-0.8325},["id"]="update-cells-line-85",["layer"]=25,["stroke"]="#3f7cce",["to"]={-1.7275,0.8925},["width"]=1.4}
refs[87] = refs[84]:point {["fill"]="#3f7cce",["id"]="update-cells-control-86",["layer"]=40,["point"]={-3.28,-1.5225},["radius"]=4}
refs[88] = refs[84]:point {["fill"]="#3f7cce",["id"]="update-cells-control-87",["layer"]=40,["point"]={-1.3825,-0.8325},["radius"]=4}
scene:fade_in(refs[84],{["curve"]="ease_out",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[82],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[89] = scene:line {["dash"]={6,5},["from"]={-4.4875,-0.8325},["id"]="update-cells-line-88",["layer"]=35,["stroke"]="#707070",["to"]={-3.4983203125,-1.096640625},["width"]=2}
scene:create(refs[89],0.45,"linear",0)
refs[90] = scene:line {["dash"]={6,5},["from"]={-3.4983203125,-1.096640625},["id"]="update-cells-line-89",["layer"]=35,["stroke"]="#707070",["to"]={-2.5253125,-0.875625},["width"]=2}
scene:create(refs[90],0.45,"linear",0)
refs[91] = scene:line {["from"]={-2.5253125,-0.875625},["id"]="update-cells-line-90",["layer"]=35,["stroke"]="#3f7cce",["to"]={-1.8433984375,-0.201796875},["width"]=4}
scene:create(refs[91],0.45,"linear",0)
refs[92] = scene:line {["from"]={-1.8433984375,-0.201796875},["id"]="update-cells-line-91",["layer"]=35,["stroke"]="#3f7cce",["to"]={-1.6978515625,0.2968359375},["width"]=4}
scene:create(refs[92],0.45,"linear",0)
refs[93] = scene:line {["from"]={-1.6978515625,0.2968359375},["id"]="update-cells-line-92",["layer"]=35,["stroke"]="#3f7cce",["to"]={-1.7275,0.8925},["width"]=4}
scene:create(refs[93],0.45,"linear",0)
scene:fade_in(refs[78],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[80],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[81],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
refs[94] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-93",["layer"]=50,["point"]={2.86,0.17},["role"]="text",["size"]=24,["text"]="5 chords → _lineTo()"}
scene:fade_in(refs[94],{["curve"]="ease_out",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.2)
scene:fade_out(refs[84],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[82],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[94],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
refs[95] = scene:group {["id"]="update-cells-group-94"}
refs[96] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-95",["layer"]=50,["point"]={2.65,0.65},["role"]="text",["size"]=26,["text"]="yCells"}
refs[97] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-96",["layer"]=50,["point"]={0.65,-0.11},["role"]="text",["size"]=22,["text"]="[0]"}
refs[98] = refs[95]:rectangle {["center"]={1.54,-0.11},["fill"]="#ffffff",["id"]="update-cells-rect-97",["layer"]=15,["size"]={1.07,0.63},["stroke"]="#202020",["width"]=1.5}
refs[99] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-98",["layer"]=50,["point"]={1.54,-0.11},["role"]="text",["size"]=23,["text"]="x 0"}
refs[100] = refs[95]:arrow {["from"]={2.1,-0.11},["id"]="update-cells-arrow-99",["layer"]=25,["stroke"]="#202020",["tip"]=9,["to"]={2.29,-0.11},["width"]=1.2}
refs[101] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-100",["layer"]=50,["point"]={1.54,-0.65},["role"]="text",["size"]=18,["text"]="256"}
refs[102] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-101",["layer"]=50,["point"]={1.54,-0.9},["role"]="text",["size"]=17,["text"]="32768"}
refs[103] = refs[95]:rectangle {["center"]={2.89,-0.11},["fill"]="#ffffff",["id"]="update-cells-rect-102",["layer"]=15,["size"]={1.07,0.63},["stroke"]="#202020",["width"]=1.5}
refs[104] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-103",["layer"]=50,["point"]={2.89,-0.11},["role"]="text",["size"]=23,["text"]="x 4"}
refs[105] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-104",["layer"]=50,["point"]={2.89,-0.65},["role"]="text",["size"]=18,["text"]="-256"}
refs[106] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-105",["layer"]=50,["point"]={2.89,-0.9},["role"]="text",["size"]=17,["text"]="-34273"}
refs[107] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-106",["layer"]=50,["point"]={0.65,-1.43},["role"]="text",["size"]=22,["text"]="[1]"}
refs[108] = refs[95]:rectangle {["center"]={1.54,-1.43},["fill"]="#ffffff",["id"]="update-cells-rect-107",["layer"]=15,["size"]={1.07,0.63},["stroke"]="#202020",["width"]=1.5}
refs[109] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-108",["layer"]=50,["point"]={1.54,-1.43},["role"]="text",["size"]=23,["text"]="x 0"}
refs[110] = refs[95]:arrow {["from"]={2.1,-1.43},["id"]="update-cells-arrow-109",["layer"]=25,["stroke"]="#202020",["tip"]=9,["to"]={2.29,-1.43},["width"]=1.2}
refs[111] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-cells-text-110",["layer"]=50,["point"]={1.54,-1.97},["role"]="text",["size"]=18,["text"]="256"}
refs[112] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-111",["layer"]=50,["point"]={1.54,-2.22},["role"]="text",["size"]=17,["text"]="32768"}
refs[113] = refs[95]:rectangle {["center"]={2.89,-1.43},["fill"]="#ffffff",["id"]="update-cells-rect-112",["layer"]=15,["size"]={1.07,0.63},["stroke"]="#202020",["width"]=1.5}
refs[114] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-113",["layer"]=50,["point"]={2.89,-1.43},["role"]="text",["size"]=23,["text"]="x 3"}
refs[115] = refs[95]:arrow {["from"]={3.45,-1.43},["id"]="update-cells-arrow-114",["layer"]=25,["stroke"]="#202020",["tip"]=9,["to"]={3.64,-1.43},["width"]=1.2}
refs[116] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-115",["layer"]=50,["point"]={2.89,-1.97},["role"]="text",["size"]=18,["text"]="-150"}
refs[117] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-116",["layer"]=50,["point"]={2.89,-2.22},["role"]="text",["size"]=17,["text"]="-54000"}
refs[118] = refs[95]:rectangle {["center"]={4.24,-1.43},["fill"]="#ffffff",["id"]="update-cells-rect-117",["layer"]=15,["size"]={1.07,0.63},["stroke"]="#202020",["width"]=1.5}
refs[119] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-118",["layer"]=50,["point"]={4.24,-1.43},["role"]="text",["size"]=23,["text"]="x 4"}
refs[120] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-cells-text-119",["layer"]=50,["point"]={4.24,-1.97},["role"]="text",["size"]=18,["text"]="-106"}
refs[121] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-120",["layer"]=50,["point"]={4.24,-2.22},["role"]="text",["size"]=17,["text"]="-6182"}
refs[122] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-121",["layer"]=50,["point"]={5.1,-0.65},["role"]="text",["size"]=17,["text"]="cover"}
refs[123] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-cells-text-122",["layer"]=50,["point"]={5.1,-0.9},["role"]="text",["size"]=17,["text"]="area"}
refs[124] = refs[95]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-cells-text-123",["layer"]=50,["point"]={2.76,-2.71},["role"]="text",["size"]=24,["text"]="5 cells · sorted by x"}
scene:fade_in(refs[95],{["curve"]="ease_out",["duration"]=0.6,["scale"]=1,["shift"]={0,0,0}})
scene:wait(2)
return scene
