-- Generated by scripts/render-update-scenes.mjs; edit prepare.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=9,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=900,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#222222",["font"]="Pretendard"},["h1"]={["color"]="#222222",["font"]="Pretendard"},["h2"]={["color"]="#222222",["font"]="Pretendard"},["h3"]={["color"]="#222222",["font"]="Pretendard"},["text"]={["color"]="#222222",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-0",["layer"]=40,["point"]={0,4.07},["role"]="text",["size"]=27,["text"]="picture->transform(M);  picture->clip(clip);  canvas->update();"}
refs[2] = scene:rectangle {["center"]={0,3.2},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-image-rect-1",["layer"]=10,["size"]={2.65,0.64},["stroke"]="#222222",["width"]=1.4}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-2",["layer"]=40,["point"]={0,3.2},["role"]="text",["size"]=24,["text"]="Picture::update()"}
refs[4] = scene:group {["id"]="update-image-group-3"}
refs[5] = refs[4]:rectangle {["center"]={0,2.25},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-image-rect-4",["layer"]=10,["size"]={2.5,0.6},["stroke"]="#222222",["width"]=1.4}
refs[6] = refs[4]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-5",["layer"]=40,["point"]={0,2.25},["role"]="text",["size"]=23,["text"]="loader->sync()"}
refs[7] = refs[4]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-image-arrow-6",["layer"]=8,["points"]={{0,2.87},{0,2.56}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[8] = scene:group {["id"]="update-image-group-7"}
refs[9] = scene:group {["id"]="update-image-group-8"}
refs[10] = refs[8]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-image-arrow-9",["layer"]=8,["points"]={{-1.26,2.25},{-4.25,2.25},{-4.25,1.61}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[11] = refs[9]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-image-arrow-10",["layer"]=8,["points"]={{1.26,2.25},{4.3,2.25},{4.3,1.64}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[12] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-11",["layer"]=40,["point"]={-2.92,2.63},["role"]="text",["size"]=24,["text"]="Bitmap"}
refs[13] = refs[9]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-12",["layer"]=40,["point"]={2.85,2.63},["role"]="text",["size"]=24,["text"]="Vector"}
refs[14] = scene:group {["id"]="update-image-group-13"}
refs[15] = scene:group {["id"]="update-image-group-14"}
refs[16] = refs[14]:rectangle {["center"]={-4.76,1.21},["corner"]=0,["fill"]="#e66121",["id"]="update-image-rect-15",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[17] = refs[15]:rectangle {["center"]={-4.76,1.21},["corner"]=0,["fill"]="#e66121",["id"]="update-image-rect-16",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[18] = refs[14]:rectangle {["center"]={-3.94,1.21},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-image-rect-17",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[19] = refs[15]:rectangle {["center"]={-3.94,1.21},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-image-rect-18",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[20] = refs[14]:rectangle {["center"]={-4.76,0.39},["corner"]=0,["fill"]="#c08040",["id"]="update-image-rect-19",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[21] = refs[15]:rectangle {["center"]={-4.76,0.39},["corner"]=0,["fill"]="#604020",["id"]="update-image-rect-20",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[22] = refs[14]:rectangle {["center"]={-3.94,0.39},["corner"]=0,["fill"]="#eeeeee",["id"]="update-image-rect-21",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[23] = refs[15]:rectangle {["center"]={-3.94,0.39},["corner"]=0,["fill"]="#eeeeee",["id"]="update-image-rect-22",["layer"]=10,["size"]={0.8,0.8},["stroke"]="#f7f7f7",["width"]=1.5}
refs[24] = scene:group {["id"]="update-image-group-23"}
refs[25] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-24",["layer"]=40,["point"]={-4.3,-0.34},["role"]="text",["size"]=22,["text"]="2 × 2 · data · stride"}
refs[26] = scene:group {["id"]="update-image-group-25"}
refs[27] = refs[26]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-26",["layer"]=40,["point"]={-4.3,-0.85},["role"]="text",["size"]=22,["text"]="CS + premultiply"}
refs[28] = scene:group {["id"]="update-image-group-27"}
refs[29] = refs[28]:rectangle {["center"]={4.3,0.78},["corner"]=0,["fill"]="#00000000",["id"]="update-image-rect-28",["layer"]=10,["size"]={3,1.67},["stroke"]="#222222",["width"]=1.4}
refs[30] = refs[28]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-29",["layer"]=40,["point"]={4.3,1.31},["role"]="text",["size"]=23,["text"]="Scene"}
refs[31] = refs[28]:polygon {["fill"]="#e66121",["id"]="update-image-polygon-30",["layer"]=15,["points"]={{3.5879999999999996,0.9063999999999999},{3.3864,0.4095999999999998},{3.9407999999999994,0.4095999999999998}},["stroke"]="#e66121",["width"]=2}
refs[32] = refs[28]:rectangle {["center"]={4.94,0.64},["corner"]=0.09359999999999999,["fill"]="#1f6bc4",["id"]="update-image-rect-31",["layer"]=15,["size"]={0.5256,0.46799999999999997},["stroke"]="#1f6bc4",["width"]=1}
refs[33] = refs[28]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-32",["layer"]=40,["point"]={4.3,-0.34},["role"]="text",["size"]=22,["text"]="Paint::update() × children"}
refs[34] = scene:group {["id"]="update-image-group-33"}
refs[35] = refs[34]:rectangle {["center"]={0,1.03},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-image-rect-34",["layer"]=10,["size"]={3.26,0.65},["stroke"]="#222222",["width"]=1.4}
refs[36] = refs[34]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-35",["layer"]=40,["point"]={0,1.03},["role"]="text",["size"]=24,["text"]="SwImageTask::run()"}
refs[37] = refs[34]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-image-arrow-36",["layer"]=8,["points"]={{-3.52,0.82},{-1.65,0.82}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[38] = refs[34]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-37",["layer"]=40,["point"]={-2.49,1.24},["role"]="text",["size"]=21,["text"]="surface + M"}
refs[39] = scene:group {["id"]="update-image-group-38"}
refs[40] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-39",["layer"]=40,["point"]={-0.04,0.06},["role"]="text",["size"]=23,["text"]="imagePrepare()"}
refs[41] = refs[39]:rectangle {["center"]={-0.57,-1.89},["corner"]=0,["fill"]="#00000000",["id"]="update-image-rect-40",["layer"]=10,["size"]={3.12,3.12},["stroke"]="#dedede",["width"]=1}
refs[42] = scene:group {["id"]="update-image-group-41"}
refs[43] = refs[42]:polygon {["fill"]="#00000000",["id"]="update-image-polygon-42",["layer"]=15,["points"]={{-2.13,-0.33},{-1.87,-0.33},{-1.87,-0.59},{-2.13,-0.59}},["stroke"]="#222222",["width"]=3}
refs[44] = scene:group {["id"]="update-image-group-43"}
refs[45] = refs[44]:polygon {["fill"]="#00000000",["id"]="update-image-polygon-44",["layer"]=15,["points"]={{-0.96,-0.72},{0.6,-1.24},{0.08,-2.8},{-1.48,-2.28}},["stroke"]="#222222",["width"]=3}
refs[46] = refs[44]:rectangle {["center"]={-0.96,-0.72},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-45",["layer"]=10,["size"]={0.08,0.08},["stroke"]="#222222",["width"]=1.4}
refs[47] = refs[44]:rectangle {["center"]={0.6,-1.24},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-46",["layer"]=10,["size"]={0.08,0.08},["stroke"]="#222222",["width"]=1.4}
refs[48] = refs[44]:rectangle {["center"]={0.08,-2.8},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-47",["layer"]=10,["size"]={0.08,0.08},["stroke"]="#222222",["width"]=1.4}
refs[49] = refs[44]:rectangle {["center"]={-1.48,-2.28},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-48",["layer"]=10,["size"]={0.08,0.08},["stroke"]="#222222",["width"]=1.4}
refs[50] = scene:group {["id"]="update-image-group-49"}
refs[51] = refs[50]:rectangle {["center"]={-0.83,-0.785},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-50",["layer"]=14,["size"]={0.516,0.124},["stroke"]="#00000000",["width"]=0}
refs[52] = refs[50]:rectangle {["center"]={-0.635,-0.915},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-51",["layer"]=14,["size"]={0.9059999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[53] = refs[50]:rectangle {["center"]={-0.44,-1.045},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-52",["layer"]=14,["size"]={1.296,0.124},["stroke"]="#00000000",["width"]=0}
refs[54] = refs[50]:rectangle {["center"]={-0.31,-1.175},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-53",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[55] = refs[50]:rectangle {["center"]={-0.31,-1.305},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-54",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[56] = refs[50]:rectangle {["center"]={-0.31,-1.435},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-55",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[57] = refs[50]:rectangle {["center"]={-0.375,-1.565},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-56",["layer"]=14,["size"]={1.946,0.124},["stroke"]="#00000000",["width"]=0}
refs[58] = refs[50]:rectangle {["center"]={-0.44,-1.695},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-57",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[59] = refs[50]:rectangle {["center"]={-0.44,-1.825},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-58",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[60] = refs[50]:rectangle {["center"]={-0.505,-1.955},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-59",["layer"]=14,["size"]={1.946,0.124},["stroke"]="#00000000",["width"]=0}
refs[61] = refs[50]:rectangle {["center"]={-0.57,-2.085},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-60",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[62] = refs[50]:rectangle {["center"]={-0.57,-2.215},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-61",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[63] = refs[50]:rectangle {["center"]={-0.57,-2.345},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-62",["layer"]=14,["size"]={1.8159999999999998,0.124},["stroke"]="#00000000",["width"]=0}
refs[64] = refs[50]:rectangle {["center"]={-0.44,-2.475},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-63",["layer"]=14,["size"]={1.296,0.124},["stroke"]="#00000000",["width"]=0}
refs[65] = refs[50]:rectangle {["center"]={-0.245,-2.605},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-64",["layer"]=14,["size"]={0.9059999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[66] = refs[50]:rectangle {["center"]={-0.05,-2.735},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-65",["layer"]=14,["size"]={0.516,0.124},["stroke"]="#00000000",["width"]=0}
refs[67] = scene:group {["id"]="update-image-group-66"}
refs[68] = refs[67]:rectangle {["center"]={-0.44,-1.76},["corner"]=0,["fill"]="#00000000",["id"]="update-image-rect-67",["layer"]=20,["size"]={2.08,2.08},["stroke"]="#1f6bc4",["width"]=2}
refs[69] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-image-text-68",["layer"]=40,["point"]={1.55,-1.78},["role"]="text",["size"]=21,["text"]="renderBox"}
refs[70] = scene:group {["id"]="update-image-group-69"}
refs[71] = refs[70]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-70",["layer"]=40,["point"]={0.01,-3.87},["role"]="text",["size"]=22,["text"]="M × [0, w] × [0, h]"}
refs[72] = scene:group {["id"]="update-image-group-71"}
refs[73] = refs[72]:rectangle {["center"]={4.18,-2.42},["corner"]=0,["fill"]="#00000000",["id"]="update-image-rect-72",["layer"]=10,["size"]={3.16,2.64},["stroke"]="#222222",["width"]=1.4}
refs[74] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-73",["layer"]=40,["point"]={4.18,-1.42},["role"]="text",["size"]=25,["text"]="SwImage"}
refs[75] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-74",["layer"]=40,["point"]={4.18,-1.86},["role"]="text",["size"]=21,["text"]="data · w · h · stride"}
refs[76] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-75",["layer"]=40,["point"]={4.18,-2.31},["role"]="text",["size"]=22,["text"]="direct = false"}
refs[77] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-76",["layer"]=40,["point"]={4.18,-2.74},["role"]="text",["size"]=22,["text"]="scaled = false"}
refs[78] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-77",["layer"]=40,["point"]={4.18,-3.22},["role"]="text",["size"]=21,["text"]="transform + renderBox"}
refs[79] = scene:group {["id"]="update-image-group-78"}
refs[80] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-79",["layer"]=40,["point"]={-4.3,-1.5},["role"]="text",["size"]=22,["text"]="clips → imageGenRle()"}
refs[81] = refs[79]:polygon {["fill"]="#00000000",["id"]="update-image-polygon-80",["layer"]=22,["points"]={{-4.85,-2.15},{-3.85,-2.45},{-4.55,-3.25}},["stroke"]="#222222",["width"]=2}
refs[82] = refs[79]:rectangle {["center"]={-4.8,-2.2},["corner"]=0,["fill"]="#999999",["id"]="update-image-rect-81",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[83] = refs[79]:rectangle {["center"]={-4.7,-2.2},["corner"]=0,["fill"]="#afafaf",["id"]="update-image-rect-82",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[84] = refs[79]:rectangle {["center"]={-4.6,-2.2},["corner"]=0,["fill"]="#d6d6d6",["id"]="update-image-rect-83",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[85] = refs[79]:rectangle {["center"]={-4.5,-2.2},["corner"]=0,["fill"]="#f4f4f4",["id"]="update-image-rect-84",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[86] = refs[79]:rectangle {["center"]={-4.8,-2.3},["corner"]=0,["fill"]="#aaaaaa",["id"]="update-image-rect-85",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[87] = refs[79]:rectangle {["center"]={-4.65,-2.3},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-86",["layer"]=14,["size"]={0.196,0.094},["stroke"]="#00000000",["width"]=0}
refs[88] = refs[79]:rectangle {["center"]={-4.5,-2.3},["corner"]=0,["fill"]="#7d7d7d",["id"]="update-image-rect-87",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[89] = refs[79]:rectangle {["center"]={-4.4,-2.3},["corner"]=0,["fill"]="#a2a2a2",["id"]="update-image-rect-88",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[90] = refs[79]:rectangle {["center"]={-4.3,-2.3},["corner"]=0,["fill"]="#c9c9c9",["id"]="update-image-rect-89",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[91] = refs[79]:rectangle {["center"]={-4.2,-2.3},["corner"]=0,["fill"]="#eeeeee",["id"]="update-image-rect-90",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[92] = refs[79]:rectangle {["center"]={-4.8,-2.4},["corner"]=0,["fill"]="#cdcdcd",["id"]="update-image-rect-91",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[93] = refs[79]:rectangle {["center"]={-4.5,-2.4},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-92",["layer"]=14,["size"]={0.496,0.094},["stroke"]="#00000000",["width"]=0}
refs[94] = refs[79]:rectangle {["center"]={-4.2,-2.4},["corner"]=0,["fill"]="#777777",["id"]="update-image-rect-93",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[95] = refs[79]:rectangle {["center"]={-4.1,-2.4},["corner"]=0,["fill"]="#959595",["id"]="update-image-rect-94",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[96] = refs[79]:rectangle {["center"]={-4,-2.4},["corner"]=0,["fill"]="#bcbcbc",["id"]="update-image-rect-95",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[97] = refs[79]:rectangle {["center"]={-3.9,-2.4},["corner"]=0,["fill"]="#e3e3e3",["id"]="update-image-rect-96",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[98] = refs[79]:rectangle {["center"]={-4.8,-2.5},["corner"]=0,["fill"]="#efefef",["id"]="update-image-rect-97",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[99] = refs[79]:rectangle {["center"]={-4.7,-2.5},["corner"]=0,["fill"]="#767676",["id"]="update-image-rect-98",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[100] = refs[79]:rectangle {["center"]={-4.3,-2.5},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-99",["layer"]=14,["size"]={0.696,0.094},["stroke"]="#00000000",["width"]=0}
refs[101] = refs[79]:rectangle {["center"]={-3.9,-2.5},["corner"]=0,["fill"]="#aeaeae",["id"]="update-image-rect-100",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[102] = refs[79]:rectangle {["center"]={-4.7,-2.6},["corner"]=0,["fill"]="#929292",["id"]="update-image-rect-101",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[103] = refs[79]:rectangle {["center"]={-4.35,-2.6},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-102",["layer"]=14,["size"]={0.596,0.094},["stroke"]="#00000000",["width"]=0}
refs[104] = refs[79]:rectangle {["center"]={-4,-2.6},["corner"]=0,["fill"]="#9e9e9e",["id"]="update-image-rect-103",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[105] = refs[79]:rectangle {["center"]={-3.9,-2.6},["corner"]=0,["fill"]="#f5f5f5",["id"]="update-image-rect-104",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[106] = refs[79]:rectangle {["center"]={-4.7,-2.7},["corner"]=0,["fill"]="#b5b5b5",["id"]="update-image-rect-105",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[107] = refs[79]:rectangle {["center"]={-4.4,-2.7},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-106",["layer"]=14,["size"]={0.496,0.094},["stroke"]="#00000000",["width"]=0}
refs[108] = refs[79]:rectangle {["center"]={-4.1,-2.7},["corner"]=0,["fill"]="#929292",["id"]="update-image-rect-107",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[109] = refs[79]:rectangle {["center"]={-4,-2.7},["corner"]=0,["fill"]="#f2f2f2",["id"]="update-image-rect-108",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[110] = refs[79]:rectangle {["center"]={-4.7,-2.8},["corner"]=0,["fill"]="#d9d9d9",["id"]="update-image-rect-109",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[111] = refs[79]:rectangle {["center"]={-4.45,-2.8},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-110",["layer"]=14,["size"]={0.396,0.094},["stroke"]="#00000000",["width"]=0}
refs[112] = refs[79]:rectangle {["center"]={-4.2,-2.8},["corner"]=0,["fill"]="#878787",["id"]="update-image-rect-111",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[113] = refs[79]:rectangle {["center"]={-4.1,-2.8},["corner"]=0,["fill"]="#ececec",["id"]="update-image-rect-112",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[114] = refs[79]:rectangle {["center"]={-4.7,-2.9},["corner"]=0,["fill"]="#f5f5f5",["id"]="update-image-rect-113",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[115] = refs[79]:rectangle {["center"]={-4.6,-2.9},["corner"]=0,["fill"]="#7c7c7c",["id"]="update-image-rect-114",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[116] = refs[79]:rectangle {["center"]={-4.45,-2.9},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-115",["layer"]=14,["size"]={0.196,0.094},["stroke"]="#00000000",["width"]=0}
refs[117] = refs[79]:rectangle {["center"]={-4.3,-2.9},["corner"]=0,["fill"]="#7f7f7f",["id"]="update-image-rect-116",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[118] = refs[79]:rectangle {["center"]={-4.2,-2.9},["corner"]=0,["fill"]="#e4e4e4",["id"]="update-image-rect-117",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[119] = refs[79]:rectangle {["center"]={-4.6,-3},["corner"]=0,["fill"]="#9e9e9e",["id"]="update-image-rect-118",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[120] = refs[79]:rectangle {["center"]={-4.5,-3},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-119",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[121] = refs[79]:rectangle {["center"]={-4.4,-3},["corner"]=0,["fill"]="#797979",["id"]="update-image-rect-120",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[122] = refs[79]:rectangle {["center"]={-4.3,-3},["corner"]=0,["fill"]="#dadada",["id"]="update-image-rect-121",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[123] = refs[79]:rectangle {["center"]={-4.6,-3.1},["corner"]=0,["fill"]="#c1c1c1",["id"]="update-image-rect-122",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[124] = refs[79]:rectangle {["center"]={-4.5,-3.1},["corner"]=0,["fill"]="#767676",["id"]="update-image-rect-123",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[125] = refs[79]:rectangle {["center"]={-4.4,-3.1},["corner"]=0,["fill"]="#cdcdcd",["id"]="update-image-rect-124",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[126] = refs[79]:rectangle {["center"]={-4.6,-3.2},["corner"]=0,["fill"]="#e5e5e5",["id"]="update-image-rect-125",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[127] = refs[79]:rectangle {["center"]={-4.5,-3.2},["corner"]=0,["fill"]="#bebebe",["id"]="update-image-rect-126",["layer"]=14,["size"]={0.096,0.094},["stroke"]="#00000000",["width"]=0}
refs[128] = scene:group {["id"]="update-image-group-127"}
refs[129] = refs[128]:rectangle {["center"]={-1.025,-1.305},["corner"]=0,["fill"]="#999999",["id"]="update-image-rect-128",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[130] = refs[128]:rectangle {["center"]={-0.895,-1.305},["corner"]=0,["fill"]="#afafaf",["id"]="update-image-rect-129",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[131] = refs[128]:rectangle {["center"]={-0.765,-1.305},["corner"]=0,["fill"]="#d6d6d6",["id"]="update-image-rect-130",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[132] = refs[128]:rectangle {["center"]={-0.635,-1.305},["corner"]=0,["fill"]="#f4f4f4",["id"]="update-image-rect-131",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[133] = refs[128]:rectangle {["center"]={-1.025,-1.435},["corner"]=0,["fill"]="#aaaaaa",["id"]="update-image-rect-132",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[134] = refs[128]:rectangle {["center"]={-0.83,-1.435},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-133",["layer"]=14,["size"]={0.256,0.124},["stroke"]="#00000000",["width"]=0}
refs[135] = refs[128]:rectangle {["center"]={-0.635,-1.435},["corner"]=0,["fill"]="#7d7d7d",["id"]="update-image-rect-134",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[136] = refs[128]:rectangle {["center"]={-0.505,-1.435},["corner"]=0,["fill"]="#a2a2a2",["id"]="update-image-rect-135",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[137] = refs[128]:rectangle {["center"]={-0.375,-1.435},["corner"]=0,["fill"]="#c9c9c9",["id"]="update-image-rect-136",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[138] = refs[128]:rectangle {["center"]={-0.245,-1.435},["corner"]=0,["fill"]="#eeeeee",["id"]="update-image-rect-137",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[139] = refs[128]:rectangle {["center"]={-1.025,-1.565},["corner"]=0,["fill"]="#cdcdcd",["id"]="update-image-rect-138",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[140] = refs[128]:rectangle {["center"]={-0.635,-1.565},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-139",["layer"]=14,["size"]={0.6459999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[141] = refs[128]:rectangle {["center"]={-0.245,-1.565},["corner"]=0,["fill"]="#777777",["id"]="update-image-rect-140",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[142] = refs[128]:rectangle {["center"]={-0.115,-1.565},["corner"]=0,["fill"]="#959595",["id"]="update-image-rect-141",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[143] = refs[128]:rectangle {["center"]={0.015,-1.565},["corner"]=0,["fill"]="#bcbcbc",["id"]="update-image-rect-142",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[144] = refs[128]:rectangle {["center"]={0.145,-1.565},["corner"]=0,["fill"]="#e3e3e3",["id"]="update-image-rect-143",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[145] = refs[128]:rectangle {["center"]={-1.025,-1.695},["corner"]=0,["fill"]="#efefef",["id"]="update-image-rect-144",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[146] = refs[128]:rectangle {["center"]={-0.895,-1.695},["corner"]=0,["fill"]="#767676",["id"]="update-image-rect-145",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[147] = refs[128]:rectangle {["center"]={-0.375,-1.695},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-146",["layer"]=14,["size"]={0.9059999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[148] = refs[128]:rectangle {["center"]={0.145,-1.695},["corner"]=0,["fill"]="#aeaeae",["id"]="update-image-rect-147",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[149] = refs[128]:rectangle {["center"]={-0.895,-1.825},["corner"]=0,["fill"]="#929292",["id"]="update-image-rect-148",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[150] = refs[128]:rectangle {["center"]={-0.44,-1.825},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-149",["layer"]=14,["size"]={0.7759999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[151] = refs[128]:rectangle {["center"]={0.015,-1.825},["corner"]=0,["fill"]="#9e9e9e",["id"]="update-image-rect-150",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[152] = refs[128]:rectangle {["center"]={0.145,-1.825},["corner"]=0,["fill"]="#f5f5f5",["id"]="update-image-rect-151",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[153] = refs[128]:rectangle {["center"]={-0.895,-1.955},["corner"]=0,["fill"]="#b5b5b5",["id"]="update-image-rect-152",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[154] = refs[128]:rectangle {["center"]={-0.505,-1.955},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-153",["layer"]=14,["size"]={0.6459999999999999,0.124},["stroke"]="#00000000",["width"]=0}
refs[155] = refs[128]:rectangle {["center"]={-0.115,-1.955},["corner"]=0,["fill"]="#929292",["id"]="update-image-rect-154",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[156] = refs[128]:rectangle {["center"]={0.015,-1.955},["corner"]=0,["fill"]="#f2f2f2",["id"]="update-image-rect-155",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[157] = refs[128]:rectangle {["center"]={-0.895,-2.085},["corner"]=0,["fill"]="#d9d9d9",["id"]="update-image-rect-156",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[158] = refs[128]:rectangle {["center"]={-0.57,-2.085},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-157",["layer"]=14,["size"]={0.516,0.124},["stroke"]="#00000000",["width"]=0}
refs[159] = refs[128]:rectangle {["center"]={-0.245,-2.085},["corner"]=0,["fill"]="#878787",["id"]="update-image-rect-158",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[160] = refs[128]:rectangle {["center"]={-0.115,-2.085},["corner"]=0,["fill"]="#ececec",["id"]="update-image-rect-159",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[161] = refs[128]:rectangle {["center"]={-0.895,-2.215},["corner"]=0,["fill"]="#f5f5f5",["id"]="update-image-rect-160",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[162] = refs[128]:rectangle {["center"]={-0.765,-2.215},["corner"]=0,["fill"]="#7c7c7c",["id"]="update-image-rect-161",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[163] = refs[128]:rectangle {["center"]={-0.57,-2.215},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-162",["layer"]=14,["size"]={0.256,0.124},["stroke"]="#00000000",["width"]=0}
refs[164] = refs[128]:rectangle {["center"]={-0.375,-2.215},["corner"]=0,["fill"]="#7f7f7f",["id"]="update-image-rect-163",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[165] = refs[128]:rectangle {["center"]={-0.245,-2.215},["corner"]=0,["fill"]="#e4e4e4",["id"]="update-image-rect-164",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[166] = refs[128]:rectangle {["center"]={-0.765,-2.345},["corner"]=0,["fill"]="#9e9e9e",["id"]="update-image-rect-165",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[167] = refs[128]:rectangle {["center"]={-0.635,-2.345},["corner"]=0,["fill"]="#757575",["id"]="update-image-rect-166",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[168] = refs[128]:rectangle {["center"]={-0.505,-2.345},["corner"]=0,["fill"]="#797979",["id"]="update-image-rect-167",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[169] = refs[128]:rectangle {["center"]={-0.375,-2.345},["corner"]=0,["fill"]="#dadada",["id"]="update-image-rect-168",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[170] = refs[128]:rectangle {["center"]={-0.765,-2.475},["corner"]=0,["fill"]="#c1c1c1",["id"]="update-image-rect-169",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[171] = refs[128]:rectangle {["center"]={-0.635,-2.475},["corner"]=0,["fill"]="#767676",["id"]="update-image-rect-170",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[172] = refs[128]:rectangle {["center"]={-0.505,-2.475},["corner"]=0,["fill"]="#cdcdcd",["id"]="update-image-rect-171",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[173] = refs[128]:rectangle {["center"]={-0.635,-2.605},["corner"]=0,["fill"]="#bebebe",["id"]="update-image-rect-172",["layer"]=14,["size"]={0.126,0.124},["stroke"]="#00000000",["width"]=0}
refs[174] = scene:group {["id"]="update-image-group-173"}
refs[175] = refs[174]:polygon {["fill"]="#00000000",["id"]="update-image-polygon-174",["layer"]=25,["points"]={{-1.09,-1.24},{0.21,-1.63},{-0.7,-2.67}},["stroke"]="#222222",["width"]=2.5}
refs[176] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-175",["layer"]=40,["point"]={-4.3,-3.76},["role"]="text",["size"]=21,["text"]="image.rle & clip RLE"}
refs[177] = scene:group {["id"]="update-image-group-176"}
refs[178] = refs[177]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-image-text-177",["layer"]=40,["point"]={4.18,-4.13},["role"]="text",["size"]=23,["text"]="Prepared → Draw/Raster"}
scene:wait(0.7)
scene:fade_in(refs[4],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:create(refs[8],0.6,"linear",0)
scene:fade_in(refs[14],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[24],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:create(refs[9],0.6,"linear",0)
scene:fade_in(refs[28],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_in(refs[34],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[14],0,0.4,"linear")
scene:fade_in(refs[15],{["duration"]=0.4,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[26],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_in(refs[39],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[42],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[70],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[42],0,0.2,"linear")
refs[179] = scene:group {["id"]="update-image-group-178"}
refs[180] = refs[179]:rectangle {["center"]={-2.13,-0.33},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-179",["layer"]=10,["size"]={0.09,0.09},["stroke"]="#222222",["width"]=1.4}
refs[181] = refs[179]:rectangle {["center"]={-1.87,-0.33},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-180",["layer"]=10,["size"]={0.09,0.09},["stroke"]="#222222",["width"]=1.4}
refs[182] = refs[179]:rectangle {["center"]={-1.87,-0.59},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-181",["layer"]=10,["size"]={0.09,0.09},["stroke"]="#222222",["width"]=1.4}
refs[183] = refs[179]:rectangle {["center"]={-2.13,-0.59},["corner"]=0,["fill"]="#222222",["id"]="update-image-rect-182",["layer"]=10,["size"]={0.09,0.09},["stroke"]="#222222",["width"]=1.4}
scene:fade_in(refs[179],{["duration"]=0.15,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[180],shift={1.17,-0.39}},{target=refs[181],shift={2.47,-0.91}},{target=refs[182],shift={1.95,-2.21}},{target=refs[183],shift={0.65,-1.69}}},1.2,"ease_in_out",0)
scene:create(refs[44],0.7,"linear",0)
scene:fade(refs[179],0,0.1,"linear")
scene:wait(1.1)
scene:fade_in(refs[67],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[72],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_in(refs[79],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[50],{["duration"]=0.12,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[51],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[52],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[53],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[54],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[55],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[56],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[57],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[58],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[59],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[60],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[61],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[62],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[63],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[64],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[65],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[66],{["duration"]=0.055,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[174],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[44],opacity=0.3}},0.3,"ease_in_out",0)
scene:fade_in(refs[128],{["duration"]=0.1,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[51],0,0.04,"linear")
scene:fade(refs[52],0,0.04,"linear")
scene:fade(refs[53],0,0.04,"linear")
scene:fade(refs[54],0,0.04,"linear")
scene:fade(refs[55],0,0.04,"linear")
scene:fade_in(refs[129],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[130],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[131],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[132],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[56],0,0.04,"linear")
scene:fade_in(refs[133],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[134],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[135],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[136],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[137],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[138],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[57],0,0.04,"linear")
scene:fade_in(refs[139],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[140],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[141],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[142],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[143],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[144],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[58],0,0.04,"linear")
scene:fade_in(refs[145],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[146],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[147],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[148],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[59],0,0.04,"linear")
scene:fade_in(refs[149],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[150],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[151],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[152],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[60],0,0.04,"linear")
scene:fade_in(refs[153],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[154],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[155],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[156],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[61],0,0.04,"linear")
scene:fade_in(refs[157],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[158],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[159],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[160],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[62],0,0.04,"linear")
scene:fade_in(refs[161],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[162],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[163],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[164],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[165],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[63],0,0.04,"linear")
scene:fade_in(refs[166],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[167],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[168],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[169],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[64],0,0.04,"linear")
scene:fade_in(refs[170],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[171],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[172],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[65],0,0.04,"linear")
scene:fade_in(refs[173],{["duration"]=0.025,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade(refs[66],0,0.04,"linear")
scene:fade_in(refs[177],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(2.4)
return scene
