-- Generated by scripts/render-update-scenes.mjs; edit prepare.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=9,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=900,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#222222",["font"]="Pretendard"},["h1"]={["color"]="#222222",["font"]="Pretendard"},["h2"]={["color"]="#222222",["font"]="Pretendard"},["h3"]={["color"]="#222222",["font"]="Pretendard"},["text"]={["color"]="#222222",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-0",["layer"]=40,["point"]={0,3.8},["role"]="text",["size"]=30,["text"]="Update A"}
refs[2] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-1",["layer"]=40,["point"]={-2.4,2.8},["role"]="text",["size"]=22,["text"]="Paint"}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-2",["layer"]=40,["point"]={0.1,2.8},["role"]="text",["size"]=22,["text"]="Flags"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-3",["layer"]=40,["point"]={4,2.8},["role"]="text",["size"]=22,["text"]="RenderData"}
refs[5] = scene:rectangle {["center"]={-5,0.1},["corner"]=0,["fill"]="#222222",["id"]="update-invalidation-rect-4",["layer"]=10,["size"]={1.7,0.64},["stroke"]="#222222",["width"]=1.4}
refs[6] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-invalidation-text-5",["layer"]=40,["point"]={-5,0.1},["role"]="text",["size"]=24,["text"]="Scene"}
refs[7] = scene:route {["fill"]="#00000000",["id"]="update-invalidation-route-6",["layer"]=8,["points"]={{-4.15,0.1},{-3.6,0.1}},["stroke"]="#222222",["tail"]=0,["tip"]=0,["width"]=1.6}
refs[8] = scene:group {["id"]="update-invalidation-group-7"}
refs[9] = scene:group {["id"]="update-invalidation-group-8"}
refs[10] = scene:group {["id"]="update-invalidation-group-9"}
refs[11] = scene:group {["id"]="update-invalidation-group-10"}
refs[12] = scene:group {["id"]="update-invalidation-group-11"}
refs[13] = scene:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-12",["layer"]=8,["points"]={{-3.6,0.1},{-3.6,1.6},{-3.2,1.6}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[14] = scene:group {["id"]="update-invalidation-group-13"}
refs[15] = refs[14]:polygon {["fill"]="#e66121",["id"]="update-invalidation-polygon-14",["layer"]=15,["points"]={{-2.5,1.97},{-2.78,1.28},{-2.01,1.28}},["stroke"]="#e66121",["width"]=2}
refs[16] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-15",["layer"]=40,["point"]={-2.4,0.7},["role"]="text",["size"]=24,["text"]="A"}
refs[17] = refs[8]:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-16",["layer"]=8,["points"]={{-1.8,1.6},{-1.05,1.6}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[18] = refs[8]:rectangle {["center"]={0.1,1.6},["corner"]=0,["fill"]="#ffffff",["id"]="update-invalidation-rect-17",["layer"]=10,["size"]={2.2,0.8},["stroke"]="#e66121",["width"]=1.4}
refs[19] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-18",["layer"]=40,["point"]={0.1,1.6},["role"]="text",["size"]=22,["text"]="Transform"}
refs[20] = refs[9]:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-19",["layer"]=8,["points"]={{1.3,1.6},{2.85,1.6}},["stroke"]="#e66121",["tip"]=9,["width"]=1.7}
refs[21] = refs[9]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-20",["layer"]=40,["point"]={2.06,1.92},["role"]="text",["size"]=21,["text"]="update"}
refs[22] = scene:rectangle {["center"]={4,1.6},["corner"]=0,["fill"]="#ffffff",["id"]="update-invalidation-rect-21",["layer"]=10,["size"]={2.1,1.4},["stroke"]="#222222",["width"]=1.4}
refs[23] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-22",["layer"]=40,["point"]={4,0.6},["role"]="text",["size"]=22,["text"]="A · rd"}
refs[24] = scene:group {["id"]="update-invalidation-group-23"}
refs[25] = refs[24]:rectangle {["center"]={4,1.96},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-24",["layer"]=10,["size"]={0.4,0.12},["stroke"]="#00000000",["width"]=0}
refs[26] = refs[24]:rectangle {["center"]={4,1.72},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-25",["layer"]=10,["size"]={0.7,0.12},["stroke"]="#00000000",["width"]=0}
refs[27] = refs[24]:rectangle {["center"]={4,1.48},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-26",["layer"]=10,["size"]={1,0.12},["stroke"]="#00000000",["width"]=0}
refs[28] = refs[24]:rectangle {["center"]={4,1.24},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-27",["layer"]=10,["size"]={1.3,0.12},["stroke"]="#00000000",["width"]=0}
refs[29] = scene:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-28",["layer"]=8,["points"]={{-3.6,0.1},{-3.6,-1.4},{-3.2,-1.4}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[30] = scene:group {["id"]="update-invalidation-group-29"}
refs[31] = refs[30]:rectangle {["center"]={-2.4,-1.4},["corner"]=0.13,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-30",["layer"]=15,["size"]={0.73,0.65},["stroke"]="#1f6bc4",["width"]=1}
refs[32] = scene:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-31",["layer"]=40,["point"]={-2.4,-2.3},["role"]="text",["size"]=24,["text"]="B"}
refs[33] = refs[8]:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-32",["layer"]=8,["points"]={{-1.8,-1.4},{-1.05,-1.4}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[34] = refs[8]:rectangle {["center"]={0.1,-1.4},["corner"]=0,["fill"]="#ffffff",["id"]="update-invalidation-rect-33",["layer"]=10,["size"]={2.2,0.8},["stroke"]="#1f6bc4",["width"]=1.4}
refs[35] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-34",["layer"]=40,["point"]={0.1,-1.4},["role"]="text",["size"]=22,["text"]="None"}
refs[36] = refs[9]:route {["fill"]="#00000000",["id"]="update-invalidation-arrow-35",["layer"]=8,["points"]={{1.3,-1.4},{2.85,-1.4}},["stroke"]="#1f6bc4",["tip"]=9,["width"]=1.7}
refs[37] = refs[9]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-36",["layer"]=40,["point"]={2.06,-1.08},["role"]="text",["size"]=21,["text"]="reuse"}
refs[38] = scene:rectangle {["center"]={4,-1.4},["corner"]=0,["fill"]="#ffffff",["id"]="update-invalidation-rect-37",["layer"]=10,["size"]={2.1,1.4},["stroke"]="#222222",["width"]=1.4}
refs[39] = scene:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-38",["layer"]=40,["point"]={4,-2.4},["role"]="text",["size"]=22,["text"]="B · rd"}
refs[40] = scene:group {["id"]="update-invalidation-group-39"}
refs[41] = refs[40]:rectangle {["center"]={4,-1.04},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-40",["layer"]=10,["size"]={1.3,0.12},["stroke"]="#00000000",["width"]=0}
refs[42] = refs[40]:rectangle {["center"]={4,-1.28},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-41",["layer"]=10,["size"]={1.3,0.12},["stroke"]="#00000000",["width"]=0}
refs[43] = refs[40]:rectangle {["center"]={4,-1.52},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-42",["layer"]=10,["size"]={1.3,0.12},["stroke"]="#00000000",["width"]=0}
refs[44] = refs[40]:rectangle {["center"]={4,-1.76},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-43",["layer"]=10,["size"]={1.3,0.12},["stroke"]="#00000000",["width"]=0}
refs[45] = refs[11]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-44",["layer"]=40,["point"]={-2.4,0.4},["role"]="text",["size"]=21,["text"]="40°  ·  ×1.35"}
refs[46] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-45",["layer"]=40,["point"]={0,-3.3},["role"]="text",["size"]=23,["text"]="Ready"}
scene:wait(0.8)
scene:fade_in(refs[11],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[14],transform={1.0341599982106204,0.8677632730768281,0,-1.306437241217436,-0.8677632730768281,1.0341599982106204,0,-2.1372878525213803,0,0,1,0,0,0,0,1}}},1,"ease_in_out",0)
scene:fade_in(refs[8],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[9],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.2)
refs[47] = scene:group {["id"]="update-invalidation-group-46"}
refs[48] = refs[47]:rectangle {["center"]={4.0775548570702655,1.96},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-47",["layer"]=10,["size"]={0.25719854346924387,0.12},["stroke"]="#00000000",["width"]=0}
refs[49] = refs[47]:rectangle {["center"]={3.7973517487760704,1.72},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-48",["layer"]=10,["size"]={0.7715956304077315,0.12},["stroke"]="#00000000",["width"]=0}
refs[50] = refs[47]:rectangle {["center"]={3.8884281095198956,1.48},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-49",["layer"]=10,["size"]={0.5434337792701779,0.12},["stroke"]="#00000000",["width"]=0}
refs[51] = refs[47]:rectangle {["center"]={4.046568137785003,1.24},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-50",["layer"]=10,["size"]={0.18114459309005923,0.12},["stroke"]="#00000000",["width"]=0}
scene:fade(refs[24],0,0.2,"linear")
scene:fade_in(refs[47],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[12],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.5)
return scene
