-- Generated by scripts/render-update-scenes.mjs; edit prepare.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=9,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=900,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#222222",["font"]="Pretendard"},["h1"]={["color"]="#222222",["font"]="Pretendard"},["h2"]={["color"]="#222222",["font"]="Pretendard"},["h3"]={["color"]="#222222",["font"]="Pretendard"},["text"]={["color"]="#222222",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-0",["layer"]=40,["point"]={0,4.06},["role"]="text",["size"]=28,["text"]="a->translate(2, 1);  canvas->update();"}
refs[2] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-1",["layer"]=40,["point"]={-5,3.37},["role"]="text",["size"]=24,["text"]="Scene"}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-2",["layer"]=40,["point"]={-2.35,3.37},["role"]="text",["size"]=24,["text"]="Paint"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-3",["layer"]=40,["point"]={1.75,3.37},["role"]="text",["size"]=24,["text"]="RenderData"}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-4",["layer"]=40,["point"]={4.8,3.37},["role"]="text",["size"]=24,["text"]="Prepared"}
refs[6] = scene:group {["id"]="update-invalidation-group-5"}
refs[7] = refs[6]:rectangle {["center"]={-5,1.85},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-6",["layer"]=10,["size"]={1.7,0.66},["stroke"]="#222222",["width"]=1.4}
refs[8] = refs[6]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-7",["layer"]=40,["point"]={-5,1.85},["role"]="text",["size"]=24,["text"]="Scene"}
refs[9] = refs[6]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-8",["layer"]=8,["points"]={{-4.15,1.95},{-3.62,1.95},{-3.62,2.3},{-2.95,2.3}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[10] = refs[6]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-9",["layer"]=8,["points"]={{-4.15,1.75},{-3.62,1.75},{-3.62,0.2},{-2.95,0.2}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[11] = scene:group {["id"]="update-invalidation-group-10"}
refs[12] = scene:group {["id"]="update-invalidation-group-11"}
refs[13] = refs[11]:polygon {["fill"]="#e66121",["id"]="update-invalidation-polygon-12",["layer"]=15,["points"]={{-2.48,2.67},{-2.76,1.98},{-1.99,1.98}},["stroke"]="#e66121",["width"]=2}
refs[14] = refs[11]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-13",["layer"]=40,["point"]={-2.38,1.58},["role"]="text",["size"]=26,["text"]="A"}
refs[15] = refs[12]:rectangle {["center"]={-2.38,0.2},["corner"]=0.13,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-14",["layer"]=15,["size"]={0.73,0.65},["stroke"]="#1f6bc4",["width"]=1}
refs[16] = refs[12]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-15",["layer"]=40,["point"]={-2.38,-0.52},["role"]="text",["size"]=26,["text"]="B"}
refs[17] = scene:group {["id"]="update-invalidation-group-16"}
refs[18] = refs[17]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-17",["layer"]=40,["point"]={-4.89,0.63},["role"]="text",["size"]=21,["text"]="Mparent × Mlocal"}
refs[19] = refs[17]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-18",["layer"]=40,["point"]={-4.89,0.22},["role"]="text",["size"]=21,["text"]="opacity = 255"}
refs[20] = refs[17]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-19",["layer"]=40,["point"]={-4.89,-0.19},["role"]="text",["size"]=21,["text"]="clips = []"}
refs[21] = refs[17]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-20",["layer"]=40,["point"]={-4.89,-0.6},["role"]="text",["size"]=21,["text"]="parentFlag = None"}
refs[22] = scene:group {["id"]="update-invalidation-group-21"}
refs[23] = scene:group {["id"]="update-invalidation-group-22"}
refs[24] = refs[22]:rectangle {["center"]={-0.5,2.3},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-23",["layer"]=10,["size"]={1.75,0.6},["stroke"]="#e66121",["width"]=1.4}
refs[25] = refs[22]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-24",["layer"]=40,["point"]={-0.5,2.3},["role"]="text",["size"]=23,["text"]="Transform"}
refs[26] = refs[23]:rectangle {["center"]={-0.5,0.2},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-25",["layer"]=10,["size"]={1.75,0.6},["stroke"]="#757575",["width"]=1.4}
refs[27] = refs[23]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-26",["layer"]=40,["point"]={-0.5,0.2},["role"]="text",["size"]=23,["text"]="None"}
refs[28] = scene:group {["id"]="update-invalidation-group-27"}
refs[29] = refs[28]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-28",["layer"]=40,["point"]={-0.5,1.21},["role"]="text",["size"]=22,["text"]="parent | local"}
refs[30] = scene:group {["id"]="update-invalidation-group-29"}
refs[31] = scene:group {["id"]="update-invalidation-group-30"}
refs[32] = refs[30]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-31",["layer"]=8,["points"]={{0.38,2.3},{0.61,2.3}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[33] = refs[31]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-32",["layer"]=8,["points"]={{0.38,0.2},{3.44,0.2}},["stroke"]="#1f6bc4",["tip"]=9,["width"]=1.7}
refs[34] = refs[31]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-33",["layer"]=40,["point"]={1.75,0.63},["role"]="text",["size"]=22,["text"]="skip() · reuse rd"}
refs[35] = scene:group {["id"]="update-invalidation-group-34"}
refs[36] = refs[35]:rectangle {["center"]={1.98,2.3},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-35",["layer"]=10,["size"]={2.68,0.64},["stroke"]="#222222",["width"]=1.4}
refs[37] = refs[35]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-36",["layer"]=40,["point"]={1.98,2.3},["role"]="text",["size"]=23,["text"]="SwShapeTask · A"}
refs[38] = refs[35]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-37",["layer"]=40,["point"]={1.98,1.73},["role"]="text",["size"]=19,["text"]="transform · flags · opacity"}
refs[39] = scene:group {["id"]="update-invalidation-group-38"}
refs[40] = scene:group {["id"]="update-invalidation-group-39"}
refs[41] = refs[39]:rectangle {["center"]={4.79,2.23},["corner"]=0,["fill"]="#00000000",["id"]="update-invalidation-rect-40",["layer"]=10,["size"]={2.1,1.26},["stroke"]="#e66121",["width"]=1.4}
refs[42] = refs[40]:rectangle {["center"]={4.79,0.13},["corner"]=0,["fill"]="#00000000",["id"]="update-invalidation-rect-41",["layer"]=10,["size"]={2.1,1.26},["stroke"]="#1f6bc4",["width"]=1.4}
refs[43] = refs[39]:rectangle {["center"]={4.6,2.65},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-42",["layer"]=10,["size"]={0.25,0.11},["stroke"]="#00000000",["width"]=0}
refs[44] = refs[40]:rectangle {["center"]={4.79,0.55},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-43",["layer"]=10,["size"]={1.12,0.11},["stroke"]="#00000000",["width"]=0}
refs[45] = refs[39]:rectangle {["center"]={4.64,2.45},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-44",["layer"]=10,["size"]={0.48,0.11},["stroke"]="#00000000",["width"]=0}
refs[46] = refs[40]:rectangle {["center"]={4.79,0.35},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-45",["layer"]=10,["size"]={1.45,0.11},["stroke"]="#00000000",["width"]=0}
refs[47] = refs[39]:rectangle {["center"]={4.68,2.25},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-46",["layer"]=10,["size"]={0.71,0.11},["stroke"]="#00000000",["width"]=0}
refs[48] = refs[40]:rectangle {["center"]={4.79,0.15},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-47",["layer"]=10,["size"]={1.45,0.11},["stroke"]="#00000000",["width"]=0}
refs[49] = refs[39]:rectangle {["center"]={4.72,2.05},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-48",["layer"]=10,["size"]={0.94,0.11},["stroke"]="#00000000",["width"]=0}
refs[50] = refs[40]:rectangle {["center"]={4.79,-0.05},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-49",["layer"]=10,["size"]={1.45,0.11},["stroke"]="#00000000",["width"]=0}
refs[51] = refs[39]:rectangle {["center"]={4.76,1.85},["corner"]=0,["fill"]="#e66121",["id"]="update-invalidation-rect-50",["layer"]=10,["size"]={1.17,0.11},["stroke"]="#00000000",["width"]=0}
refs[52] = refs[40]:rectangle {["center"]={4.79,-0.25},["corner"]=0,["fill"]="#1f6bc4",["id"]="update-invalidation-rect-51",["layer"]=10,["size"]={1.12,0.11},["stroke"]="#00000000",["width"]=0}
refs[53] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-52",["layer"]=40,["point"]={4.79,1.26},["role"]="text",["size"]=22,["text"]="bounds + RLE"}
refs[54] = refs[40]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="update-invalidation-text-53",["layer"]=40,["point"]={4.79,-0.84},["role"]="text",["size"]=22,["text"]="same bounds + RLE"}
refs[55] = scene:group {["id"]="update-invalidation-group-54"}
refs[56] = refs[55]:route {["fill"]="#00000000",["id"]="update-invalidation-route-55",["layer"]=8,["points"]={{-5.8,-1.5},{5.8,-1.5}},["stroke"]="#dedede",["tail"]=0,["tip"]=0,["width"]=1.6}
refs[57] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-56",["layer"]=40,["point"]={-4.26,-1.9},["role"]="text",["size"]=23,["text"]="prepare()"}
refs[58] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-57",["layer"]=40,["point"]={-0.72,-1.9},["role"]="text",["size"]=23,["text"]="TaskScheduler::request()"}
refs[59] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-58",["layer"]=40,["point"]={3.4,-1.9},["role"]="text",["size"]=23,["text"]="SwShapeTask::run()"}
refs[60] = refs[55]:rectangle {["center"]={-4.25,-2.65},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-59",["layer"]=10,["size"]={2.7,0.7},["stroke"]="#222222",["width"]=1.4}
refs[61] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-60",["layer"]=40,["point"]={-4.25,-2.65},["role"]="text",["size"]=22,["text"]="previous · done()"}
refs[62] = refs[55]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-61",["layer"]=8,["points"]={{-2.89,-2.65},{-1.85,-2.65}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[63] = refs[55]:rectangle {["center"]={-0.56,-2.65},["corner"]=0,["fill"]="#00000000",["id"]="update-invalidation-rect-62",["layer"]=10,["size"]={2.5,0.9},["stroke"]="#222222",["width"]=1.4}
refs[64] = refs[55]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-63",["layer"]=8,["points"]={{0.7,-2.65},{1.63,-2.65}},["stroke"]="#222222",["tip"]=9,["width"]=1.7}
refs[65] = refs[55]:rectangle {["center"]={3.51,-2.65},["corner"]=0,["fill"]="#00000000",["id"]="update-invalidation-rect-64",["layer"]=10,["size"]={3.7,0.9},["stroke"]="#222222",["width"]=1.4}
refs[66] = scene:group {["id"]="update-invalidation-group-65"}
refs[67] = refs[66]:polygon {["fill"]="#e66121",["id"]="update-invalidation-polygon-66",["layer"]=15,["points"]={{-0.6279999999999996,-2.4353999999999996},{-0.7903999999999997,-2.8355999999999995},{-0.34379999999999994,-2.8355999999999995}},["stroke"]="#e66121",["width"]=2}
refs[68] = scene:group {["id"]="update-invalidation-group-67"}
refs[69] = refs[68]:route {["dash"]={6,5},["fill"]="#00000000",["id"]="update-invalidation-arrow-68",["layer"]=8,["points"]={{5.37,-2.64},{6.02,-2.64},{6.02,2.25},{5.84,2.25}},["stroke"]="#e66121",["tip"]=9,["width"]=1.7}
refs[70] = scene:group {["id"]="update-invalidation-group-69"}
refs[71] = refs[70]:rectangle {["center"]={3.31,-3.84},["corner"]=0,["fill"]="#f7f7f7",["id"]="update-invalidation-rect-70",["layer"]=10,["size"]={4.14,0.57},["stroke"]="#222222",["width"]=1.4}
refs[72] = refs[70]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="update-invalidation-text-71",["layer"]=40,["point"]={3.31,-3.84},["role"]="text",["size"]=22,["text"]="Draw → done(A) → consume"}
refs[73] = scene:group {["id"]="update-invalidation-group-72"}
refs[74] = refs[73]:text {["align"]={0.5,0.5},["fill"]="#757575",["font"]="Pretendard",["id"]="update-invalidation-text-73",["layer"]=40,["point"]={-3.63,-3.79},["role"]="text",["size"]=22,["text"]="postUpdate() → return"}
refs[75] = scene:group {["id"]="update-invalidation-group-74"}
refs[76] = refs[75]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-invalidation-text-75",["layer"]=40,["point"]={-2.36,1.09},["role"]="text",["size"]=22,["text"]="Transform"}
scene:wait(0.8)
scene:fade_in(refs[75],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[11],shift={0.16,-0.08}}},0.85,"ease_in_out",0)
scene:wait(1.1)
scene:fade_in(refs[17],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[28],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[22],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[23],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:create(refs[30],0.6,"linear",0)
scene:fade_in(refs[35],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:create(refs[31],0.6,"linear",0)
scene:wait(1.1)
scene:fade_in(refs[55],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[66],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[43],opacity=0.18},{target=refs[45],opacity=0.18},{target=refs[47],opacity=0.18},{target=refs[49],opacity=0.18},{target=refs[51],opacity=0.18}},0.35,"ease_in_out",0)
scene:play({{target=refs[66],shift={4.03,0}}},1.05,"ease_in_out",0)
scene:fade_in(refs[73],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:create(refs[68],0.7,"linear",0)
scene:play({{target=refs[43],shift={0.06,-0.03},opacity=1},{target=refs[45],shift={0.06,-0.03},opacity=1},{target=refs[47],shift={0.06,-0.03},opacity=1},{target=refs[49],shift={0.06,-0.03},opacity=1},{target=refs[51],shift={0.06,-0.03},opacity=1}},0.6,"ease_in_out",0.13333333333333333)
scene:fade(refs[66],0,0.25,"linear")
scene:fade(refs[75],0,0.25,"linear")
scene:wait(1.1)
scene:fade_in(refs[70],{["duration"]=0.5,["easing"]="smooth",["scale"]=1,["shift"]={0,0,0}})
scene:wait(2.3)
return scene
