-- Generated by scripts/render-update-scenes.mjs; edit overview.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=25,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=2500,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-0",["layer"]=40,["point"]={-4,12.01},["size"]=30,["text"]="Update / Prepare"}
refs[2] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-1",["layer"]=40,["point"]={2.16,12.01},["size"]=25,["text"]="API → tasks → prepared render data"}
refs[3] = scene:line {["from"]={-6.04,11.63},["id"]="update-overview-rule-2",["layer"]=5,["stroke"]="#cccccc",["to"]={6.04,11.63},["width"]=1}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-3",["layer"]=40,["point"]={-4.2,11.2},["size"]=18,["text"]="CALLER"}
refs[5] = scene:line {["from"]={-1.75,11.45},["id"]="update-overview-rule-4",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,11.45},["width"]=1}
refs[6] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-5",["layer"]=40,["point"]={-1.6,11.15},["size"]=18,["text"]="01  PAINT INPUTS"}
refs[7] = scene:line {["from"]={-1.75,8.95},["id"]="update-overview-rule-6",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,8.95},["width"]=1}
refs[8] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-7",["layer"]=40,["point"]={-1.6,8.65},["size"]=18,["text"]="02  INHERITED CONTEXT"}
refs[9] = scene:line {["from"]={-1.75,6.5},["id"]="update-overview-rule-8",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,6.5},["width"]=1}
refs[10] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-9",["layer"]=40,["point"]={-1.6,6.2},["size"]=18,["text"]="03  PAINT DISPATCH"}
refs[11] = scene:line {["from"]={-1.75,0.75},["id"]="update-overview-rule-10",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,0.75},["width"]=1}
refs[12] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-11",["layer"]=40,["point"]={-1.6,0.45},["size"]=18,["text"]="04  PREPARE TASKS"}
refs[13] = scene:line {["from"]={-1.75,-2.15},["id"]="update-overview-rule-12",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-2.15},["width"]=1}
refs[14] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-13",["layer"]=40,["point"]={-1.6,-2.45},["size"]=18,["text"]="05  PREPARED DATA"}
refs[15] = scene:group {["id"]="update-overview-api-14",["opacity"]=0.24}
refs[16] = refs[15]:rectangle {["center"]={-4.2,10.25},["fill"]="#ffffff",["id"]="update-overview-rect-15",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[17] = refs[15]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-16",["layer"]=40,["point"]={-4.2,10.43},["size"]=20,["text"]="canvas->update()"}
refs[18] = refs[15]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-17",["layer"]=40,["point"]={-4.2,10.03},["size"]=16,["text"]="Canvas::Impl::update()"}
refs[19] = scene:group {["id"]="update-overview-target-18",["opacity"]=0.24}
refs[20] = refs[19]:rectangle {["center"]={-4.2,8.6},["fill"]="#ffffff",["id"]="update-overview-rect-19",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[21] = refs[19]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-20",["layer"]=40,["point"]={-4.2,8.78},["size"]=20,["text"]="preUpdate()"}
refs[22] = refs[19]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-21",["layer"]=40,["point"]={-4.2,8.38},["size"]=16,["text"]="target Surface exists"}
refs[23] = scene:group {["id"]="update-overview-paint-22",["opacity"]=0.24}
refs[24] = refs[23]:rectangle {["center"]={-4.2,7.3},["fill"]="#ffffff",["id"]="update-overview-rect-23",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[25] = refs[23]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-24",["layer"]=40,["point"]={-4.2,7.48},["size"]=20,["text"]="Paint::Impl::update()"}
refs[26] = refs[23]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-25",["layer"]=40,["point"]={-4.2,7.08},["size"]=16,["text"]="mask / clip → inheritance"}
refs[27] = scene:group {["id"]="update-overview-children-26",["opacity"]=0.24}
refs[28] = refs[27]:rectangle {["center"]={-4.2,5.5},["fill"]="#ffffff",["id"]="update-overview-rect-27",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[29] = refs[27]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-28",["layer"]=40,["point"]={-4.2,5.68},["size"]=20,["text"]="SceneImpl::update()"}
refs[30] = refs[27]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-29",["layer"]=40,["point"]={-4.2,5.28},["size"]=16,["text"]="for (paint : paints)"}
refs[31] = scene:group {["id"]="update-overview-common-30",["opacity"]=0.24}
refs[32] = refs[31]:rectangle {["center"]={-4.2,1.6},["fill"]="#ffffff",["id"]="update-overview-rect-31",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[33] = refs[31]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-32",["layer"]=40,["point"]={-4.2,1.78},["size"]=20,["text"]="prepareCommon()"}
refs[34] = refs[31]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-33",["layer"]=40,["point"]={-4.2,1.38},["size"]=16,["text"]="clipBox · clip->done()"}
refs[35] = scene:group {["id"]="update-overview-request-34",["opacity"]=0.24}
refs[36] = refs[35]:rectangle {["center"]={-4.2,-0.7},["fill"]="#ffffff",["id"]="update-overview-rect-35",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[37] = refs[35]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-36",["layer"]=40,["point"]={-4.2,-0.52},["size"]=20,["text"]="Submit task"}
refs[38] = refs[35]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-37",["layer"]=40,["point"]={-4.2,-0.92},["size"]=16,["text"]="TaskScheduler::request()"}
refs[39] = scene:group {["id"]="update-overview-post-38",["opacity"]=0.24}
refs[40] = refs[39]:rectangle {["center"]={-4.2,-3.5},["fill"]="#ffffff",["id"]="update-overview-rect-39",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[41] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-40",["layer"]=40,["point"]={-4.2,-3.32},["size"]=20,["text"]="postUpdate()"}
refs[42] = refs[39]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-41",["layer"]=40,["point"]={-4.2,-3.72},["size"]=16,["text"]="status = Updating"}
refs[43] = scene:group {["id"]="update-overview-draw-42",["opacity"]=0.24}
refs[44] = refs[43]:rectangle {["center"]={-4.2,-9.7},["fill"]="#ffffff",["id"]="update-overview-rect-43",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[45] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-44",["layer"]=40,["point"]={-4.2,-9.52},["size"]=20,["text"]="Draw: task->done()"}
refs[46] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-45",["layer"]=40,["point"]={-4.2,-9.92},["size"]=16,["text"]="renderShape / renderImage"}
refs[47] = scene:route {["dash"]={6,5},["id"]="update-overview-route-46",["layer"]=7,["points"]={{-4.2,9.78},{-4.2,9.08}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[48] = scene:route {["dash"]={6,5},["id"]="update-overview-route-47",["layer"]=7,["points"]={{-4.2,8.12},{-4.2,7.78}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[49] = scene:route {["dash"]={6,5},["id"]="update-overview-route-48",["layer"]=7,["points"]={{-4.2,6.82},{-4.2,5.98}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[50] = scene:route {["dash"]={6,5},["id"]="update-overview-route-49",["layer"]=7,["points"]={{-4.2,1.12},{-4.2,-0.22}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[51] = scene:route {["dash"]={6,5},["id"]="update-overview-route-50",["layer"]=7,["points"]={{-4.2,-1.18},{-4.2,-3.02}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[52] = scene:route {["dash"]={6,5},["id"]="update-overview-route-51",["layer"]=7,["points"]={{-4.2,-3.98},{-4.2,-9.22}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[53] = scene:group {["id"]="update-overview-inputs-52",["opacity"]=1}
refs[54] = refs[53]:rectangle {["center"]={-0.8,10.15},["fill"]="#ffffff",["id"]="update-overview-rect-53",["layer"]=12,["size"]={0.84,0.62},["stroke"]="#202020",["width"]=1.5}
refs[55] = refs[53]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-54",["layer"]=40,["point"]={-0.8,9.5},["size"]=18,["text"]="Rect"}
refs[56] = refs[53]:polygon {["fill"]="#e661212a",["id"]="update-overview-triangle-55",["layer"]=20,["points"]={{0.80625,10.45125},{0.63125,9.83875},{1.2875,9.83875}},["stroke"]="#e66121",["width"]=2.2}
refs[57] = refs[53]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="update-overview-text-56",["layer"]=40,["point"]={1.05,9.5},["size"]=18,["text"]="A"}
refs[58] = refs[53]:rectangle {["center"]={2.19,10.15},["fill"]="#1f66c42a",["id"]="update-overview-rect-57",["layer"]=12,["size"]={0.68,0.52},["stroke"]="#1f66c4",["width"]=2}
refs[59] = refs[53]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="update-overview-text-58",["layer"]=40,["point"]={2.19,9.5},["size"]=18,["text"]="B"}
refs[60] = refs[53]:rectangle {["center"]={1.52,10.04},["dash"]={6,5},["fill"]="#00000000",["id"]="update-overview-scene-scope-59",["layer"]=8,["size"]={2.32,1.48},["stroke"]="#999999",["width"]=1}
refs[61] = refs[53]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-60",["layer"]=40,["point"]={1.52,9.17},["size"]=16,["text"]="Scene(A, B)"}
refs[62] = refs[53]:group {["id"]="update-overview-image-input-61"}
refs[63] = refs[62]:image {["center"]={4.5,10.15},["filter"]="nearest",["id"]="update-overview-bitmap-62",["layer"]=20,["pixels"]={"#e66121","#1f66c4","#1f66c4","#e66121"},["size"]={2,2},["width"]=0.72}
refs[64] = refs[53]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-63",["layer"]=40,["point"]={4.5,9.5},["size"]=18,["text"]="Picture"}
refs[65] = scene:group {["id"]="update-overview-inherited-64",["opacity"]=0}
refs[66] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-65",["layer"]=40,["point"]={0.1,8.02},["size"]=16,["text"]="Transform"}
refs[67] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-66",["layer"]=40,["point"]={0.1,7.63},["size"]=20,["text"]="parent × local"}
refs[68] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-67",["layer"]=40,["point"]={4,8.02},["size"]=16,["text"]="Update flags"}
refs[69] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-68",["layer"]=40,["point"]={4,7.63},["size"]=20,["text"]="flags | renderFlag"}
refs[70] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-69",["layer"]=40,["point"]={0.1,6.98},["size"]=20,["text"]="opacity × parent"}
refs[71] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-70",["layer"]=40,["point"]={4,6.98},["size"]=20,["text"]="clip stack"}
refs[72] = refs[65]:route {["dash"]={6,5},["id"]="update-overview-route-71",["layer"]=7,["points"]={{-2.63,7.3},{-1.92,7.3}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[73] = scene:group {["id"]="update-overview-recursion-72",["opacity"]=0}
refs[74] = refs[73]:rectangle {["center"]={2.1,5.5},["fill"]="#ffffff",["id"]="update-overview-rect-73",["layer"]=12,["size"]={3.3,0.56},["stroke"]="#202020",["width"]=1.2}
refs[75] = refs[73]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-74",["layer"]=40,["point"]={2.1,5.5},["size"]=20,["text"]="child Paint::update()"}
refs[76] = refs[73]:route {["dash"]={6,5},["id"]="update-overview-route-75",["layer"]=7,["points"]={{-2.63,5.5},{0.44,5.5}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[77] = refs[73]:route {["dash"]={6,5},["id"]="update-overview-route-76",["layer"]=7,["points"]={{2.1,5.21},{2.1,4.93},{0.1,4.93},{0.1,4.61}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[78] = refs[73]:route {["dash"]={6,5},["id"]="update-overview-route-77",["layer"]=7,["points"]={{2.1,4.93},{4.1,4.93},{4.1,4.61}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[79] = scene:group {["id"]="update-overview-shape-78",["opacity"]=0.24}
refs[80] = refs[79]:rectangle {["center"]={0.1,4.3},["fill"]="#ffffff",["id"]="update-overview-rect-79",["layer"]=12,["size"]={3.1,0.6},["stroke"]="#202020",["width"]=1.2}
refs[81] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-80",["layer"]=40,["point"]={0.1,4.3},["size"]=20,["text"]="ShapeImpl::update()"}
refs[82] = scene:group {["id"]="update-overview-picture-81",["opacity"]=0.24}
refs[83] = refs[82]:rectangle {["center"]={4.1,4.3},["fill"]="#ffffff",["id"]="update-overview-rect-82",["layer"]=12,["size"]={3.1,0.6},["stroke"]="#202020",["width"]=1.2}
refs[84] = refs[82]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-83",["layer"]=40,["point"]={4.1,4.3},["size"]=20,["text"]="PictureImpl::update()"}
refs[85] = scene:group {["id"]="update-overview-bitmap-branch-84",["opacity"]=0}
refs[86] = refs[85]:route {["dash"]={6,5},["id"]="update-overview-route-85",["layer"]=7,["points"]={{0.1,3.99},{0.1,3.48}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[87] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-86",["layer"]=40,["point"]={0.1,3.2},["size"]=19,["text"]="RenderShape"}
refs[88] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-87",["layer"]=40,["point"]={4.1,3.69},["size"]=17,["text"]="load()"}
refs[89] = refs[85]:route {["dash"]={6,5},["id"]="update-overview-route-88",["layer"]=7,["points"]={{4.1,3.51},{4.1,3.36},{3.05,3.36},{3.05,3.11}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[90] = refs[85]:route {["dash"]={6,5},["id"]="update-overview-route-89",["layer"]=7,["points"]={{4.1,3.36},{5.05,3.36},{5.05,3.11}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[91] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-90",["layer"]=40,["point"]={3.05,2.85},["size"]=18,["text"]="Bitmap"}
refs[92] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-91",["layer"]=40,["point"]={5.05,2.85},["size"]=18,["text"]="Vector"}
refs[93] = refs[85]:route {["dash"]={6,5},["id"]="update-overview-route-92",["layer"]=7,["points"]={{5.05,2.67},{5.05,2.5}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[94] = refs[85]:rectangle {["center"]={5.05,2.15},["fill"]="#ffffff",["id"]="update-overview-rect-93",["layer"]=12,["size"]={1.68,0.68},["stroke"]="#999999",["width"]=1}
refs[95] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-94",["layer"]=40,["point"]={5.05,2.27},["size"]=16,["text"]="child Paint"}
refs[96] = refs[85]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-95",["layer"]=40,["point"]={5.05,2.04},["size"]=14,["text"]="update()"}
refs[97] = scene:group {["id"]="update-overview-prepare-join-96",["opacity"]=0}
refs[98] = refs[97]:route {["dash"]={6,5},["id"]="update-overview-route-97",["layer"]=7,["points"]={{0.1,2.99},{0.1,2.4},{-2.18,2.4},{-2.18,1.6},{-2.63,1.6}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[99] = refs[97]:route {["dash"]={6,5},["id"]="update-overview-route-98",["layer"]=7,["points"]={{3.05,2.67},{3.05,2.4},{0.1,2.4}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[100] = refs[97]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-99",["layer"]=40,["point"]={0.1,2},["size"]=17,["text"]="prepare()"}
refs[101] = scene:group {["id"]="update-overview-effects-100",["opacity"]=0}
refs[102] = refs[101]:rectangle {["center"]={2.1,1.3},["fill"]="#ffffff",["id"]="update-overview-rect-101",["layer"]=12,["size"]={7.5,0.84},["stroke"]="#cccccc",["width"]=1}
refs[103] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-102",["layer"]=40,["point"]={-0.6,1.48},["size"]=18,["text"]="Scene effects?"}
refs[104] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-103",["layer"]=40,["point"]={-0.6,1.18},["size"]=16,["text"]="optional"}
refs[105] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-104",["layer"]=40,["point"]={3.12,1.48},["size"]=20,["text"]="prepare(effect, matrix)"}
refs[106] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-105",["layer"]=40,["point"]={3.12,1.18},["size"]=18,["text"]="parameters / extent"}
refs[107] = scene:group {["id"]="update-overview-worker-shape-106",["opacity"]=0.24}
refs[108] = refs[107]:rectangle {["center"]={0.1,-0.7},["fill"]="#202020",["id"]="update-overview-rect-107",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[109] = refs[107]:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-overview-text-108",["layer"]=40,["point"]={0.1,-0.52},["size"]=20,["text"]="SwShapeTask::run(tid)"}
refs[110] = refs[107]:text {["align"]={0.5,0.5},["fill"]="#e0e0e0",["font"]="Pretendard",["id"]="update-overview-text-109",["layer"]=40,["point"]={0.1,-0.92},["size"]=16,["text"]="shapeGenRle() / fill / stroke"}
refs[111] = scene:group {["id"]="update-overview-worker-image-110",["opacity"]=0.24}
refs[112] = refs[111]:rectangle {["center"]={4.1,-0.7},["fill"]="#202020",["id"]="update-overview-rect-111",["layer"]=12,["size"]={3.1,0.94},["stroke"]="#202020",["width"]=1.5}
refs[113] = refs[111]:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-overview-text-112",["layer"]=40,["point"]={4.1,-0.52},["size"]=20,["text"]="SwImageTask::run(tid)"}
refs[114] = refs[111]:text {["align"]={0.5,0.5},["fill"]="#e0e0e0",["font"]="Pretendard",["id"]="update-overview-text-113",["layer"]=40,["point"]={4.1,-0.92},["size"]=16,["text"]="convertCS() / premultiply()"}
refs[115] = scene:group {["id"]="update-overview-task-dispatch-114",["opacity"]=0}
refs[116] = refs[115]:route {["dash"]={6,5},["id"]="update-overview-route-115",["layer"]=7,["points"]={{-2.64,-0.7},{-1.86,-0.7},{-1.86,0},{0.1,0},{0.1,-0.21}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[117] = refs[115]:route {["dash"]={6,5},["id"]="update-overview-route-116",["layer"]=7,["points"]={{0.1,0},{4.1,0},{4.1,-0.21}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[118] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-117",["layer"]=40,["point"]={2.1,-1.6},["size"]=17,["text"]="workers may overlap"}
refs[119] = scene:line {["from"]={2.1,-2.85},["id"]="update-overview-rule-118",["layer"]=5,["stroke"]="#cccccc",["to"]={2.1,-7.9},["width"]=1}
refs[120] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-119",["layer"]=40,["point"]={0.1,-3.1},["size"]=17,["text"]="SHAPE"}
refs[121] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-120",["layer"]=40,["point"]={4.1,-3.1},["size"]=17,["text"]="IMAGE"}
refs[122] = scene:group {["id"]="update-overview-shape-artifacts-121",["opacity"]=0}
refs[123] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-122",["layer"]=40,["point"]={-0.85,-3.7},["size"]=19,["text"]="Rect"}
refs[124] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-123",["layer"]=40,["point"]={1.1,-3.7},["size"]=19,["text"]="RLE"}
refs[125] = refs[122]:rectangle {["center"]={-0.85,-4.6},["fill"]="#ffffff",["id"]="update-overview-rect-124",["layer"]=12,["size"]={0.92,0.92},["stroke"]="#202020",["width"]=1.5}
refs[126] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-125",["layer"]=40,["point"]={-0.85,-5.45},["size"]=17,["text"]="fastTrack"}
refs[127] = refs[122]:group {["id"]="update-overview-rle-row-126",["opacity"]=0}
refs[128] = refs[127]:line {["from"]={0.825,-4.275},["id"]="update-overview-rle-length-127",["layer"]=20,["stroke"]="#d4d4d4",["to"]={0.875,-4.275},["width"]=1.2}
refs[129] = refs[127]:rectangle {["center"]={0.825,-4.275},["fill"]="#d4d4d4",["id"]="update-overview-rect-128",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[130] = refs[127]:line {["from"]={0.875,-4.275},["id"]="update-overview-rle-length-129",["layer"]=20,["stroke"]="#a0a0a0",["to"]={0.925,-4.275},["width"]=1.2}
refs[131] = refs[127]:rectangle {["center"]={0.875,-4.275},["fill"]="#a0a0a0",["id"]="update-overview-rect-130",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[132] = refs[122]:group {["id"]="update-overview-rle-row-131",["opacity"]=0}
refs[133] = refs[132]:line {["from"]={0.825,-4.325},["id"]="update-overview-rle-length-132",["layer"]=20,["stroke"]="#979797",["to"]={0.875,-4.325},["width"]=1.2}
refs[134] = refs[132]:rectangle {["center"]={0.825,-4.325},["fill"]="#979797",["id"]="update-overview-rect-133",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[135] = refs[132]:line {["from"]={0.875,-4.325},["id"]="update-overview-rle-length-134",["layer"]=20,["stroke"]="#262626",["to"]={0.925,-4.325},["width"]=1.2}
refs[136] = refs[132]:rectangle {["center"]={0.875,-4.325},["fill"]="#262626",["id"]="update-overview-rect-135",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[137] = refs[132]:line {["from"]={0.925,-4.325},["id"]="update-overview-rle-length-136",["layer"]=20,["stroke"]="#c6c6c6",["to"]={0.975,-4.325},["width"]=1.2}
refs[138] = refs[132]:rectangle {["center"]={0.925,-4.325},["fill"]="#c6c6c6",["id"]="update-overview-rect-137",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[139] = refs[122]:group {["id"]="update-overview-rle-row-138",["opacity"]=0}
refs[140] = refs[139]:line {["from"]={0.825,-4.375},["id"]="update-overview-rle-length-139",["layer"]=20,["stroke"]="#5b5b5b",["to"]={0.875,-4.375},["width"]=1.2}
refs[141] = refs[139]:rectangle {["center"]={0.825,-4.375},["fill"]="#5b5b5b",["id"]="update-overview-rect-140",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[142] = refs[139]:line {["from"]={0.875,-4.375},["id"]="update-overview-rle-length-141",["layer"]=20,["stroke"]="#202020",["to"]={0.925,-4.375},["width"]=1.2}
refs[143] = refs[139]:rectangle {["center"]={0.875,-4.375},["fill"]="#202020",["id"]="update-overview-rect-142",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[144] = refs[139]:line {["from"]={0.925,-4.375},["id"]="update-overview-rle-length-143",["layer"]=20,["stroke"]="#383838",["to"]={0.975,-4.375},["width"]=1.2}
refs[145] = refs[139]:rectangle {["center"]={0.925,-4.375},["fill"]="#383838",["id"]="update-overview-rect-144",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[146] = refs[139]:line {["from"]={0.975,-4.375},["id"]="update-overview-rle-length-145",["layer"]=20,["stroke"]="#e2e2e2",["to"]={1.025,-4.375},["width"]=1.2}
refs[147] = refs[139]:rectangle {["center"]={0.975,-4.375},["fill"]="#e2e2e2",["id"]="update-overview-rect-146",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[148] = refs[122]:group {["id"]="update-overview-rle-row-147",["opacity"]=0}
refs[149] = refs[148]:line {["from"]={0.775,-4.425},["id"]="update-overview-rle-length-148",["layer"]=20,["stroke"]="#ebebeb",["to"]={0.825,-4.425},["width"]=1.2}
refs[150] = refs[148]:rectangle {["center"]={0.775,-4.425},["fill"]="#ebebeb",["id"]="update-overview-rect-149",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[151] = refs[148]:line {["from"]={0.825,-4.425},["id"]="update-overview-rle-length-150",["layer"]=20,["stroke"]="#272727",["to"]={0.875,-4.425},["width"]=1.2}
refs[152] = refs[148]:rectangle {["center"]={0.825,-4.425},["fill"]="#272727",["id"]="update-overview-rect-151",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[153] = refs[148]:line {["from"]={0.875,-4.425},["id"]="update-overview-rle-length-152",["layer"]=20,["stroke"]="#202020",["to"]={0.975,-4.425},["width"]=1.2}
refs[154] = refs[148]:rectangle {["center"]={0.875,-4.425},["fill"]="#202020",["id"]="update-overview-rect-153",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[155] = refs[148]:line {["from"]={0.975,-4.425},["id"]="update-overview-rle-length-154",["layer"]=20,["stroke"]="#575757",["to"]={1.025,-4.425},["width"]=1.2}
refs[156] = refs[148]:rectangle {["center"]={0.975,-4.425},["fill"]="#575757",["id"]="update-overview-rect-155",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[157] = refs[148]:line {["from"]={1.025,-4.425},["id"]="update-overview-rle-length-156",["layer"]=20,["stroke"]="#f0f0f0",["to"]={1.075,-4.425},["width"]=1.2}
refs[158] = refs[148]:rectangle {["center"]={1.025,-4.425},["fill"]="#f0f0f0",["id"]="update-overview-rect-157",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[159] = refs[122]:group {["id"]="update-overview-rle-row-158",["opacity"]=0}
refs[160] = refs[159]:line {["from"]={0.775,-4.475},["id"]="update-overview-rle-length-159",["layer"]=20,["stroke"]="#b6b6b6",["to"]={0.825,-4.475},["width"]=1.2}
refs[161] = refs[159]:rectangle {["center"]={0.775,-4.475},["fill"]="#b6b6b6",["id"]="update-overview-rect-160",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[162] = refs[159]:line {["from"]={0.825,-4.475},["id"]="update-overview-rle-length-161",["layer"]=20,["stroke"]="#202020",["to"]={1.025,-4.475},["width"]=1.2}
refs[163] = refs[159]:rectangle {["center"]={0.825,-4.475},["fill"]="#202020",["id"]="update-overview-rect-162",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[164] = refs[159]:line {["from"]={1.025,-4.475},["id"]="update-overview-rle-length-163",["layer"]=20,["stroke"]="#828282",["to"]={1.075,-4.475},["width"]=1.2}
refs[165] = refs[159]:rectangle {["center"]={1.025,-4.475},["fill"]="#828282",["id"]="update-overview-rect-164",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[166] = refs[122]:group {["id"]="update-overview-rle-row-165",["opacity"]=0}
refs[167] = refs[166]:line {["from"]={0.775,-4.525},["id"]="update-overview-rle-length-166",["layer"]=20,["stroke"]="#7a7a7a",["to"]={0.825,-4.525},["width"]=1.2}
refs[168] = refs[166]:rectangle {["center"]={0.775,-4.525},["fill"]="#7a7a7a",["id"]="update-overview-rect-167",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[169] = refs[166]:line {["from"]={0.825,-4.525},["id"]="update-overview-rle-length-168",["layer"]=20,["stroke"]="#202020",["to"]={1.075,-4.525},["width"]=1.2}
refs[170] = refs[166]:rectangle {["center"]={0.825,-4.525},["fill"]="#202020",["id"]="update-overview-rect-169",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[171] = refs[166]:line {["from"]={1.075,-4.525},["id"]="update-overview-rle-length-170",["layer"]=20,["stroke"]="#aeaeae",["to"]={1.125,-4.525},["width"]=1.2}
refs[172] = refs[166]:rectangle {["center"]={1.075,-4.525},["fill"]="#aeaeae",["id"]="update-overview-rect-171",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[173] = refs[122]:group {["id"]="update-overview-rle-row-172",["opacity"]=0}
refs[174] = refs[173]:line {["from"]={0.775,-4.575},["id"]="update-overview-rle-length-173",["layer"]=20,["stroke"]="#3e3e3e",["to"]={0.825,-4.575},["width"]=1.2}
refs[175] = refs[173]:rectangle {["center"]={0.775,-4.575},["fill"]="#3e3e3e",["id"]="update-overview-rect-174",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[176] = refs[173]:line {["from"]={0.825,-4.575},["id"]="update-overview-rle-length-175",["layer"]=20,["stroke"]="#202020",["to"]={1.075,-4.575},["width"]=1.2}
refs[177] = refs[173]:rectangle {["center"]={0.825,-4.575},["fill"]="#202020",["id"]="update-overview-rect-176",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[178] = refs[173]:line {["from"]={1.075,-4.575},["id"]="update-overview-rle-length-177",["layer"]=20,["stroke"]="#2b2b2b",["to"]={1.125,-4.575},["width"]=1.2}
refs[179] = refs[173]:rectangle {["center"]={1.075,-4.575},["fill"]="#2b2b2b",["id"]="update-overview-rect-178",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[180] = refs[173]:line {["from"]={1.125,-4.575},["id"]="update-overview-rle-length-179",["layer"]=20,["stroke"]="#d1d1d1",["to"]={1.175,-4.575},["width"]=1.2}
refs[181] = refs[173]:rectangle {["center"]={1.125,-4.575},["fill"]="#d1d1d1",["id"]="update-overview-rect-180",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[182] = refs[122]:group {["id"]="update-overview-rle-row-181",["opacity"]=0}
refs[183] = refs[182]:line {["from"]={0.725,-4.625},["id"]="update-overview-rle-length-182",["layer"]=20,["stroke"]="#d4d4d4",["to"]={0.775,-4.625},["width"]=1.2}
refs[184] = refs[182]:rectangle {["center"]={0.725,-4.625},["fill"]="#d4d4d4",["id"]="update-overview-rect-183",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[185] = refs[182]:line {["from"]={0.775,-4.625},["id"]="update-overview-rle-length-184",["layer"]=20,["stroke"]="#202020",["to"]={1.125,-4.625},["width"]=1.2}
refs[186] = refs[182]:rectangle {["center"]={0.775,-4.625},["fill"]="#202020",["id"]="update-overview-rect-185",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[187] = refs[182]:line {["from"]={1.125,-4.625},["id"]="update-overview-rle-length-186",["layer"]=20,["stroke"]="#414141",["to"]={1.175,-4.625},["width"]=1.2}
refs[188] = refs[182]:rectangle {["center"]={1.125,-4.625},["fill"]="#414141",["id"]="update-overview-rect-187",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[189] = refs[182]:line {["from"]={1.175,-4.625},["id"]="update-overview-rle-length-188",["layer"]=20,["stroke"]="#e7e7e7",["to"]={1.225,-4.625},["width"]=1.2}
refs[190] = refs[182]:rectangle {["center"]={1.175,-4.625},["fill"]="#e7e7e7",["id"]="update-overview-rect-189",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[191] = refs[122]:group {["id"]="update-overview-rle-row-190",["opacity"]=0}
refs[192] = refs[191]:line {["from"]={0.725,-4.675},["id"]="update-overview-rle-length-191",["layer"]=20,["stroke"]="#979797",["to"]={0.775,-4.675},["width"]=1.2}
refs[193] = refs[191]:rectangle {["center"]={0.725,-4.675},["fill"]="#979797",["id"]="update-overview-rect-192",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[194] = refs[191]:line {["from"]={0.775,-4.675},["id"]="update-overview-rle-length-193",["layer"]=20,["stroke"]="#202020",["to"]={1.175,-4.675},["width"]=1.2}
refs[195] = refs[191]:rectangle {["center"]={0.775,-4.675},["fill"]="#202020",["id"]="update-overview-rect-194",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[196] = refs[191]:line {["from"]={1.175,-4.675},["id"]="update-overview-rle-length-195",["layer"]=20,["stroke"]="#646464",["to"]={1.225,-4.675},["width"]=1.2}
refs[197] = refs[191]:rectangle {["center"]={1.175,-4.675},["fill"]="#646464",["id"]="update-overview-rect-196",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[198] = refs[122]:group {["id"]="update-overview-rle-row-197",["opacity"]=0}
refs[199] = refs[198]:line {["from"]={0.725,-4.725},["id"]="update-overview-rle-length-198",["layer"]=20,["stroke"]="#5b5b5b",["to"]={0.775,-4.725},["width"]=1.2}
refs[200] = refs[198]:rectangle {["center"]={0.725,-4.725},["fill"]="#5b5b5b",["id"]="update-overview-rect-199",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[201] = refs[198]:line {["from"]={0.775,-4.725},["id"]="update-overview-rle-length-200",["layer"]=20,["stroke"]="#202020",["to"]={1.225,-4.725},["width"]=1.2}
refs[202] = refs[198]:rectangle {["center"]={0.775,-4.725},["fill"]="#202020",["id"]="update-overview-rect-201",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[203] = refs[198]:line {["from"]={1.225,-4.725},["id"]="update-overview-rle-length-202",["layer"]=20,["stroke"]="#919191",["to"]={1.275,-4.725},["width"]=1.2}
refs[204] = refs[198]:rectangle {["center"]={1.225,-4.725},["fill"]="#919191",["id"]="update-overview-rect-203",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[205] = refs[122]:group {["id"]="update-overview-rle-row-204",["opacity"]=0}
refs[206] = refs[205]:line {["from"]={0.675,-4.775},["id"]="update-overview-rle-length-205",["layer"]=20,["stroke"]="#ebebeb",["to"]={0.725,-4.775},["width"]=1.2}
refs[207] = refs[205]:rectangle {["center"]={0.675,-4.775},["fill"]="#ebebeb",["id"]="update-overview-rect-206",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[208] = refs[205]:line {["from"]={0.725,-4.775},["id"]="update-overview-rle-length-207",["layer"]=20,["stroke"]="#272727",["to"]={0.775,-4.775},["width"]=1.2}
refs[209] = refs[205]:rectangle {["center"]={0.725,-4.775},["fill"]="#272727",["id"]="update-overview-rect-208",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[210] = refs[205]:line {["from"]={0.775,-4.775},["id"]="update-overview-rle-length-209",["layer"]=20,["stroke"]="#202020",["to"]={1.225,-4.775},["width"]=1.2}
refs[211] = refs[205]:rectangle {["center"]={0.775,-4.775},["fill"]="#202020",["id"]="update-overview-rect-210",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[212] = refs[205]:line {["from"]={1.225,-4.775},["id"]="update-overview-rle-length-211",["layer"]=20,["stroke"]="#222222",["to"]={1.275,-4.775},["width"]=1.2}
refs[213] = refs[205]:rectangle {["center"]={1.225,-4.775},["fill"]="#222222",["id"]="update-overview-rect-212",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[214] = refs[205]:line {["from"]={1.275,-4.775},["id"]="update-overview-rle-length-213",["layer"]=20,["stroke"]="#bbbbbb",["to"]={1.325,-4.775},["width"]=1.2}
refs[215] = refs[205]:rectangle {["center"]={1.275,-4.775},["fill"]="#bbbbbb",["id"]="update-overview-rect-214",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[216] = refs[122]:group {["id"]="update-overview-rle-row-215",["opacity"]=0}
refs[217] = refs[216]:line {["from"]={0.675,-4.825},["id"]="update-overview-rle-length-216",["layer"]=20,["stroke"]="#b6b6b6",["to"]={0.725,-4.825},["width"]=1.2}
refs[218] = refs[216]:rectangle {["center"]={0.675,-4.825},["fill"]="#b6b6b6",["id"]="update-overview-rect-217",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[219] = refs[216]:line {["from"]={0.725,-4.825},["id"]="update-overview-rle-length-218",["layer"]=20,["stroke"]="#202020",["to"]={1.275,-4.825},["width"]=1.2}
refs[220] = refs[216]:rectangle {["center"]={0.725,-4.825},["fill"]="#202020",["id"]="update-overview-rect-219",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[221] = refs[216]:line {["from"]={1.275,-4.825},["id"]="update-overview-rle-length-220",["layer"]=20,["stroke"]="#303030",["to"]={1.325,-4.825},["width"]=1.2}
refs[222] = refs[216]:rectangle {["center"]={1.275,-4.825},["fill"]="#303030",["id"]="update-overview-rect-221",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[223] = refs[216]:line {["from"]={1.325,-4.825},["id"]="update-overview-rle-length-222",["layer"]=20,["stroke"]="#dadada",["to"]={1.375,-4.825},["width"]=1.2}
refs[224] = refs[216]:rectangle {["center"]={1.325,-4.825},["fill"]="#dadada",["id"]="update-overview-rect-223",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[225] = refs[122]:group {["id"]="update-overview-rle-row-224",["opacity"]=0}
refs[226] = refs[225]:line {["from"]={0.675,-4.875},["id"]="update-overview-rle-length-225",["layer"]=20,["stroke"]="#7a7a7a",["to"]={0.725,-4.875},["width"]=1.2}
refs[227] = refs[225]:rectangle {["center"]={0.675,-4.875},["fill"]="#7a7a7a",["id"]="update-overview-rect-226",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[228] = refs[225]:line {["from"]={0.725,-4.875},["id"]="update-overview-rle-length-227",["layer"]=20,["stroke"]="#202020",["to"]={1.325,-4.875},["width"]=1.2}
refs[229] = refs[225]:rectangle {["center"]={0.725,-4.875},["fill"]="#202020",["id"]="update-overview-rect-228",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[230] = refs[225]:line {["from"]={1.325,-4.875},["id"]="update-overview-rle-length-229",["layer"]=20,["stroke"]="#4c4c4c",["to"]={1.375,-4.875},["width"]=1.2}
refs[231] = refs[225]:rectangle {["center"]={1.325,-4.875},["fill"]="#4c4c4c",["id"]="update-overview-rect-230",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[232] = refs[225]:line {["from"]={1.375,-4.875},["id"]="update-overview-rle-length-231",["layer"]=20,["stroke"]="#ececec",["to"]={1.425,-4.875},["width"]=1.2}
refs[233] = refs[225]:rectangle {["center"]={1.375,-4.875},["fill"]="#ececec",["id"]="update-overview-rect-232",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[234] = refs[122]:group {["id"]="update-overview-rle-row-233",["opacity"]=0}
refs[235] = refs[234]:line {["from"]={0.675,-4.925},["id"]="update-overview-rle-length-234",["layer"]=20,["stroke"]="#3e3e3e",["to"]={0.725,-4.925},["width"]=1.2}
refs[236] = refs[234]:rectangle {["center"]={0.675,-4.925},["fill"]="#3e3e3e",["id"]="update-overview-rect-235",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[237] = refs[234]:line {["from"]={0.725,-4.925},["id"]="update-overview-rle-length-236",["layer"]=20,["stroke"]="#202020",["to"]={1.375,-4.925},["width"]=1.2}
refs[238] = refs[234]:rectangle {["center"]={0.725,-4.925},["fill"]="#202020",["id"]="update-overview-rect-237",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[239] = refs[234]:line {["from"]={1.375,-4.925},["id"]="update-overview-rle-length-238",["layer"]=20,["stroke"]="#737373",["to"]={1.425,-4.925},["width"]=1.2}
refs[240] = refs[234]:rectangle {["center"]={1.375,-4.925},["fill"]="#737373",["id"]="update-overview-rect-239",["layer"]=21,["size"]={0.024,0.024},["stroke"]="#00000000",["width"]=0}
refs[241] = refs[122]:rectangle {["center"]={1.1,-4.6},["fill"]="#00000000",["id"]="update-overview-rect-240",["layer"]=12,["size"]={1.2,1.2},["stroke"]="#aaaaaa",["width"]=1}
refs[242] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-241",["layer"]=40,["point"]={1.1,-5.45},["size"]=17,["text"]="spans"}
refs[243] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-242",["layer"]=40,["point"]={0.1,-6.15},["size"]=19,["text"]="x · y · len · coverage"}
refs[244] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-243",["layer"]=40,["point"]={0.1,-6.8},["size"]=18,["text"]="+ strokeRle"}
refs[245] = refs[122]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-244",["layer"]=40,["point"]={0.1,-7.25},["size"]=18,["text"]="+ gradient colors"}
refs[246] = scene:group {["id"]="update-overview-image-artifacts-245",["opacity"]=0}
refs[247] = refs[246]:group {["id"]="update-overview-raw-image-246"}
refs[248] = refs[247]:image {["center"]={3.38,-4.24},["filter"]="nearest",["id"]="update-overview-raw-quad-247",["layer"]=20,["pixels"]={"#e66121","#1f66c4","#1f66c4","#e66121"},["size"]={2,2},["width"]=0.28}
refs[249] = refs[246]:group {["id"]="update-overview-transformed-extent-248",["opacity"]=0}
refs[250] = refs[249]:rectangle {["center"]={4.1,-4.6},["fill"]="#00000000",["id"]="update-overview-rect-249",["layer"]=25,["size"]={0.56,0.56},["stroke"]="#1f66c4",["width"]=2}
refs[251] = refs[246]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-250",["layer"]=40,["point"]={4.1,-3.7},["size"]=20,["text"]="imagePrepare()"}
refs[252] = refs[246]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-251",["layer"]=40,["point"]={4.1,-5.45},["size"]=19,["text"]="matrix → extent"}
refs[253] = refs[246]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-252",["layer"]=40,["point"]={4.1,-6.15},["size"]=18,["text"]="renderBox · direct / scaled"}
refs[254] = refs[246]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-253",["layer"]=40,["point"]={4.1,-6.8},["size"]=18,["text"]="+ RLE when clipped"}
refs[255] = scene:group {["id"]="update-overview-image-guide-254",["opacity"]=0}
refs[256] = refs[255]:route {["dash"]={6,5},["id"]="update-overview-route-255",["layer"]=7,["points"]={{4.6,-4.24},{5.05,-4.24},{5.05,-4.88}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[257] = scene:group {["id"]="update-overview-source-converted-256",["opacity"]=0}
refs[258] = refs[257]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-257",["layer"]=40,["point"]={4.1,-7.25},["size"]=18,["text"]="source bytes normalized"}
refs[259] = scene:group {["id"]="update-overview-update-return-258",["opacity"]=0}
refs[260] = refs[259]:rectangle {["center"]={-4.2,-2.3},["fill"]="#f2f2f2",["id"]="update-overview-rect-259",["layer"]=12,["size"]={2.3,0.56},["stroke"]="#00000000",["width"]=0}
refs[261] = refs[259]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-260",["layer"]=40,["point"]={-4.2,-2.3},["size"]=18,["text"]="no global wait"}
refs[262] = scene:group {["id"]="update-overview-prepared-dependency-261",["opacity"]=0}
refs[263] = refs[262]:route {["dash"]={6,5},["id"]="update-overview-route-262",["layer"]=7,["points"]={{0.1,-7.95},{0.1,-8.8},{-2.2,-8.8},{-2.2,-9.7},{-2.63,-9.7}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[264] = refs[262]:route {["dash"]={6,5},["id"]="update-overview-route-263",["layer"]=7,["points"]={{4.1,-7.95},{4.1,-8.8},{0.1,-8.8}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[265] = refs[262]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-264",["layer"]=40,["point"]={2.1,-9.5},["size"]=20,["text"]="prepared data"}
refs[266] = scene:line {["from"]={-6.04,-11.05},["id"]="update-overview-rule-265",["layer"]=5,["stroke"]="#cccccc",["to"]={6.04,-11.05},["width"]=1}
refs[267] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-266",["layer"]=40,["point"]={0,-11.45},["size"]=17,["text"]="NEXT"}
refs[268] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-overview-text-267",["layer"]=40,["point"]={0,-11.9},["size"]=24,["text"]="Draw / Raster → Postprocessing"}
refs[269] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="update-overview-text-268",["layer"]=40,["point"]={0,-12.3},["size"]=17,["text"]="Update prepares data; Canvas pixels are written during Draw."}
scene:play({{target=refs[15],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[19],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[23],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[65],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[27],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[73],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[79],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[82],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[85],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[101],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[97],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[31],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[35],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[115],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[39],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[259],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[107],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[111],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[122],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[127],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[132],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[139],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[148],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[159],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[166],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[173],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[182],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[191],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[198],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[205],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[216],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[225],opacity=1}},0.11,"ease_in_out",0)
scene:play({{target=refs[234],opacity=1}},0.11,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[246],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[255],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[247],shift={0.72,-0.36}}},0.8,"ease_in_out",0)
scene:play({{target=refs[249],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[257],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1.1)
scene:play({{target=refs[262],opacity=1}},0.45,"ease_in_out",0)
scene:play({{target=refs[43],opacity=1}},0.45,"ease_in_out",0)
scene:wait(2.4)
return scene
