-- Generated by scripts/render-update-scenes.mjs; edit rle.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=8,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=800,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1200}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-0",["layer"]=50,["point"]={0,3.58},["role"]="text",["size"]=30,["text"]="SwMpool · temporary cells, retained spans"}
refs[2] = scene:line {["from"]={-5.55,3.2},["id"]="update-pool-line-1",["layer"]=25,["stroke"]="#cccccc",["to"]={5.55,3.2},["width"]=1}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-2",["layer"]=50,["point"]={-4.2,2.83},["role"]="text",["size"]=23,["text"]="SwShapeTask · tid"}
refs[4] = scene:arrow {["dash"]={6,5},["from"]={-2.76,2.83},["id"]="update-pool-arrow-3",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={-1.56,2.83},["width"]=1.6}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-4",["layer"]=50,["point"]={-0.09,2.83},["role"]="text",["size"]=23,["text"]="mpool->cell(tid)"}
refs[6] = scene:arrow {["dash"]={6,5},["from"]={1.47,2.83},["id"]="update-pool-arrow-5",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.52,2.83},["width"]=1.6}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-6",["layer"]=50,["point"]={4,2.83},["role"]="text",["size"]=23,["text"]="cellPools[tid]"}
refs[8] = scene:group {["id"]="update-pool-group-7"}
refs[9] = refs[8]:line {["from"]={-5.42,1.85},["id"]="update-pool-line-8",["layer"]=25,["stroke"]="#cccccc",["to"]={-5.42,-1.21},["width"]=1}
refs[10] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-9",["layer"]=50,["point"]={-5.42,2.05},["role"]="text",["size"]=16,["text"]="0"}
refs[11] = refs[8]:line {["from"]={-4.91,1.85},["id"]="update-pool-line-10",["layer"]=25,["stroke"]="#cccccc",["to"]={-4.91,-1.21},["width"]=1}
refs[12] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-11",["layer"]=50,["point"]={-4.91,2.05},["role"]="text",["size"]=16,["text"]="1"}
refs[13] = refs[8]:line {["from"]={-4.4,1.85},["id"]="update-pool-line-12",["layer"]=25,["stroke"]="#cccccc",["to"]={-4.4,-1.21},["width"]=1}
refs[14] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-13",["layer"]=50,["point"]={-4.4,2.05},["role"]="text",["size"]=16,["text"]="2"}
refs[15] = refs[8]:line {["from"]={-3.89,1.85},["id"]="update-pool-line-14",["layer"]=25,["stroke"]="#cccccc",["to"]={-3.89,-1.21},["width"]=1}
refs[16] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-15",["layer"]=50,["point"]={-3.89,2.05},["role"]="text",["size"]=16,["text"]="3"}
refs[17] = refs[8]:line {["from"]={-3.38,1.85},["id"]="update-pool-line-16",["layer"]=25,["stroke"]="#cccccc",["to"]={-3.38,-1.21},["width"]=1}
refs[18] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-17",["layer"]=50,["point"]={-3.38,2.05},["role"]="text",["size"]=16,["text"]="4"}
refs[19] = refs[8]:line {["from"]={-2.87,1.85},["id"]="update-pool-line-18",["layer"]=25,["stroke"]="#cccccc",["to"]={-2.87,-1.21},["width"]=1}
refs[20] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-19",["layer"]=50,["point"]={-2.87,2.05},["role"]="text",["size"]=16,["text"]="5"}
refs[21] = refs[8]:line {["from"]={-2.36,1.85},["id"]="update-pool-line-20",["layer"]=25,["stroke"]="#cccccc",["to"]={-2.36,-1.21},["width"]=1}
refs[22] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-21",["layer"]=50,["point"]={-2.36,2.05},["role"]="text",["size"]=16,["text"]="6"}
refs[23] = refs[8]:line {["from"]={-1.85,1.85},["id"]="update-pool-line-22",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,-1.21},["width"]=1}
refs[24] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-23",["layer"]=50,["point"]={-1.85,2.05},["role"]="text",["size"]=16,["text"]="7"}
refs[25] = refs[8]:line {["from"]={-5.42,1.85},["id"]="update-pool-line-24",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,1.85},["width"]=1}
refs[26] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-25",["layer"]=50,["point"]={-5.64,1.85},["role"]="text",["size"]=16,["text"]="0"}
refs[27] = refs[8]:line {["from"]={-5.42,1.34},["id"]="update-pool-line-26",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,1.34},["width"]=1}
refs[28] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-27",["layer"]=50,["point"]={-5.64,1.34},["role"]="text",["size"]=16,["text"]="1"}
refs[29] = refs[8]:line {["from"]={-5.42,0.83},["id"]="update-pool-line-28",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,0.83},["width"]=1}
refs[30] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-29",["layer"]=50,["point"]={-5.64,0.83},["role"]="text",["size"]=16,["text"]="2"}
refs[31] = refs[8]:line {["from"]={-5.42,0.32},["id"]="update-pool-line-30",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,0.32},["width"]=1}
refs[32] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-31",["layer"]=50,["point"]={-5.64,0.32},["role"]="text",["size"]=16,["text"]="3"}
refs[33] = refs[8]:line {["from"]={-5.42,-0.19},["id"]="update-pool-line-32",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,-0.19},["width"]=1}
refs[34] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-33",["layer"]=50,["point"]={-5.64,-0.19},["role"]="text",["size"]=16,["text"]="4"}
refs[35] = refs[8]:line {["from"]={-5.42,-0.7},["id"]="update-pool-line-34",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,-0.7},["width"]=1}
refs[36] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-35",["layer"]=50,["point"]={-5.64,-0.7},["role"]="text",["size"]=16,["text"]="5"}
refs[37] = refs[8]:line {["from"]={-5.42,-1.21},["id"]="update-pool-line-36",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.85,-1.21},["width"]=1}
refs[38] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-37",["layer"]=50,["point"]={-5.64,-1.21},["role"]="text",["size"]=16,["text"]="6"}
refs[39] = refs[8]:path {["commands"]={{["to"]={-4.7825,1.2125},["type"]="move"},{["to"]={-4.7825,-0.3175},["type"]="line"},{["control1"]={-3.89,-0.8275},["control2"]={-2.4875,-0.3175},["to"]={-2.7425,0.9575},["type"]="cubic"},{["type"]="close"}},["fill"]="#df792b12",["id"]="update-pool-outline-38",["layer"]=20,["stroke"]="#202020",["width"]=2.2}
refs[40] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-39",["layer"]=50,["point"]={-3.63,2.38},["role"]="text",["size"]=23,["text"]="Outline"}
refs[41] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-40",["layer"]=50,["point"]={2.36,2.06},["role"]="text",["size"]=24,["text"]="Temporary · same buffer"}
refs[42] = scene:rectangle {["center"]={2.36,0.775},["fill"]="#ffffff",["id"]="update-pool-rect-41",["layer"]=10,["size"]={6.24,0.93},["stroke"]="#202020",["width"]=1.8}
refs[43] = scene:group {["id"]="update-pool-group-42"}
refs[44] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-43",["layer"]=50,["point"]={2.32,-0.88},["role"]="text",["size"]=25,["text"]="SwRle::spans"}
refs[45] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-44",["layer"]=50,["point"]={-0.59,-1.48},["role"]="text",["size"]=17,["text"]="y 1"}
refs[46] = refs[43]:rectangle {["center"]={2.065,-1.48},["fill"]="#ffffff",["id"]="update-pool-rect-45",["layer"]=10,["size"]={4.69,0.33},["stroke"]="#cccccc",["width"]=1}
refs[47] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-46",["layer"]=50,["point"]={-0.59,-1.85},["role"]="text",["size"]=17,["text"]="y 2"}
refs[48] = refs[43]:rectangle {["center"]={2.065,-1.85},["fill"]="#ffffff",["id"]="update-pool-rect-47",["layer"]=10,["size"]={4.69,0.33},["stroke"]="#cccccc",["width"]=1}
refs[49] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-48",["layer"]=50,["point"]={-0.59,-2.22},["role"]="text",["size"]=17,["text"]="y 3"}
refs[50] = refs[43]:rectangle {["center"]={2.065,-2.22},["fill"]="#ffffff",["id"]="update-pool-rect-49",["layer"]=10,["size"]={4.69,0.33},["stroke"]="#cccccc",["width"]=1}
refs[51] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-50",["layer"]=50,["point"]={-0.59,-2.59},["role"]="text",["size"]=17,["text"]="y 4"}
refs[52] = refs[43]:rectangle {["center"]={2.065,-2.59},["fill"]="#ffffff",["id"]="update-pool-rect-51",["layer"]=10,["size"]={4.69,0.33},["stroke"]="#cccccc",["width"]=1}
refs[53] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-52",["layer"]=50,["point"]={2.31,-3.26},["role"]="text",["size"]=23,["text"]="Retained for Draw/Raster"}
refs[54] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-53",["layer"]=50,["point"]={-3.61,-2.66},["role"]="text",["size"]=22,["text"]="Reduced pool · 192 B"}
refs[55] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-54",["layer"]=50,["point"]={-3.61,-3.04},["role"]="text",["size"]=20,["text"]="Default · 16,368 B"}
refs[56] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-55",["layer"]=50,["point"]={2.36,1.62},["role"]="text",["size"]=20,["text"]="bbox sizing → band allocation"}
scene:wait(1.1)
scene:fade_in(refs[43],{["curve"]="ease_out",["duration"]=0.45,["scale"]=1,["shift"]={0,0,0}})
refs[57] = scene:group {["id"]="update-pool-group-56"}
refs[58] = scene:group {["id"]="update-pool-group-57"}
refs[59] = scene:group {["id"]="update-pool-group-58"}
refs[60] = refs[58]:rectangle {["center"]={-3.635,0.32},["fill"]="#20202009",["id"]="update-pool-rect-59",["layer"]=15,["size"]={3.57,2.04},["stroke"]="#202020",["width"]=2}
refs[61] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-60",["layer"]=50,["point"]={-3.61,-1.63},["role"]="text",["size"]=25,["text"]="Band [1, 5)"}
refs[62] = refs[57]:rectangle {["center"]={-0.63,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-61",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[63] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-62",["layer"]=50,["point"]={-0.63,0.775},["role"]="text",["size"]=16,["text"]="0"}
refs[64] = refs[57]:rectangle {["center"]={-0.37,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-63",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[65] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-64",["layer"]=50,["point"]={-0.37,0.775},["role"]="text",["size"]=16,["text"]="1"}
refs[66] = refs[57]:rectangle {["center"]={-0.11,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-65",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[67] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-66",["layer"]=50,["point"]={-0.11,0.775},["role"]="text",["size"]=16,["text"]="2"}
refs[68] = refs[57]:rectangle {["center"]={0.15,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-67",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[69] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-68",["layer"]=50,["point"]={0.15,0.775},["role"]="text",["size"]=16,["text"]="3"}
refs[70] = refs[57]:rectangle {["center"]={0.54,0.775},["fill"]="#eeeeee",["id"]="update-pool-rect-69",["layer"]=16,["size"]={0.52,0.93},["stroke"]="#ffffff",["width"]=1}
refs[71] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-70",["layer"]=50,["point"]={0.02,0.05},["role"]="text",["size"]=18,["text"]="yCells[4]"}
refs[72] = refs[57]:rectangle {["center"]={1.19,0.775},["fill"]="#00000000",["id"]="update-pool-rect-71",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[73] = refs[57]:rectangle {["center"]={1.97,0.775},["fill"]="#00000000",["id"]="update-pool-rect-72",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[74] = refs[57]:rectangle {["center"]={2.75,0.775},["fill"]="#00000000",["id"]="update-pool-rect-73",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[75] = refs[57]:rectangle {["center"]={3.53,0.775},["fill"]="#00000000",["id"]="update-pool-rect-74",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[76] = refs[57]:rectangle {["center"]={4.31,0.775},["fill"]="#00000000",["id"]="update-pool-rect-75",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[77] = refs[57]:rectangle {["center"]={5.09,0.775},["fill"]="#00000000",["id"]="update-pool-rect-76",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[78] = refs[57]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-77",["layer"]=50,["point"]={3.14,0.05},["role"]="text",["size"]=19,["text"]="6 cells · world (x,y)"}
scene:fade_in(refs[57],{["curve"]="ease_out",["duration"]=0.45,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[58],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
refs[79] = scene:group {["id"]="update-pool-group-78"}
refs[80] = refs[79]:rectangle {["center"]={-4.655,1.085},["fill"]="#df792b36",["id"]="update-pool-rect-79",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[79],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[79],shift={5.845,-0.31}}},0.32,"linear",0)
refs[81] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-80",["layer"]=50,["point"]={1.19,0.775},["role"]="text",["size"]=18,["text"]="1,1"}
scene:fade_in(refs[81],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[82] = scene:group {["id"]="update-pool-group-81"}
refs[83] = refs[82]:rectangle {["center"]={-4.655,0.575},["fill"]="#df792b36",["id"]="update-pool-rect-82",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[82],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[82],shift={6.625,0.2}}},0.32,"linear",0)
refs[84] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-83",["layer"]=50,["point"]={1.97,0.775},["role"]="text",["size"]=18,["text"]="1,2"}
scene:fade_in(refs[84],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[85] = scene:group {["id"]="update-pool-group-84"}
refs[86] = refs[85]:rectangle {["center"]={-4.655,0.065},["fill"]="#df792b36",["id"]="update-pool-rect-85",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[85],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[85],shift={7.405,0.71}}},0.32,"linear",0)
refs[87] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-86",["layer"]=50,["point"]={2.75,0.775},["role"]="text",["size"]=18,["text"]="1,3"}
scene:fade_in(refs[87],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[88] = scene:group {["id"]="update-pool-group-87"}
refs[89] = refs[88]:rectangle {["center"]={-4.655,-0.445},["fill"]="#df792b36",["id"]="update-pool-rect-88",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[88],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[88],shift={8.185,1.22}}},0.32,"linear",0)
refs[90] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-89",["layer"]=50,["point"]={3.53,0.775},["role"]="text",["size"]=18,["text"]="1,4"}
scene:fade_in(refs[90],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[91] = scene:group {["id"]="update-pool-group-90"}
refs[92] = refs[91]:rectangle {["center"]={-4.145,-0.445},["fill"]="#df792b36",["id"]="update-pool-rect-91",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[91],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[91],shift={8.455,1.22}}},0.32,"linear",0)
refs[93] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-92",["layer"]=50,["point"]={4.31,0.775},["role"]="text",["size"]=18,["text"]="2,4"}
scene:fade_in(refs[93],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[94] = scene:group {["id"]="update-pool-group-93"}
refs[95] = refs[94]:rectangle {["center"]={-3.635,-0.445},["fill"]="#3f7cce36",["id"]="update-pool-rect-94",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[94],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[94],shift={8.725,1.22}}},0.32,"linear",0)
refs[96] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-95",["layer"]=50,["point"]={5.09,0.775},["role"]="text",["size"]=18,["text"]="3,4"}
scene:fade_in(refs[96],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[97] = refs[59]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-96",["layer"]=50,["point"]={2.35,-0.34},["role"]="text",["size"]=26,["text"]="Pool full"}
scene:fade_in(refs[59],{["curve"]="ease_out",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.2)
refs[98] = scene:group {["id"]="update-pool-group-97"}
refs[99] = refs[98]:line {["dash"]={7,5},["from"]={-5.42,0.32},["id"]="update-pool-line-98",["layer"]=25,["stroke"]="#202020",["to"]={-1.85,0.32},["width"]=3}
refs[100] = refs[98]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-99",["layer"]=50,["point"]={-3.61,-2.14},["role"]="text",["size"]=24,["text"]="split → retry"}
scene:fade_in(refs[98],{["curve"]="ease_out",["duration"]=0.5,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_out(refs[98],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[79],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[81],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[82],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[84],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[85],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[87],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[88],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[90],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[91],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[93],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[94],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[96],{["curve"]="ease_in",["duration"]=0.08,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[57],{["curve"]="ease_in",["duration"]=0.55,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[58],{["curve"]="ease_in",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[59],{["curve"]="ease_in",["duration"]=0.2,["scale"]=1,["shift"]={0,0,0}})
refs[101] = scene:group {["id"]="update-pool-group-100"}
refs[102] = scene:group {["id"]="update-pool-group-101"}
refs[103] = scene:group {["id"]="update-pool-group-102"}
refs[104] = refs[102]:rectangle {["center"]={-3.635,0.83},["fill"]="#20202009",["id"]="update-pool-rect-103",["layer"]=15,["size"]={3.57,1.02},["stroke"]="#202020",["width"]=2}
refs[105] = refs[102]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-104",["layer"]=50,["point"]={-3.61,-1.63},["role"]="text",["size"]=25,["text"]="Band [1, 3)"}
refs[106] = refs[101]:rectangle {["center"]={-0.63,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-105",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[107] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-106",["layer"]=50,["point"]={-0.63,0.775},["role"]="text",["size"]=16,["text"]="0"}
refs[108] = refs[101]:rectangle {["center"]={-0.37,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-107",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[109] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-108",["layer"]=50,["point"]={-0.37,0.775},["role"]="text",["size"]=16,["text"]="1"}
refs[110] = refs[101]:rectangle {["center"]={-0.11,0.775},["fill"]="#eeeeee",["id"]="update-pool-rect-109",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[111] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-110",["layer"]=50,["point"]={-0.37,0.05},["role"]="text",["size"]=18,["text"]="yCells[2]"}
refs[112] = refs[101]:rectangle {["center"]={0.41,0.775},["fill"]="#00000000",["id"]="update-pool-rect-111",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[113] = refs[101]:rectangle {["center"]={1.19,0.775},["fill"]="#00000000",["id"]="update-pool-rect-112",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[114] = refs[101]:rectangle {["center"]={1.97,0.775},["fill"]="#00000000",["id"]="update-pool-rect-113",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[115] = refs[101]:rectangle {["center"]={2.75,0.775},["fill"]="#00000000",["id"]="update-pool-rect-114",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[116] = refs[101]:rectangle {["center"]={3.53,0.775},["fill"]="#00000000",["id"]="update-pool-rect-115",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[117] = refs[101]:rectangle {["center"]={4.31,0.775},["fill"]="#00000000",["id"]="update-pool-rect-116",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[118] = refs[101]:rectangle {["center"]={5.09,0.775},["fill"]="#00000000",["id"]="update-pool-rect-117",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[119] = refs[101]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-118",["layer"]=50,["point"]={2.75,0.05},["role"]="text",["size"]=19,["text"]="7 cells · world (x,y)"}
scene:fade_in(refs[101],{["curve"]="ease_out",["duration"]=0.45,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[102],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
refs[120] = scene:group {["id"]="update-pool-group-119"}
refs[121] = refs[120]:rectangle {["center"]={-4.655,1.085},["fill"]="#df792b36",["id"]="update-pool-rect-120",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[120],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[120],shift={5.065,-0.31}}},0.2,"linear",0)
refs[122] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-121",["layer"]=50,["point"]={0.41,0.775},["role"]="text",["size"]=18,["text"]="1,1"}
scene:fade_in(refs[122],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[123] = scene:group {["id"]="update-pool-group-122"}
refs[124] = refs[123]:rectangle {["center"]={-4.655,0.575},["fill"]="#df792b36",["id"]="update-pool-rect-123",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[123],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[123],shift={5.845,0.2}}},0.2,"linear",0)
refs[125] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-124",["layer"]=50,["point"]={1.19,0.775},["role"]="text",["size"]=18,["text"]="1,2"}
scene:fade_in(refs[125],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[126] = scene:group {["id"]="update-pool-group-125"}
refs[127] = refs[126]:rectangle {["center"]={-2.615,0.575},["fill"]="#3f7cce36",["id"]="update-pool-rect-126",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[126],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[126],shift={4.585,0.2}}},0.2,"linear",0)
refs[128] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-127",["layer"]=50,["point"]={1.97,0.775},["role"]="text",["size"]=18,["text"]="5,2"}
scene:fade_in(refs[128],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[129] = scene:group {["id"]="update-pool-group-128"}
refs[130] = refs[129]:rectangle {["center"]={-2.615,1.085},["fill"]="#3f7cce36",["id"]="update-pool-rect-129",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[129],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[129],shift={5.365,-0.31}}},0.2,"linear",0)
refs[131] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-130",["layer"]=50,["point"]={2.75,0.775},["role"]="text",["size"]=18,["text"]="5,1"}
scene:fade_in(refs[131],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[132] = scene:group {["id"]="update-pool-group-131"}
refs[133] = refs[132]:rectangle {["center"]={-3.125,1.085},["fill"]="#3f7cce36",["id"]="update-pool-rect-132",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[132],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[132],shift={6.655,-0.31}}},0.2,"linear",0)
refs[134] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-133",["layer"]=50,["point"]={3.53,0.775},["role"]="text",["size"]=18,["text"]="4,1"}
scene:fade_in(refs[134],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[135] = scene:group {["id"]="update-pool-group-134"}
refs[136] = refs[135]:rectangle {["center"]={-3.635,1.085},["fill"]="#3f7cce36",["id"]="update-pool-rect-135",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[135],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[135],shift={7.945,-0.31}}},0.2,"linear",0)
refs[137] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-136",["layer"]=50,["point"]={4.31,0.775},["role"]="text",["size"]=18,["text"]="3,1"}
scene:fade_in(refs[137],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[138] = scene:group {["id"]="update-pool-group-137"}
refs[139] = refs[138]:rectangle {["center"]={-4.145,1.085},["fill"]="#3f7cce36",["id"]="update-pool-rect-138",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[138],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[138],shift={9.235,-0.31}}},0.2,"linear",0)
refs[140] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-139",["layer"]=50,["point"]={5.09,0.775},["role"]="text",["size"]=18,["text"]="2,1"}
scene:fade_in(refs[140],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[141] = refs[103]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-140",["layer"]=50,["point"]={2.35,-0.34},["role"]="text",["size"]=25,["text"]="_sweep() → 8 spans"}
scene:fade_in(refs[103],{["curve"]="ease_out",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
refs[142] = scene:rectangle {["center"]={0.725,-1.48},["fill"]="#838383",["id"]="update-pool-rect-141",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[142],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[143] = scene:rectangle {["center"]={1.395,-1.48},["fill"]="#747474",["id"]="update-pool-rect-142",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[143],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[144] = scene:rectangle {["center"]={2.065,-1.48},["fill"]="#8e8e8e",["id"]="update-pool-rect-143",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[144],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[145] = scene:rectangle {["center"]={2.735,-1.48},["fill"]="#a9a9a9",["id"]="update-pool-rect-144",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[145],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[146] = scene:rectangle {["center"]={3.405,-1.48},["fill"]="#e4e4e4",["id"]="update-pool-rect-145",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[146],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[147] = scene:rectangle {["center"]={0.725,-1.85},["fill"]="#545454",["id"]="update-pool-rect-146",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[147],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[148] = scene:rectangle {["center"]={2.065,-1.85},["fill"]="#202020",["id"]="update-pool-rect-147",["layer"]=25,["size"]={1.99,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[148],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[149] = scene:rectangle {["center"]={3.405,-1.85},["fill"]="#bcbcbc",["id"]="update-pool-rect-148",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[149],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_out(refs[120],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[122],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[123],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[125],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[126],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[128],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[129],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[131],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[132],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[134],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[135],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[137],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[138],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[140],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[101],{["curve"]="ease_in",["duration"]=0.55,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[102],{["curve"]="ease_in",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[103],{["curve"]="ease_in",["duration"]=0.2,["scale"]=1,["shift"]={0,0,0}})
refs[150] = scene:group {["id"]="update-pool-group-149"}
refs[151] = scene:group {["id"]="update-pool-group-150"}
refs[152] = scene:group {["id"]="update-pool-group-151"}
refs[153] = refs[151]:rectangle {["center"]={-3.635,-0.19},["fill"]="#20202009",["id"]="update-pool-rect-152",["layer"]=15,["size"]={3.57,1.02},["stroke"]="#202020",["width"]=2}
refs[154] = refs[151]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-153",["layer"]=50,["point"]={-3.61,-1.63},["role"]="text",["size"]=25,["text"]="Band [3, 5)"}
refs[155] = refs[150]:rectangle {["center"]={-0.63,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-154",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[156] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-155",["layer"]=50,["point"]={-0.63,0.775},["role"]="text",["size"]=16,["text"]="0"}
refs[157] = refs[150]:rectangle {["center"]={-0.37,0.775},["fill"]="#dddddd",["id"]="update-pool-rect-156",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[158] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-157",["layer"]=50,["point"]={-0.37,0.775},["role"]="text",["size"]=16,["text"]="1"}
refs[159] = refs[150]:rectangle {["center"]={-0.11,0.775},["fill"]="#eeeeee",["id"]="update-pool-rect-158",["layer"]=16,["size"]={0.26,0.93},["stroke"]="#ffffff",["width"]=1}
refs[160] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-159",["layer"]=50,["point"]={-0.37,0.05},["role"]="text",["size"]=18,["text"]="yCells[2]"}
refs[161] = refs[150]:rectangle {["center"]={0.41,0.775},["fill"]="#00000000",["id"]="update-pool-rect-160",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[162] = refs[150]:rectangle {["center"]={1.19,0.775},["fill"]="#00000000",["id"]="update-pool-rect-161",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[163] = refs[150]:rectangle {["center"]={1.97,0.775},["fill"]="#00000000",["id"]="update-pool-rect-162",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[164] = refs[150]:rectangle {["center"]={2.75,0.775},["fill"]="#00000000",["id"]="update-pool-rect-163",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[165] = refs[150]:rectangle {["center"]={3.53,0.775},["fill"]="#00000000",["id"]="update-pool-rect-164",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[166] = refs[150]:rectangle {["center"]={4.31,0.775},["fill"]="#00000000",["id"]="update-pool-rect-165",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[167] = refs[150]:rectangle {["center"]={5.09,0.775},["fill"]="#00000000",["id"]="update-pool-rect-166",["layer"]=17,["size"]={0.78,0.93},["stroke"]="#cccccc",["width"]=1.2}
refs[168] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-167",["layer"]=50,["point"]={2.75,0.05},["role"]="text",["size"]=19,["text"]="7 cells · world (x,y)"}
scene:fade_in(refs[150],{["curve"]="ease_out",["duration"]=0.45,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[151],{["curve"]="ease_out",["duration"]=0.4,["scale"]=1,["shift"]={0,0,0}})
refs[169] = scene:group {["id"]="update-pool-group-168"}
refs[170] = refs[169]:rectangle {["center"]={-4.655,0.065},["fill"]="#df792b36",["id"]="update-pool-rect-169",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[169],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[169],shift={5.065,0.71}}},0.2,"linear",0)
refs[171] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-170",["layer"]=50,["point"]={0.41,0.775},["role"]="text",["size"]=18,["text"]="1,3"}
scene:fade_in(refs[171],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[172] = scene:group {["id"]="update-pool-group-171"}
refs[173] = refs[172]:rectangle {["center"]={-4.655,-0.445},["fill"]="#df792b36",["id"]="update-pool-rect-172",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[172],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[172],shift={5.845,1.22}}},0.2,"linear",0)
refs[174] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-173",["layer"]=50,["point"]={1.19,0.775},["role"]="text",["size"]=18,["text"]="1,4"}
scene:fade_in(refs[174],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[175] = scene:group {["id"]="update-pool-group-174"}
refs[176] = refs[175]:rectangle {["center"]={-4.145,-0.445},["fill"]="#df792b36",["id"]="update-pool-rect-175",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#df792b",["width"]=1.6}
scene:fade_in(refs[175],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[175],shift={6.115,1.22}}},0.2,"linear",0)
refs[177] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-176",["layer"]=50,["point"]={1.97,0.775},["role"]="text",["size"]=18,["text"]="2,4"}
scene:fade_in(refs[177],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[178] = scene:group {["id"]="update-pool-group-177"}
refs[179] = refs[178]:rectangle {["center"]={-3.635,-0.445},["fill"]="#3f7cce36",["id"]="update-pool-rect-178",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[178],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[178],shift={6.385,1.22}}},0.2,"linear",0)
refs[180] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-179",["layer"]=50,["point"]={2.75,0.775},["role"]="text",["size"]=18,["text"]="3,4"}
scene:fade_in(refs[180],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[181] = scene:group {["id"]="update-pool-group-180"}
refs[182] = refs[181]:rectangle {["center"]={-3.125,-0.445},["fill"]="#3f7cce36",["id"]="update-pool-rect-181",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[181],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[181],shift={6.655,1.22}}},0.2,"linear",0)
refs[183] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-182",["layer"]=50,["point"]={3.53,0.775},["role"]="text",["size"]=18,["text"]="4,4"}
scene:fade_in(refs[183],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[184] = scene:group {["id"]="update-pool-group-183"}
refs[185] = refs[184]:rectangle {["center"]={-3.125,0.065},["fill"]="#3f7cce36",["id"]="update-pool-rect-184",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[184],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[184],shift={7.435,0.71}}},0.2,"linear",0)
refs[186] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-185",["layer"]=50,["point"]={4.31,0.775},["role"]="text",["size"]=18,["text"]="4,3"}
scene:fade_in(refs[186],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[187] = scene:group {["id"]="update-pool-group-186"}
refs[188] = refs[187]:rectangle {["center"]={-2.615,0.065},["fill"]="#3f7cce36",["id"]="update-pool-rect-187",["layer"]=33,["size"]={0.74,0.85},["stroke"]="#3f7cce",["width"]=1.6}
scene:fade_in(refs[187],{["curve"]="ease_out",["duration"]=0.05,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[187],shift={7.705,0.71}}},0.2,"linear",0)
refs[189] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-188",["layer"]=50,["point"]={5.09,0.775},["role"]="text",["size"]=18,["text"]="5,3"}
scene:fade_in(refs[189],{["curve"]="ease_out",["duration"]=0.04,["scale"]=1,["shift"]={0,0,0}})
refs[190] = refs[152]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-189",["layer"]=50,["point"]={2.35,-0.34},["role"]="text",["size"]=25,["text"]="_sweep() → 8 spans"}
scene:fade_in(refs[152],{["curve"]="ease_out",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
refs[191] = scene:rectangle {["center"]={0.725,-2.22},["fill"]="#545454",["id"]="update-pool-rect-190",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[191],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[192] = scene:rectangle {["center"]={1.73,-2.22},["fill"]="#202020",["id"]="update-pool-rect-191",["layer"]=25,["size"]={1.32,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[192],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[193] = scene:rectangle {["center"]={2.735,-2.22},["fill"]="#444444",["id"]="update-pool-rect-192",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[193],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[194] = scene:rectangle {["center"]={3.405,-2.22},["fill"]="#e8e8e8",["id"]="update-pool-rect-193",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[194],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[195] = scene:rectangle {["center"]={0.725,-2.59},["fill"]="#bbbbbb",["id"]="update-pool-rect-194",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[195],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[196] = scene:rectangle {["center"]={1.395,-2.59},["fill"]="#7d7d7d",["id"]="update-pool-rect-195",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[196],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[197] = scene:rectangle {["center"]={2.065,-2.59},["fill"]="#949494",["id"]="update-pool-rect-196",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[197],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
refs[198] = scene:rectangle {["center"]={2.735,-2.59},["fill"]="#e2e2e2",["id"]="update-pool-rect-197",["layer"]=25,["size"]={0.65,0.32},["stroke"]="#ffffff",["width"]=1}
scene:fade_in(refs[198],{["curve"]="ease_out",["duration"]=0.1,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1.1)
scene:fade_out(refs[169],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[171],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[172],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[174],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[175],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[177],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[178],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[180],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[181],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[183],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[184],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[186],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[187],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[189],{["curve"]="ease_in",["duration"]=0.045,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[150],{["curve"]="ease_in",["duration"]=0.55,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[151],{["curve"]="ease_in",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[152],{["curve"]="ease_in",["duration"]=0.2,["scale"]=1,["shift"]={0,0,0}})
refs[199] = scene:group {["id"]="update-pool-group-198"}
refs[200] = refs[199]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-199",["layer"]=50,["point"]={2.36,0.79},["role"]="text",["size"]=26,["text"]="Next task → reuse buffer"}
refs[201] = refs[199]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-200",["layer"]=50,["point"]={2.36,-0.34},["role"]="text",["size"]=29,["text"]="16 spans retained"}
refs[202] = refs[199]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-pool-text-201",["layer"]=50,["point"]={-3.61,-1.83},["role"]="text",["size"]=24,["text"]="[1, 3) + [3, 5)"}
refs[203] = refs[199]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-pool-text-202",["layer"]=50,["point"]={-3.61,-2.24},["role"]="text",["size"]=21,["text"]="Same coverage as the full pool"}
scene:fade_in(refs[199],{["curve"]="ease_out",["duration"]=0.5,["scale"]=1,["shift"]={0,0,0}})
scene:wait(2)
return scene
