-- Generated by scripts/render-update-scenes.mjs; edit rle.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=8,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=800,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1200}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-0",["layer"]=50,["point"]={0,3.58},["role"]="text",["size"]=30,["text"]="Cells → coverage → RLE spans"}
refs[2] = scene:line {["from"]={-5.55,3.2},["id"]="update-sweep-line-1",["layer"]=25,["stroke"]="#cccccc",["to"]={5.55,3.2},["width"]=1}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-2",["layer"]=50,["point"]={-4.25,2.81},["role"]="text",["size"]=24,["text"]="_sweep()"}
refs[4] = scene:arrow {["dash"]={6,5},["from"]={-3.42,2.81},["id"]="update-sweep-arrow-3",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={-2.2,2.81},["width"]=1.6}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-4",["layer"]=50,["point"]={-1,2.81},["role"]="text",["size"]=24,["text"]="_horizLine()"}
refs[6] = scene:arrow {["dash"]={6,5},["from"]={0.1,2.81},["id"]="update-sweep-arrow-5",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={1.44,2.81},["width"]=1.6}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-6",["layer"]=50,["point"]={3.2,2.81},["role"]="text",["size"]=24,["text"]="SwRle::spans"}
refs[8] = scene:group {["id"]="update-sweep-group-7"}
refs[9] = refs[8]:line {["from"]={-5.35,2.19},["id"]="update-sweep-line-8",["layer"]=25,["stroke"]="#cccccc",["to"]={-5.35,-1.59},["width"]=1}
refs[10] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-9",["layer"]=50,["point"]={-5.35,2.39},["role"]="text",["size"]=16,["text"]="0"}
refs[11] = refs[8]:line {["from"]={-4.72,2.19},["id"]="update-sweep-line-10",["layer"]=25,["stroke"]="#cccccc",["to"]={-4.72,-1.59},["width"]=1}
refs[12] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-11",["layer"]=50,["point"]={-4.72,2.39},["role"]="text",["size"]=16,["text"]="1"}
refs[13] = refs[8]:line {["from"]={-4.09,2.19},["id"]="update-sweep-line-12",["layer"]=25,["stroke"]="#cccccc",["to"]={-4.09,-1.59},["width"]=1}
refs[14] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-13",["layer"]=50,["point"]={-4.09,2.39},["role"]="text",["size"]=16,["text"]="2"}
refs[15] = refs[8]:line {["from"]={-3.46,2.19},["id"]="update-sweep-line-14",["layer"]=25,["stroke"]="#cccccc",["to"]={-3.46,-1.59},["width"]=1}
refs[16] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-15",["layer"]=50,["point"]={-3.46,2.39},["role"]="text",["size"]=16,["text"]="3"}
refs[17] = refs[8]:line {["from"]={-2.83,2.19},["id"]="update-sweep-line-16",["layer"]=25,["stroke"]="#cccccc",["to"]={-2.83,-1.59},["width"]=1}
refs[18] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-17",["layer"]=50,["point"]={-2.83,2.39},["role"]="text",["size"]=16,["text"]="4"}
refs[19] = refs[8]:line {["from"]={-2.2,2.19},["id"]="update-sweep-line-18",["layer"]=25,["stroke"]="#cccccc",["to"]={-2.2,-1.59},["width"]=1}
refs[20] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-19",["layer"]=50,["point"]={-2.2,2.39},["role"]="text",["size"]=16,["text"]="5"}
refs[21] = refs[8]:line {["from"]={-1.57,2.19},["id"]="update-sweep-line-20",["layer"]=25,["stroke"]="#cccccc",["to"]={-1.57,-1.59},["width"]=1}
refs[22] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-21",["layer"]=50,["point"]={-1.57,2.39},["role"]="text",["size"]=16,["text"]="6"}
refs[23] = refs[8]:line {["from"]={-0.94,2.19},["id"]="update-sweep-line-22",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,-1.59},["width"]=1}
refs[24] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-23",["layer"]=50,["point"]={-0.94,2.39},["role"]="text",["size"]=16,["text"]="7"}
refs[25] = refs[8]:line {["from"]={-5.35,2.19},["id"]="update-sweep-line-24",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,2.19},["width"]=1}
refs[26] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-25",["layer"]=50,["point"]={-5.57,2.19},["role"]="text",["size"]=16,["text"]="0"}
refs[27] = refs[8]:line {["from"]={-5.35,1.56},["id"]="update-sweep-line-26",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,1.56},["width"]=1}
refs[28] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-27",["layer"]=50,["point"]={-5.57,1.56},["role"]="text",["size"]=16,["text"]="1"}
refs[29] = refs[8]:line {["from"]={-5.35,0.93},["id"]="update-sweep-line-28",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,0.93},["width"]=1}
refs[30] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-29",["layer"]=50,["point"]={-5.57,0.93},["role"]="text",["size"]=16,["text"]="2"}
refs[31] = refs[8]:line {["from"]={-5.35,0.3},["id"]="update-sweep-line-30",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,0.3},["width"]=1}
refs[32] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-31",["layer"]=50,["point"]={-5.57,0.3},["role"]="text",["size"]=16,["text"]="3"}
refs[33] = refs[8]:line {["from"]={-5.35,-0.33},["id"]="update-sweep-line-32",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,-0.33},["width"]=1}
refs[34] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-33",["layer"]=50,["point"]={-5.57,-0.33},["role"]="text",["size"]=16,["text"]="4"}
refs[35] = refs[8]:line {["from"]={-5.35,-0.96},["id"]="update-sweep-line-34",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,-0.96},["width"]=1}
refs[36] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-35",["layer"]=50,["point"]={-5.57,-0.96},["role"]="text",["size"]=16,["text"]="5"}
refs[37] = refs[8]:line {["from"]={-5.35,-1.59},["id"]="update-sweep-line-36",["layer"]=25,["stroke"]="#cccccc",["to"]={-0.94,-1.59},["width"]=1}
refs[38] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-37",["layer"]=50,["point"]={-5.57,-1.59},["role"]="text",["size"]=16,["text"]="6"}
refs[39] = refs[8]:path {["commands"]={{["to"]={-4.5625,1.4025},["type"]="move"},{["to"]={-4.5625,-0.4875},["type"]="line"},{["control1"]={-3.46,-1.1175},["control2"]={-1.7275,-0.4875},["to"]={-2.0425,1.0875},["type"]="cubic"},{["type"]="close"}},["fill"]="#df792b12",["id"]="update-sweep-outline-38",["layer"]=20,["stroke"]="#202020",["width"]=2.2}
refs[40] = scene:rectangle {["center"]={-4.405,0.615},["fill"]="#df792b25",["id"]="update-sweep-rect-39",["layer"]=17,["size"]={0.63,0.63},["stroke"]="#df792b",["width"]=2}
refs[41] = scene:rectangle {["center"]={-1.885,0.615},["fill"]="#3f7cce25",["id"]="update-sweep-rect-40",["layer"]=17,["size"]={0.63,0.63},["stroke"]="#3f7cce",["width"]=2}
refs[42] = scene:rectangle {["center"]={-4.405,-0.015},["fill"]="#df792b25",["id"]="update-sweep-rect-41",["layer"]=17,["size"]={0.63,0.63},["stroke"]="#df792b",["width"]=2}
refs[43] = scene:rectangle {["center"]={-2.515,-0.015},["fill"]="#3f7cce25",["id"]="update-sweep-rect-42",["layer"]=17,["size"]={0.63,0.63},["stroke"]="#3f7cce",["width"]=2}
refs[44] = scene:rectangle {["center"]={-1.885,-0.015},["fill"]="#3f7cce25",["id"]="update-sweep-rect-43",["layer"]=17,["size"]={0.63,0.63},["stroke"]="#3f7cce",["width"]=2}
refs[45] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-44",["layer"]=50,["point"]={-0.56,0.615},["role"]="text",["size"]=20,["text"]="y 2"}
refs[46] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-45",["layer"]=50,["point"]={-0.56,-0.015},["role"]="text",["size"]=20,["text"]="y 3"}
refs[47] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-46",["layer"]=50,["point"]={-3.02,-1.97},["role"]="text",["size"]=21,["text"]="cover = 0 at each row"}
refs[48] = scene:group {["id"]="update-sweep-group-47"}
refs[49] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-48",["layer"]=50,["point"]={-5.06,-2.63},["role"]="text",["size"]=23,["text"]="RLE"}
refs[50] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-49",["layer"]=50,["point"]={-4.71,-2.87},["role"]="text",["size"]=18,["text"]="y 2"}
refs[51] = refs[48]:rectangle {["center"]={-2.2,-2.87},["fill"]="#ffffff",["id"]="update-sweep-rect-50",["layer"]=10,["size"]={4.06,0.34},["stroke"]="#cccccc",["width"]=1}
refs[52] = refs[48]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-51",["layer"]=50,["point"]={-4.71,-3.26},["role"]="text",["size"]=18,["text"]="y 3"}
refs[53] = refs[48]:rectangle {["center"]={-2.2,-3.26},["fill"]="#ffffff",["id"]="update-sweep-rect-52",["layer"]=10,["size"]={4.06,0.34},["stroke"]="#cccccc",["width"]=1}
refs[54] = scene:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-53",["layer"]=50,["point"]={2.85,-2.87},["role"]="text",["size"]=21,["text"]="x · len · coverage"}
refs[55] = scene:group {["id"]="update-sweep-group-54"}
refs[56] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-55",["layer"]=50,["point"]={2.86,1.44},["role"]="text",["size"]=26,["text"]="Signed cover accumulates"}
refs[57] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-56",["layer"]=50,["point"]={2.05,0.71},["role"]="text",["size"]=24,["text"]="edge cell"}
refs[58] = refs[55]:rectangle {["center"]={4.29,0.71},["fill"]="#df792b55",["id"]="update-sweep-rect-57",["layer"]=15,["size"]={0.44,0.31},["stroke"]="#df792b",["width"]=1.4}
refs[59] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-58",["layer"]=50,["point"]={2.05,-0.04},["role"]="text",["size"]=24,["text"]="between cells"}
refs[60] = refs[55]:rectangle {["center"]={4.29,-0.04},["fill"]="#20202018",["id"]="update-sweep-rect-59",["layer"]=15,["size"]={1.5,0.31},["stroke"]="#202020",["width"]=1.4}
refs[61] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-60",["layer"]=50,["point"]={2.05,-0.79},["role"]="text",["size"]=24,["text"]="span"}
refs[62] = refs[55]:rectangle {["center"]={4.29,-0.79},["fill"]="#202020",["id"]="update-sweep-rect-61",["layer"]=15,["size"]={1.5,0.31},["stroke"]="#202020",["width"]=1.4}
refs[63] = refs[55]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-62",["layer"]=50,["point"]={2.86,-1.82},["role"]="text",["size"]=23,["text"]="No RGBA buffer yet"}
scene:wait(1.2)
scene:fade_out(refs[55],{["curve"]="ease_in",["duration"]=0.25,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[48],{["curve"]="ease_out",["duration"]=0.3,["scale"]=1,["shift"]={0,0,0}})
refs[64] = scene:group {["id"]="update-sweep-group-63"}
refs[65] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-sweep-text-64",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Cell · y 2 · x 1"}
refs[66] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-65",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[67] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-66",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="256"}
refs[68] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-67",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="0 + 256"}
refs[69] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-68",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="256 × 512 − (32768)"}
refs[70] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-69",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="98304"}
refs[71] = refs[64]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-70",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[72] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-71",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[73] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-72",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="192"}
refs[74] = refs[64]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-73",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="1 · 1 · 192"}
refs[75] = scene:rectangle {["center"]={-4.405,0.615},["fill"]="#00000000",["id"]="update-sweep-rect-74",["layer"]=35,["size"]={0.63,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[75],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[64],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[76] = scene:rectangle {["center"]={-4.405,0.615},["fill"]="#545454",["id"]="update-sweep-rect-75",["layer"]=28,["size"]={0.58,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[76],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[77] = scene:rectangle {["center"]={-4.405,0.615},["fill"]="#545454",["id"]="update-sweep-rect-76",["layer"]=38,["size"]={0.55,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[77],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[77],shift={1.045,-3.485}}},0.65,"linear",0)
refs[78] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-sweep-text-77",["layer"]=50,["point"]={-3.36,-2.87},["role"]="text",["size"]=17,["text"]="192"}
scene:fade_in(refs[78],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.9)
scene:fade_out(refs[64],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[75],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[79] = scene:group {["id"]="update-sweep-group-78"}
refs[80] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-79",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Gap · y 2 · x 2"}
refs[81] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-80",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[82] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-81",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="256"}
refs[83] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-82",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="carry 256"}
refs[84] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-83",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="256 × 512"}
refs[85] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-84",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="131072"}
refs[86] = refs[79]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-85",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[87] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-86",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[88] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-87",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="255"}
refs[89] = refs[79]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-88",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="2 · 3 · 255"}
refs[90] = scene:rectangle {["center"]={-3.145,0.615},["fill"]="#00000000",["id"]="update-sweep-rect-89",["layer"]=35,["size"]={1.89,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[90],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[79],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[91] = scene:rectangle {["center"]={-3.145,0.615},["fill"]="#202020",["id"]="update-sweep-rect-90",["layer"]=28,["size"]={1.84,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[91],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[92] = scene:rectangle {["center"]={-3.145,0.615},["fill"]="#202020",["id"]="update-sweep-rect-91",["layer"]=38,["size"]={1.71,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[92],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[92],shift={0.945,-3.485}}},0.65,"linear",0)
refs[93] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-sweep-text-92",["layer"]=50,["point"]={-2.2,-2.87},["role"]="text",["size"]=17,["text"]="255"}
scene:fade_in(refs[93],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.85)
scene:fade_out(refs[79],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[90],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[94] = scene:group {["id"]="update-sweep-group-93"}
refs[95] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-sweep-text-94",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Cell · y 2 · x 5"}
refs[96] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-95",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[97] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-96",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="0"}
refs[98] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-97",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="256 − 256"}
refs[99] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-98",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="0 × 512 − (-34273)"}
refs[100] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-99",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="34273"}
refs[101] = refs[94]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-100",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[102] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-101",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[103] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-102",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="66"}
refs[104] = refs[94]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-103",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="5 · 1 · 66"}
refs[105] = scene:rectangle {["center"]={-1.885,0.615},["fill"]="#00000000",["id"]="update-sweep-rect-104",["layer"]=35,["size"]={0.63,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[105],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[94],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[106] = scene:rectangle {["center"]={-1.885,0.615},["fill"]="#bcbcbc",["id"]="update-sweep-rect-105",["layer"]=28,["size"]={0.58,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[106],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[107] = scene:rectangle {["center"]={-1.885,0.615},["fill"]="#bcbcbc",["id"]="update-sweep-rect-106",["layer"]=38,["size"]={0.55,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[107],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[107],shift={0.845,-3.485}}},0.65,"linear",0)
refs[108] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-107",["layer"]=50,["point"]={-1.04,-2.87},["role"]="text",["size"]=17,["text"]="66"}
scene:fade_in(refs[108],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.45)
scene:fade_out(refs[94],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[105],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[109] = scene:group {["id"]="update-sweep-group-108"}
refs[110] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#df792b",["font"]="Pretendard",["id"]="update-sweep-text-109",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Cell · y 3 · x 1"}
refs[111] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-110",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[112] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-111",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="256"}
refs[113] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-112",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="0 + 256"}
refs[114] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-113",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="256 × 512 − (32768)"}
refs[115] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-114",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="98304"}
refs[116] = refs[109]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-115",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[117] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-116",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[118] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-117",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="192"}
refs[119] = refs[109]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-118",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="1 · 1 · 192"}
refs[120] = scene:rectangle {["center"]={-4.405,-0.015},["fill"]="#00000000",["id"]="update-sweep-rect-119",["layer"]=35,["size"]={0.63,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[120],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[109],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[121] = scene:rectangle {["center"]={-4.405,-0.015},["fill"]="#545454",["id"]="update-sweep-rect-120",["layer"]=28,["size"]={0.58,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[121],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[122] = scene:rectangle {["center"]={-4.405,-0.015},["fill"]="#545454",["id"]="update-sweep-rect-121",["layer"]=38,["size"]={0.55,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[122],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[122],shift={1.045,-3.245}}},0.65,"linear",0)
refs[123] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-sweep-text-122",["layer"]=50,["point"]={-3.36,-3.26},["role"]="text",["size"]=17,["text"]="192"}
scene:fade_in(refs[123],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.45)
scene:fade_out(refs[109],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[120],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[124] = scene:group {["id"]="update-sweep-group-123"}
refs[125] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-124",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Gap · y 3 · x 2"}
refs[126] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-125",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[127] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-126",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="256"}
refs[128] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-127",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="carry 256"}
refs[129] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-128",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="256 × 512"}
refs[130] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-129",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="131072"}
refs[131] = refs[124]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-130",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[132] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-131",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[133] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-132",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="255"}
refs[134] = refs[124]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-133",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="2 · 2 · 255"}
refs[135] = scene:rectangle {["center"]={-3.46,-0.015},["fill"]="#00000000",["id"]="update-sweep-rect-134",["layer"]=35,["size"]={1.26,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[135],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[124],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[136] = scene:rectangle {["center"]={-3.46,-0.015},["fill"]="#202020",["id"]="update-sweep-rect-135",["layer"]=28,["size"]={1.21,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[136],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[137] = scene:rectangle {["center"]={-3.46,-0.015},["fill"]="#202020",["id"]="update-sweep-rect-136",["layer"]=38,["size"]={1.13,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[137],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[137],shift={0.97,-3.245}}},0.65,"linear",0)
refs[138] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-sweep-text-137",["layer"]=50,["point"]={-2.49,-3.26},["role"]="text",["size"]=17,["text"]="255"}
scene:fade_in(refs[138],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.45)
scene:fade_out(refs[124],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[135],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[139] = scene:group {["id"]="update-sweep-group-138"}
refs[140] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-sweep-text-139",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Cell · y 3 · x 4"}
refs[141] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-140",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[142] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-141",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="106"}
refs[143] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-142",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="256 − 150"}
refs[144] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-143",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="106 × 512 − (-54000)"}
refs[145] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-144",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="108272"}
refs[146] = refs[139]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-145",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[147] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-146",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[148] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-147",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="211"}
refs[149] = refs[139]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-148",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="4 · 1 · 211"}
refs[150] = scene:rectangle {["center"]={-2.515,-0.015},["fill"]="#00000000",["id"]="update-sweep-rect-149",["layer"]=35,["size"]={0.63,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[150],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[139],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[151] = scene:rectangle {["center"]={-2.515,-0.015},["fill"]="#444444",["id"]="update-sweep-rect-150",["layer"]=28,["size"]={0.58,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[151],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[152] = scene:rectangle {["center"]={-2.515,-0.015},["fill"]="#444444",["id"]="update-sweep-rect-151",["layer"]=38,["size"]={0.55,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[152],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[152],shift={0.895,-3.245}}},0.65,"linear",0)
refs[153] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="update-sweep-text-152",["layer"]=50,["point"]={-1.62,-3.26},["role"]="text",["size"]=17,["text"]="211"}
scene:fade_in(refs[153],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(0.45)
scene:fade_out(refs[139],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[150],{["curve"]="ease_in",["duration"]=0.12,["scale"]=1,["shift"]={0,0,0}})
refs[154] = scene:group {["id"]="update-sweep-group-153"}
refs[155] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#3f7cce",["font"]="Pretendard",["id"]="update-sweep-text-154",["layer"]=50,["point"]={2.86,1.79},["role"]="text",["size"]=25,["text"]="Cell · y 3 · x 5"}
refs[156] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-155",["layer"]=50,["point"]={1.35,1.08},["role"]="text",["size"]=21,["text"]="cover"}
refs[157] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-156",["layer"]=50,["point"]={3.79,1.08},["role"]="text",["size"]=32,["text"]="0"}
refs[158] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-157",["layer"]=50,["point"]={2.86,0.63},["role"]="text",["size"]=25,["text"]="106 − 106"}
refs[159] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-158",["layer"]=50,["point"]={2.86,-0.07},["role"]="text",["size"]=25,["text"]="0 × 512 − (-6182)"}
refs[160] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-159",["layer"]=50,["point"]={2.86,-0.54},["role"]="text",["size"]=28,["text"]="6182"}
refs[161] = refs[154]:arrow {["from"]={2.86,-0.84},["id"]="update-sweep-arrow-160",["layer"]=25,["stroke"]="#707070",["tip"]=9,["to"]={2.86,-1.24},["width"]=1.5}
refs[162] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-161",["layer"]=50,["point"]={2.86,-1.58},["role"]="text",["size"]=22,["text"]="abs(area >> 9) · clamp 255"}
refs[163] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-162",["layer"]=50,["point"]={2.86,-2.11},["role"]="text",["size"]=37,["text"]="12"}
refs[164] = refs[154]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-163",["layer"]=50,["point"]={2.86,-3.34},["role"]="text",["size"]=26,["text"]="5 · 1 · 12"}
refs[165] = scene:rectangle {["center"]={-1.885,-0.015},["fill"]="#00000000",["id"]="update-sweep-rect-164",["layer"]=35,["size"]={0.63,0.63},["stroke"]="#202020",["width"]=3.2}
scene:fade_in(refs[165],{["curve"]="ease_out",["duration"]=0.22,["scale"]=1,["shift"]={0,0,0}})
scene:fade_in(refs[154],{["curve"]="ease_out",["duration"]=0.35,["scale"]=1,["shift"]={0,0,0}})
refs[166] = scene:rectangle {["center"]={-1.885,-0.015},["fill"]="#e8e8e8",["id"]="update-sweep-rect-165",["layer"]=28,["size"]={0.58,0.58},["stroke"]="#00000000",["width"]=0}
scene:fade_in(refs[166],{["curve"]="ease_out",["duration"]=0.42,["scale"]=1,["shift"]={0,0,0}})
refs[167] = scene:rectangle {["center"]={-1.885,-0.015},["fill"]="#e8e8e8",["id"]="update-sweep-rect-166",["layer"]=38,["size"]={0.55,0.32},["stroke"]="#ffffff",["width"]=1.2}
scene:fade_in(refs[167],{["curve"]="ease_out",["duration"]=0.06,["scale"]=1,["shift"]={0,0,0}})
scene:play({{target=refs[167],shift={0.845,-3.245}}},0.65,"linear",0)
refs[168] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-167",["layer"]=50,["point"]={-1.04,-3.26},["role"]="text",["size"]=17,["text"]="12"}
scene:fade_in(refs[168],{["curve"]="ease_out",["duration"]=0.13,["scale"]=1,["shift"]={0,0,0}})
scene:wait(1)
scene:fade_out(refs[154],{["curve"]="ease_in",["duration"]=0.2,["scale"]=1,["shift"]={0,0,0}})
scene:fade_out(refs[165],{["curve"]="ease_in",["duration"]=0.2,["scale"]=1,["shift"]={0,0,0}})
refs[169] = scene:group {["id"]="update-sweep-group-168"}
refs[170] = refs[169]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-169",["layer"]=50,["point"]={2.86,1.09},["role"]="text",["size"]=27,["text"]="5 edge cells"}
refs[171] = refs[169]:arrow {["from"]={2.86,0.69},["id"]="update-sweep-arrow-170",["layer"]=25,["stroke"]="#202020",["tip"]=9,["to"]={2.86,0.1},["width"]=2}
refs[172] = refs[169]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-171",["layer"]=50,["point"]={2.86,-0.38},["role"]="text",["size"]=33,["text"]="7 spans"}
refs[173] = refs[169]:text {["align"]={0.5,0.5},["fill"]="#707070",["font"]="Pretendard",["id"]="update-sweep-text-172",["layer"]=50,["point"]={2.86,-1.19},["role"]="text",["size"]=22,["text"]="Same y + coverage + adjacent x"}
refs[174] = refs[169]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="update-sweep-text-173",["layer"]=50,["point"]={2.86,-1.63},["role"]="text",["size"]=25,["text"]="→ one run"}
scene:fade_in(refs[169],{["curve"]="ease_out",["duration"]=0.6,["scale"]=1,["shift"]={0,0,0}})
scene:wait(2)
return scene
