-- Generated by scripts/render-update-scenes.mjs; edit tasks.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=13.2,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=1320,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white"},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-0",["layer"]=50,["point"]={0,6.08},["role"]="text",["size"]=32,["text"]="Prepare Task"}
refs[2] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-1",["layer"]=50,["point"]={-4.95,5.09},["role"]="text",["size"]=21,["text"]="Input"}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-2",["layer"]=50,["point"]={-0.3,5.09},["role"]="text",["size"]=21,["text"]="Task → SwTask"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-3",["layer"]=50,["point"]={4.6,5.09},["role"]="text",["size"]=21,["text"]="Canvas"}
refs[5] = scene:group {["id"]="tasks-4",["opacity"]=1}
refs[6] = scene:group {["id"]="tasks-5",["opacity"]=0}
refs[7] = scene:group {["id"]="tasks-6",["opacity"]=0}
refs[8] = scene:group {["id"]="tasks-7",["opacity"]=0}
refs[9] = scene:group {["id"]="tasks-8",["opacity"]=0}
refs[10] = refs[9]:route {["id"]="tasks-9",["layer"]=30,["points"]={{-5.75,3.64},{-4.1,3.64}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[11] = scene:rectangle {["center"]={-0.3,3.1},["fill"]="#ffffff",["id"]="tasks-10",["layer"]=15,["size"]={5.6,3.4},["stroke"]="#202020",["width"]=1.5}
refs[12] = scene:rectangle {["center"]={-0.3,4.47},["fill"]="#202020",["id"]="tasks-11",["layer"]=15,["size"]={5.6,0.66},["stroke"]="#202020",["width"]=1.5}
refs[13] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="tasks-12",["layer"]=50,["point"]={-0.3,4.47},["role"]="text",["size"]=25,["text"]="SwShapeTask"}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-13",["layer"]=50,["point"]={-1.9,3.62},["role"]="text",["size"]=21,["text"]="RenderData"}
refs[15] = scene:route {["id"]="tasks-14",["layer"]=22,["points"]={{-1.9,3.83},{-1.9,4.1}},["stroke"]="#202020",["tip"]=8,["width"]=1.8}
refs[16] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-15",["layer"]=50,["point"]={0.9,3.6},["role"]="text",["size"]=23,["text"]="shape"}
refs[17] = scene:rectangle {["center"]={0.9,2.58},["fill"]="#ffffff",["id"]="tasks-16",["layer"]=15,["size"]={2.5,1.65},["stroke"]="#cccccc",["width"]=1.5}
refs[18] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-17",["layer"]=50,["point"]={-1.55,2.86},["role"]="text",["size"]=22,["text"]="run(tid)"}
refs[19] = scene:route {["id"]="tasks-18",["layer"]=22,["points"]={{-0.95,2.86},{-0.55,2.86}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[20] = scene:route {["id"]="tasks-19",["layer"]=8,["points"]={{-4.02,3.1},{-3.3,3.1}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[21] = scene:rectangle {["center"]={4.6,3.1},["fill"]="#ffffff",["id"]="tasks-20",["layer"]=15,["size"]={2.2,2.5},["stroke"]="#202020",["width"]=1.5}
refs[22] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-21",["layer"]=50,["point"]={-4.95,1.85},["role"]="text",["size"]=22,["text"]="RenderPath"}
refs[23] = refs[5]:polygon {["fill"]="#00000000",["id"]="tasks-22",["layer"]=25,["points"]={{-5.04,3.82},{-5.67,2.47},{-4.23,2.47}},["stroke"]="#e66121",["width"]=2}
refs[24] = scene:group {["id"]="tasks-23",["opacity"]=0}
refs[25] = refs[24]:rectangle {["center"]={0.82,3.06},["fill"]="#202020",["id"]="tasks-24",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[26] = refs[24]:route {["id"]="tasks-25",["layer"]=30,["points"]={{0.82,3.06},{0.9,3.06}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[27] = scene:group {["id"]="tasks-26",["opacity"]=0}
refs[28] = refs[27]:rectangle {["center"]={0.82,2.9},["fill"]="#202020",["id"]="tasks-27",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[29] = refs[27]:route {["id"]="tasks-28",["layer"]=30,["points"]={{0.82,2.9},{1.06,2.9}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[30] = scene:group {["id"]="tasks-29",["opacity"]=0}
refs[31] = refs[30]:rectangle {["center"]={0.66,2.74},["fill"]="#202020",["id"]="tasks-30",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[32] = refs[30]:route {["id"]="tasks-31",["layer"]=30,["points"]={{0.66,2.74},{1.06,2.74}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[33] = scene:group {["id"]="tasks-32",["opacity"]=0}
refs[34] = refs[33]:rectangle {["center"]={0.66,2.58},["fill"]="#202020",["id"]="tasks-33",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[35] = refs[33]:route {["id"]="tasks-34",["layer"]=30,["points"]={{0.66,2.58},{1.22,2.58}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[36] = scene:group {["id"]="tasks-35",["opacity"]=0}
refs[37] = refs[36]:rectangle {["center"]={0.5,2.42},["fill"]="#202020",["id"]="tasks-36",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[38] = refs[36]:route {["id"]="tasks-37",["layer"]=30,["points"]={{0.5,2.42},{1.22,2.42}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[39] = scene:group {["id"]="tasks-38",["opacity"]=0}
refs[40] = refs[39]:rectangle {["center"]={0.5,2.26},["fill"]="#202020",["id"]="tasks-39",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[41] = refs[39]:route {["id"]="tasks-40",["layer"]=30,["points"]={{0.5,2.26},{1.38,2.26}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[42] = scene:group {["id"]="tasks-41",["opacity"]=0}
refs[43] = refs[42]:rectangle {["center"]={0.34,2.1},["fill"]="#202020",["id"]="tasks-42",["layer"]=24,["size"]={0.14,0.14},["stroke"]="#00000000",["width"]=1.5}
refs[44] = refs[42]:route {["id"]="tasks-43",["layer"]=30,["points"]={{0.34,2.1},{1.54,2.1}},["stroke"]="#1f6bc4",["tip"]=0,["width"]=1.8}
refs[45] = refs[6]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-44",["layer"]=50,["point"]={0.9,1.65},["role"]="text",["size"]=18,["text"]="RLE"}
refs[46] = scene:group {["id"]="tasks-45",["opacity"]=0}
refs[47] = refs[46]:rectangle {["center"]={4.5,3.7},["fill"]="#e66121",["id"]="tasks-46",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[48] = scene:group {["id"]="tasks-47",["opacity"]=0}
refs[49] = refs[48]:rectangle {["center"]={4.5,3.5},["fill"]="#e66121",["id"]="tasks-48",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[50] = refs[48]:rectangle {["center"]={4.7,3.5},["fill"]="#e66121",["id"]="tasks-49",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[51] = scene:group {["id"]="tasks-50",["opacity"]=0}
refs[52] = refs[51]:rectangle {["center"]={4.3,3.3},["fill"]="#e66121",["id"]="tasks-51",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[53] = refs[51]:rectangle {["center"]={4.5,3.3},["fill"]="#e66121",["id"]="tasks-52",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[54] = refs[51]:rectangle {["center"]={4.7,3.3},["fill"]="#e66121",["id"]="tasks-53",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[55] = scene:group {["id"]="tasks-54",["opacity"]=0}
refs[56] = refs[55]:rectangle {["center"]={4.3,3.1},["fill"]="#e66121",["id"]="tasks-55",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[57] = refs[55]:rectangle {["center"]={4.5,3.1},["fill"]="#e66121",["id"]="tasks-56",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[58] = refs[55]:rectangle {["center"]={4.7,3.1},["fill"]="#e66121",["id"]="tasks-57",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[59] = refs[55]:rectangle {["center"]={4.9,3.1},["fill"]="#e66121",["id"]="tasks-58",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[60] = scene:group {["id"]="tasks-59",["opacity"]=0}
refs[61] = refs[60]:rectangle {["center"]={4.1,2.9},["fill"]="#e66121",["id"]="tasks-60",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[62] = refs[60]:rectangle {["center"]={4.3,2.9},["fill"]="#e66121",["id"]="tasks-61",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[63] = refs[60]:rectangle {["center"]={4.5,2.9},["fill"]="#e66121",["id"]="tasks-62",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[64] = refs[60]:rectangle {["center"]={4.7,2.9},["fill"]="#e66121",["id"]="tasks-63",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[65] = refs[60]:rectangle {["center"]={4.9,2.9},["fill"]="#e66121",["id"]="tasks-64",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[66] = scene:group {["id"]="tasks-65",["opacity"]=0}
refs[67] = refs[66]:rectangle {["center"]={4.1,2.7},["fill"]="#e66121",["id"]="tasks-66",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[68] = refs[66]:rectangle {["center"]={4.3,2.7},["fill"]="#e66121",["id"]="tasks-67",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[69] = refs[66]:rectangle {["center"]={4.5,2.7},["fill"]="#e66121",["id"]="tasks-68",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[70] = refs[66]:rectangle {["center"]={4.7,2.7},["fill"]="#e66121",["id"]="tasks-69",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[71] = refs[66]:rectangle {["center"]={4.9,2.7},["fill"]="#e66121",["id"]="tasks-70",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[72] = refs[66]:rectangle {["center"]={5.1,2.7},["fill"]="#e66121",["id"]="tasks-71",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[73] = scene:group {["id"]="tasks-72",["opacity"]=0}
refs[74] = refs[73]:rectangle {["center"]={3.9,2.5},["fill"]="#e66121",["id"]="tasks-73",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[75] = refs[73]:rectangle {["center"]={4.1,2.5},["fill"]="#e66121",["id"]="tasks-74",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[76] = refs[73]:rectangle {["center"]={4.3,2.5},["fill"]="#e66121",["id"]="tasks-75",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[77] = refs[73]:rectangle {["center"]={4.5,2.5},["fill"]="#e66121",["id"]="tasks-76",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[78] = refs[73]:rectangle {["center"]={4.7,2.5},["fill"]="#e66121",["id"]="tasks-77",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[79] = refs[73]:rectangle {["center"]={4.9,2.5},["fill"]="#e66121",["id"]="tasks-78",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[80] = refs[73]:rectangle {["center"]={5.1,2.5},["fill"]="#e66121",["id"]="tasks-79",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[81] = refs[73]:rectangle {["center"]={5.3,2.5},["fill"]="#e66121",["id"]="tasks-80",["layer"]=25,["size"]={0.19,0.19},["stroke"]="#00000000",["width"]=1.5}
refs[82] = scene:rectangle {["center"]={-0.3,-0.9},["fill"]="#ffffff",["id"]="tasks-81",["layer"]=15,["size"]={5.6,3.4},["stroke"]="#202020",["width"]=1.5}
refs[83] = scene:rectangle {["center"]={-0.3,0.47},["fill"]="#202020",["id"]="tasks-82",["layer"]=15,["size"]={5.6,0.66},["stroke"]="#202020",["width"]=1.5}
refs[84] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="tasks-83",["layer"]=50,["point"]={-0.3,0.47},["role"]="text",["size"]=25,["text"]="SwImageTask"}
refs[85] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-84",["layer"]=50,["point"]={-1.9,-0.38},["role"]="text",["size"]=21,["text"]="RenderData"}
refs[86] = scene:route {["id"]="tasks-85",["layer"]=22,["points"]={{-1.9,-0.17},{-1.9,0.1}},["stroke"]="#202020",["tip"]=8,["width"]=1.8}
refs[87] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-86",["layer"]=50,["point"]={0.9,-0.4},["role"]="text",["size"]=23,["text"]="image"}
refs[88] = scene:rectangle {["center"]={0.9,-1.42},["fill"]="#ffffff",["id"]="tasks-87",["layer"]=15,["size"]={2.5,1.65},["stroke"]="#cccccc",["width"]=1.5}
refs[89] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-88",["layer"]=50,["point"]={-1.55,-1.14},["role"]="text",["size"]=22,["text"]="run(tid)"}
refs[90] = scene:route {["id"]="tasks-89",["layer"]=22,["points"]={{-0.95,-1.14},{-0.55,-1.14}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[91] = scene:route {["id"]="tasks-90",["layer"]=8,["points"]={{-4.02,-0.9},{-3.3,-0.9}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[92] = scene:rectangle {["center"]={4.6,-0.9},["fill"]="#ffffff",["id"]="tasks-91",["layer"]=15,["size"]={2.2,2.5},["stroke"]="#202020",["width"]=1.5}
refs[93] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-92",["layer"]=50,["point"]={-4.95,-2.15},["role"]="text",["size"]=22,["text"]="Bitmap"}
refs[94] = refs[5]:rectangle {["center"]={-5.43,-0.42},["fill"]="#1f6bc4",["id"]="tasks-93",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[95] = refs[5]:rectangle {["center"]={-5.11,-0.42},["fill"]="#1f6bc4",["id"]="tasks-94",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[96] = refs[5]:rectangle {["center"]={-4.79,-0.42},["fill"]="#96bfdf",["id"]="tasks-95",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[97] = refs[5]:rectangle {["center"]={-4.47,-0.42},["fill"]="#f4d078",["id"]="tasks-96",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[98] = refs[5]:rectangle {["center"]={-5.43,-0.74},["fill"]="#1f6bc4",["id"]="tasks-97",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[99] = refs[5]:rectangle {["center"]={-5.11,-0.74},["fill"]="#96bfdf",["id"]="tasks-98",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[100] = refs[5]:rectangle {["center"]={-4.79,-0.74},["fill"]="#f4d078",["id"]="tasks-99",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[101] = refs[5]:rectangle {["center"]={-4.47,-0.74},["fill"]="#f4d078",["id"]="tasks-100",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[102] = refs[5]:rectangle {["center"]={-5.43,-1.06},["fill"]="#96bfdf",["id"]="tasks-101",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[103] = refs[5]:rectangle {["center"]={-5.11,-1.06},["fill"]="#f4d078",["id"]="tasks-102",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[104] = refs[5]:rectangle {["center"]={-4.79,-1.06},["fill"]="#e66121",["id"]="tasks-103",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[105] = refs[5]:rectangle {["center"]={-4.47,-1.06},["fill"]="#e66121",["id"]="tasks-104",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[106] = refs[5]:rectangle {["center"]={-5.43,-1.38},["fill"]="#f4d078",["id"]="tasks-105",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[107] = refs[5]:rectangle {["center"]={-5.11,-1.38},["fill"]="#f4d078",["id"]="tasks-106",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[108] = refs[5]:rectangle {["center"]={-4.79,-1.38},["fill"]="#e66121",["id"]="tasks-107",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[109] = refs[5]:rectangle {["center"]={-4.47,-1.38},["fill"]="#202020",["id"]="tasks-108",["layer"]=25,["size"]={0.31,0.31},["stroke"]="#00000000",["width"]=1.5}
refs[110] = refs[7]:rectangle {["center"]={0.495,-0.935},["fill"]="#1f6bc4",["id"]="tasks-109",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[111] = refs[7]:rectangle {["center"]={0.765,-0.935},["fill"]="#1f6bc4",["id"]="tasks-110",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[112] = refs[7]:rectangle {["center"]={1.035,-0.935},["fill"]="#96bfdf",["id"]="tasks-111",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[113] = refs[7]:rectangle {["center"]={1.305,-0.935},["fill"]="#f4d078",["id"]="tasks-112",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[114] = refs[7]:rectangle {["center"]={0.495,-1.205},["fill"]="#1f6bc4",["id"]="tasks-113",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[115] = refs[7]:rectangle {["center"]={0.765,-1.205},["fill"]="#96bfdf",["id"]="tasks-114",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[116] = refs[7]:rectangle {["center"]={1.035,-1.205},["fill"]="#f4d078",["id"]="tasks-115",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[117] = refs[7]:rectangle {["center"]={1.305,-1.205},["fill"]="#f4d078",["id"]="tasks-116",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[118] = refs[7]:rectangle {["center"]={0.495,-1.475},["fill"]="#96bfdf",["id"]="tasks-117",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[119] = refs[7]:rectangle {["center"]={0.765,-1.475},["fill"]="#f4d078",["id"]="tasks-118",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[120] = refs[7]:rectangle {["center"]={1.035,-1.475},["fill"]="#e66121",["id"]="tasks-119",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[121] = refs[7]:rectangle {["center"]={1.305,-1.475},["fill"]="#e66121",["id"]="tasks-120",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[122] = refs[7]:rectangle {["center"]={0.495,-1.745},["fill"]="#f4d078",["id"]="tasks-121",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[123] = refs[7]:rectangle {["center"]={0.765,-1.745},["fill"]="#f4d078",["id"]="tasks-122",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[124] = refs[7]:rectangle {["center"]={1.035,-1.745},["fill"]="#e66121",["id"]="tasks-123",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[125] = refs[7]:rectangle {["center"]={1.305,-1.745},["fill"]="#202020",["id"]="tasks-124",["layer"]=25,["size"]={0.26,0.26},["stroke"]="#00000000",["width"]=1.5}
refs[126] = refs[7]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-125",["layer"]=50,["point"]={0.9,-2.35},["role"]="text",["size"]=18,["text"]="transform"}
refs[127] = refs[8]:rectangle {["center"]={4.075,-0.375},["fill"]="#1f6bc4",["id"]="tasks-126",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[128] = refs[8]:rectangle {["center"]={4.425,-0.375},["fill"]="#1f6bc4",["id"]="tasks-127",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[129] = refs[8]:rectangle {["center"]={4.775,-0.375},["fill"]="#96bfdf",["id"]="tasks-128",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[130] = refs[8]:rectangle {["center"]={5.125,-0.375},["fill"]="#f4d078",["id"]="tasks-129",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[131] = refs[8]:rectangle {["center"]={4.075,-0.725},["fill"]="#1f6bc4",["id"]="tasks-130",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[132] = refs[8]:rectangle {["center"]={4.425,-0.725},["fill"]="#96bfdf",["id"]="tasks-131",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[133] = refs[8]:rectangle {["center"]={4.775,-0.725},["fill"]="#f4d078",["id"]="tasks-132",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[134] = refs[8]:rectangle {["center"]={5.125,-0.725},["fill"]="#f4d078",["id"]="tasks-133",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[135] = refs[8]:rectangle {["center"]={4.075,-1.075},["fill"]="#96bfdf",["id"]="tasks-134",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[136] = refs[8]:rectangle {["center"]={4.425,-1.075},["fill"]="#f4d078",["id"]="tasks-135",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[137] = refs[8]:rectangle {["center"]={4.775,-1.075},["fill"]="#e66121",["id"]="tasks-136",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[138] = refs[8]:rectangle {["center"]={5.125,-1.075},["fill"]="#e66121",["id"]="tasks-137",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[139] = refs[8]:rectangle {["center"]={4.075,-1.425},["fill"]="#f4d078",["id"]="tasks-138",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[140] = refs[8]:rectangle {["center"]={4.425,-1.425},["fill"]="#f4d078",["id"]="tasks-139",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[141] = refs[8]:rectangle {["center"]={4.775,-1.425},["fill"]="#e66121",["id"]="tasks-140",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[142] = refs[8]:rectangle {["center"]={5.125,-1.425},["fill"]="#202020",["id"]="tasks-141",["layer"]=25,["size"]={0.34,0.34},["stroke"]="#00000000",["width"]=1.5}
refs[143] = scene:group {["id"]="tasks-142",["opacity"]=0}
refs[144] = refs[143]:route {["id"]="tasks-143",["layer"]=8,["points"]={{2.6,3.1},{3.4,3.1}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[145] = refs[143]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-144",["layer"]=50,["point"]={3.01,3.36},["role"]="text",["size"]=18,["text"]="done()"}
refs[146] = refs[143]:route {["id"]="tasks-145",["layer"]=8,["points"]={{2.6,-0.9},{3.4,-0.9}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[147] = refs[143]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-146",["layer"]=50,["point"]={3.01,-0.64},["role"]="text",["size"]=18,["text"]="done()"}
refs[148] = scene:group {["id"]="tasks-147",["opacity"]=0}
refs[149] = scene:group {["id"]="tasks-148",["opacity"]=0}
refs[150] = scene:group {["id"]="tasks-149",["opacity"]=0}
refs[151] = scene:group {["id"]="tasks-150",["opacity"]=0}
refs[152] = refs[148]:rectangle {["center"]={-4.5,-3.8},["fill"]="#ffffff",["id"]="tasks-151",["layer"]=15,["size"]={2.4,0.58},["stroke"]="#202020",["width"]=1.5}
refs[153] = refs[148]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-152",["layer"]=50,["point"]={-4.5,-3.8},["role"]="text",["size"]=22,["text"]="request(task)"}
refs[154] = refs[149]:rectangle {["center"]={-1.3,-3.8},["fill"]="#ffffff",["id"]="tasks-153",["layer"]=15,["size"]={1.8,0.58},["stroke"]="#202020",["width"]=1.5}
refs[155] = refs[149]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-154",["layer"]=50,["point"]={-1.3,-3.8},["role"]="text",["size"]=22,["text"]="run(tid)"}
refs[156] = refs[149]:route {["id"]="tasks-155",["layer"]=8,["points"]={{-3.3,-3.8},{-2.3,-3.8}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[157] = refs[150]:rectangle {["center"]={1.7,-3.8},["fill"]="#ffffff",["id"]="tasks-156",["layer"]=15,["size"]={1.8,0.58},["stroke"]="#202020",["width"]=1.5}
refs[158] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-157",["layer"]=50,["point"]={1.7,-3.8},["role"]="text",["size"]=22,["text"]="done()"}
refs[159] = refs[150]:route {["id"]="tasks-158",["layer"]=8,["points"]={{-0.3,-3.8},{0.7,-3.8}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[160] = refs[150]:rectangle {["center"]={4.6,-3.8},["fill"]="#ffffff",["id"]="tasks-159",["layer"]=15,["size"]={1.8,0.58},["stroke"]="#202020",["width"]=1.5}
refs[161] = refs[150]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-160",["layer"]=50,["point"]={4.6,-3.8},["role"]="text",["size"]=22,["text"]="Draw"}
refs[162] = refs[150]:route {["id"]="tasks-161",["layer"]=8,["points"]={{2.7,-3.8},{3.6,-3.8}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[163] = refs[151]:rectangle {["center"]={4.6,-5.3},["fill"]="#ffffff",["id"]="tasks-162",["layer"]=15,["size"]={1.8,0.58},["stroke"]="#202020",["width"]=1.5}
refs[164] = refs[151]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="tasks-163",["layer"]=50,["point"]={4.6,-5.3},["role"]="text",["size"]=22,["text"]="sync()"}
refs[165] = refs[151]:route {["id"]="tasks-164",["layer"]=8,["points"]={{4.6,-4.1},{4.6,-4.9}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[166] = refs[151]:route {["id"]="tasks-165",["layer"]=8,["points"]={{3.6,-5.3},{-4.5,-5.3},{-4.5,-4.2}},["stroke"]="#202020",["tip"]=9,["width"]=1.8}
refs[167] = refs[151]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="tasks-166",["layer"]=50,["point"]={0,-5.75},["role"]="text",["size"]=22,["text"]="Next update · retained tasks"}
scene:wait(0.8)
scene:play({{target=refs[148],opacity=1}},0.5,"ease_in_out",0)
scene:wait(0.8)
scene:play({{target=refs[149],opacity=1}},0.5,"ease_in_out",0)
scene:play({{target=refs[6],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[9],opacity=1}},0.2,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1}},{target=refs[24],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-0.18,0,0,1,0,0,0,0,1}},{target=refs[27],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-0.36,0,0,1,0,0,0,0,1}},{target=refs[30],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-0.54,0,0,1,0,0,0,0,1}},{target=refs[33],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-0.72,0,0,1,0,0,0,0,1}},{target=refs[36],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-0.9,0,0,1,0,0,0,0,1}},{target=refs[39],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],transform={1,0,0,0,0,1,0,-1.08,0,0,1,0,0,0,0,1}},{target=refs[42],opacity=1}},0.18,"ease_in_out",0)
scene:play({{target=refs[9],opacity=0}},0.2,"ease_in_out",0)
scene:play({{target=refs[7],opacity=1}},0.8,"ease_in_out",0)
scene:wait(0.8)
scene:play({{target=refs[150],opacity=1}},0.5,"ease_in_out",0)
scene:play({{target=refs[143],opacity=1}},0.5,"ease_in_out",0)
scene:play({{target=refs[46],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[48],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[51],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[55],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[60],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[66],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[73],opacity=1}},0.12,"ease_in_out",0)
scene:play({{target=refs[8],opacity=1}},0.8,"ease_in_out",0)
scene:wait(0.8)
scene:play({{target=refs[151],opacity=1}},0.5,"ease_in_out",0)
scene:wait(0.8)
scene:wait(1.5)
return scene
