-- Generated by scripts/render-update-scenes.mjs; edit tasks.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=13.2,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=1320,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#222222",["font"]="Pretendard"},["h1"]={["color"]="#222222",["font"]="Pretendard"},["h2"]={["color"]="#222222",["font"]="Pretendard"},["h3"]={["color"]="#222222",["font"]="Pretendard"},["text"]={["color"]="#222222",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-0",["layer"]=40,["point"]={0,6.12},["size"]=32,["text"]="Prepare tasks"}
refs[2] = scene:rectangle {["center"]={0,5.23},["fill"]="#ffffff",["id"]="tasks-1",["layer"]=15,["size"]={2.7,0.58},["stroke"]="#222222",["width"]=1.4}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-2",["layer"]=40,["point"]={0,5.23},["size"]=23,["text"]="Task"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-3",["layer"]=40,["point"]={3,5.23},["size"]=20,["text"]="run(tid) · done()"}
refs[5] = scene:route {["id"]="tasks-4",["layer"]=5,["points"]={{0,4.93},{0,4.36}},["stroke"]="#222222",["tip"]=0,["width"]=1.4}
refs[6] = scene:rectangle {["center"]={0,4.05},["fill"]="#ffffff",["id"]="tasks-5",["layer"]=15,["size"]={3.1,0.62},["stroke"]="#222222",["width"]=1.4}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-6",["layer"]=40,["point"]={0,4.05},["size"]=23,["text"]="SwTask"}
refs[8] = scene:group {["id"]="tasks-7",["opacity"]=0}
refs[9] = refs[8]:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-8",["layer"]=40,["point"]={0,3.42},["size"]=22,["text"]="transform · clips · opacity · flags"}
refs[10] = scene:route {["id"]="tasks-9",["layer"]=5,["points"]={{0,3.16},{-3.1,3.16},{-3.1,2.8}},["stroke"]="#222222",["tip"]=0,["width"]=1.4}
refs[11] = scene:route {["id"]="tasks-10",["layer"]=5,["points"]={{0,3.16},{3.1,3.16},{3.1,2.8}},["stroke"]="#222222",["tip"]=0,["width"]=1.4}
refs[12] = scene:rectangle {["center"]={-3.1,0.95},["fill"]="#ffffff",["id"]="tasks-11",["layer"]=15,["size"]={5.3,3.7},["stroke"]="#222222",["width"]=1.4}
refs[13] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="tasks-12",["layer"]=40,["point"]={-3.1,2.42},["size"]=28,["text"]="SwShapeTask"}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-13",["layer"]=40,["point"]={-3.1,1.79},["size"]=21,["text"]="const RenderShape* rshape"}
refs[15] = scene:rectangle {["center"]={-3.1,0.65},["fill"]="#ffffff",["id"]="tasks-14",["layer"]=15,["size"]={4.64,1.4},["stroke"]="#bcbcbc",["width"]=1.4}
refs[16] = scene:group {["id"]="tasks-15",["opacity"]=0}
refs[17] = refs[16]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="tasks-16",["layer"]=40,["point"]={-3.1,0.95},["size"]=25,["text"]="SwShape shape"}
refs[18] = refs[16]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-17",["layer"]=40,["point"]={-3.1,0.39},["size"]=20,["text"]="Rect / RLE · Fill · Stroke"}
refs[19] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-18",["layer"]=40,["point"]={-3.1,-0.51},["size"]=21,["text"]="RenderData = task"}
refs[20] = scene:rectangle {["center"]={3.1,0.95},["fill"]="#ffffff",["id"]="tasks-19",["layer"]=15,["size"]={5.3,3.7},["stroke"]="#222222",["width"]=1.4}
refs[21] = scene:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="tasks-20",["layer"]=40,["point"]={3.1,2.42},["size"]=28,["text"]="SwImageTask"}
refs[22] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-21",["layer"]=40,["point"]={3.1,1.79},["size"]=21,["text"]="RenderSurface* source"}
refs[23] = scene:rectangle {["center"]={3.1,0.65},["fill"]="#ffffff",["id"]="tasks-22",["layer"]=15,["size"]={4.64,1.4},["stroke"]="#bcbcbc",["width"]=1.4}
refs[24] = scene:group {["id"]="tasks-23",["opacity"]=0}
refs[25] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="tasks-24",["layer"]=40,["point"]={3.1,0.95},["size"]=25,["text"]="SwImage image"}
refs[26] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-25",["layer"]=40,["point"]={3.1,0.39},["size"]=20,["text"]="Pixels · Sampling · Image RLE*"}
refs[27] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-26",["layer"]=40,["point"]={3.1,-0.51},["size"]=21,["text"]="RenderData = task"}
refs[28] = scene:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-27",["layer"]=40,["point"]={3.1,-1.17},["size"]=17,["text"]="* Image RLE when needed"}
refs[29] = scene:group {["id"]="tasks-28",["opacity"]=0}
refs[30] = refs[29]:rectangle {["center"]={-4.1,-2.01},["fill"]="#ffffff",["id"]="tasks-29",["layer"]=15,["size"]={2.86,0.62},["stroke"]="#222222",["width"]=1.4}
refs[31] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-30",["layer"]=40,["point"]={-4.1,-2.01},["size"]=23,["text"]="request(task)"}
refs[32] = refs[29]:rectangle {["center"]={0,-2.01},["fill"]="#ffffff",["id"]="tasks-31",["layer"]=15,["size"]={2.7,0.62},["stroke"]="#222222",["width"]=1.4}
refs[33] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-32",["layer"]=40,["point"]={0,-2.01},["size"]=23,["text"]="run(tid)"}
refs[34] = refs[29]:rectangle {["center"]={4.1,-2.01},["fill"]="#ffffff",["id"]="tasks-33",["layer"]=15,["size"]={2.5,0.62},["stroke"]="#222222",["width"]=1.4}
refs[35] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-34",["layer"]=40,["point"]={4.1,-2.01},["size"]=23,["text"]="done()"}
refs[36] = refs[29]:route {["dash"]={5,4},["id"]="tasks-35",["layer"]=5,["points"]={{-2.67,-2.01},{-1.35,-2.01}},["stroke"]="#222222",["tip"]=8,["width"]=1.4}
refs[37] = refs[29]:route {["dash"]={5,4},["id"]="tasks-36",["layer"]=5,["points"]={{1.35,-2.01},{2.85,-2.01}},["stroke"]="#222222",["tip"]=8,["width"]=1.4}
refs[38] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-37",["layer"]=40,["point"]={-4.1,-1.47},["size"]=19,["text"]="TaskScheduler"}
refs[39] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-38",["layer"]=40,["point"]={0,-1.47},["size"]=19,["text"]="Worker"}
refs[40] = refs[29]:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-39",["layer"]=40,["point"]={4.1,-1.47},["size"]=19,["text"]="Caller · render*()"}
refs[41] = scene:group {["id"]="tasks-40",["opacity"]=0}
refs[42] = refs[41]:rectangle {["center"]={-4.1,-2.68},["fill"]="#ffffff",["id"]="tasks-41",["layer"]=15,["size"]={1.42,0.5},["stroke"]="#e66121",["width"]=1.4}
refs[43] = refs[41]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="tasks-42",["layer"]=40,["point"]={-4.1,-2.68},["size"]=17,["text"]="Shape"}
refs[44] = scene:group {["id"]="tasks-43",["opacity"]=0}
refs[45] = refs[44]:rectangle {["center"]={-4.1,-3.24},["fill"]="#ffffff",["id"]="tasks-44",["layer"]=15,["size"]={1.42,0.5},["stroke"]="#1f6bc4",["width"]=1.4}
refs[46] = refs[44]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="tasks-45",["layer"]=40,["point"]={-4.1,-3.24},["size"]=17,["text"]="Bitmap"}
refs[47] = scene:group {["id"]="tasks-46",["opacity"]=0}
refs[48] = refs[47]:text {["align"]={0.5,0.5},["fill"]="#777777",["font"]="Pretendard",["id"]="tasks-47",["layer"]=40,["point"]={0,-3.77},["size"]=21,["text"]="pending = true"}
refs[49] = scene:group {["id"]="tasks-48",["opacity"]=0}
refs[50] = refs[49]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="tasks-49",["layer"]=40,["point"]={0,-3.77},["size"]=21,["text"]="ready = true"}
refs[51] = scene:group {["id"]="tasks-50",["opacity"]=0}
refs[52] = refs[51]:rectangle {["center"]={-3.1,-4.65},["fill"]="#ffffff",["id"]="tasks-51",["layer"]=15,["size"]={3.5,0.62},["stroke"]="#e66121",["width"]=1.4}
refs[53] = refs[51]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="tasks-52",["layer"]=40,["point"]={-3.1,-4.65},["size"]=23,["text"]="Raster · task->shape"}
refs[54] = refs[51]:rectangle {["center"]={3.1,-4.65},["fill"]="#ffffff",["id"]="tasks-53",["layer"]=15,["size"]={3.5,0.62},["stroke"]="#1f6bc4",["width"]=1.4}
refs[55] = refs[51]:text {["align"]={0.5,0.5},["fill"]="#1f6bc4",["font"]="Pretendard",["id"]="tasks-54",["layer"]=40,["point"]={3.1,-4.65},["size"]=23,["text"]="Raster · task->image"}
refs[56] = refs[51]:route {["dash"]={5,4},["id"]="tasks-55",["layer"]=5,["points"]={{4.1,-3.52},{4.1,-4.1},{-3.1,-4.1},{-3.1,-4.34}},["stroke"]="#222222",["tip"]=8,["width"]=1.4}
refs[57] = refs[51]:route {["dash"]={5,4},["id"]="tasks-56",["layer"]=5,["points"]={{4.1,-4.1},{3.1,-4.1},{3.1,-4.34}},["stroke"]="#222222",["tip"]=8,["width"]=1.4}
refs[58] = scene:group {["id"]="tasks-57",["opacity"]=0}
refs[59] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#222222",["font"]="Pretendard",["id"]="tasks-58",["layer"]=40,["point"]={0,-5.8},["size"]=25,["text"]="Next update · reuse the same RenderData"}
refs[60] = refs[58]:rectangle {["center"]={-3.1,0.95},["fill"]="#00000000",["id"]="tasks-59",["layer"]=15,["size"]={5.46,3.86},["stroke"]="#e66121",["width"]=1.4}
refs[61] = refs[58]:rectangle {["center"]={3.1,0.95},["fill"]="#00000000",["id"]="tasks-60",["layer"]=15,["size"]={5.46,3.86},["stroke"]="#1f6bc4",["width"]=1.4}
scene:wait(1)
scene:play({{target=refs[8],opacity=1}},0.4,"ease_in_out",0)
scene:play({{target=refs[29],opacity=1}},0.4,"ease_in_out",0)
scene:play({{target=refs[41],opacity=1},{target=refs[44],opacity=1}},0.4,"ease_in_out",0)
scene:play({{target=refs[47],opacity=1}},0.2,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[41],shift={4.1,0}},{target=refs[44],shift={4.1,0}}},0.7,"ease_in_out",0)
scene:play({{target=refs[16],opacity=1},{target=refs[24],opacity=1}},0.65,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[47],opacity=0}},0.2,"ease_in_out",0)
scene:play({{target=refs[49],opacity=1}},0.25,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[41],shift={4.1,0}},{target=refs[44],shift={4.1,0}}},0.65,"ease_in_out",0)
scene:play({{target=refs[51],opacity=1}},0.5,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[58],opacity=1}},0.55,"ease_in_out",0)
scene:wait(1)
scene:wait(0.8)
return scene
