// Posters and validation are generated by default; pass --video to also export MP4.
// node render.mjs /path/to/tmath-runtime [--preview] [scene-prefix]
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import sharp from 'sharp';
const dir=path.dirname(fileURLToPath(import.meta.url));
const bundle=path.resolve(process.argv[2]);
const preview=process.argv.includes('--preview');
const filter=process.argv.slice(3).find(a=>!a.startsWith('--'))||'';
const out=path.resolve(dir,'../../IMAGE/07-SW-Bitmap');
const temp=path.join(dir,'temp');
await fs.mkdir(out,{recursive:true});await fs.mkdir(temp,{recursive:true});
const {createTMath}=await import(pathToFileURL(path.join(bundle,'client.js')));
const runtime=await createTMath('return tmath.scene {width=960,height=540}', 'boot.lua',{
 renderEngine:'cpu',wasmBinary:await fs.readFile(path.join(bundle,'tmath-wasm.wasm'))});
runtime.font('Pretendard',await fs.readFile(path.join(bundle,'Pretendard.ttf')));
const names=(await fs.readdir(dir)).filter(n=>n.endsWith('.lua')&&n.startsWith(filter)).sort();
const sheets=[];const summaries=[];
try {
for(const name of names){
 const source=await fs.readFile(path.join(dir,name),'utf8');runtime.loadLua(source,name);
 const [width,height]=runtime.size(),duration=runtime.duration,fps=30;
 const issues=new Set();let minCanvas=Infinity,minTextGap=Infinity;
 const frames=Math.ceil(duration*fps)+1;
 for(let frame=0;frame<frames;frame++){
  const time=Math.min(frame/fps,duration);
  const texts=runtime.layoutReport(time,4).objects.filter(o=>o.type==='text'&&o.visible);
  for(const t of texts){
   if(!/^label_.+$/.test(t.id))issues.add(`missing standalone ledger ${t.id}`);
   const b=t.paintBounds;
   if(!b||b.width<=0||b.height<=0){issues.add(`null text ${t.id}`);continue;}
   const c=Math.min(b.x,b.y,width-b.x-b.width,height-b.y-b.height);minCanvas=Math.min(minCanvas,c);
   if(c<4)issues.add(`canvas ${t.id}: ${c.toFixed(1)}`);
  }
  for(let i=0;i<texts.length;i++)for(let j=i+1;j<texts.length;j++){
   const a=texts[i].paintBounds,b=texts[j].paintBounds;if(!a||!b)continue;
   const dx=Math.max(b.x-a.x-a.width,a.x-b.x-b.width),dy=Math.max(b.y-a.y-a.height,a.y-b.y-b.height);
   minTextGap=Math.min(minTextGap,Math.max(dx,dy));
   if(dx<4&&dy<4)issues.add(`gap ${texts[i].id}/${texts[j].id}`);
  }
 }
 const summary={name,duration,frames,minCanvas,minTextGap,panelClearance:null,ownership:'all text standalone',issues:[...issues]};
 summaries.push(summary);console.log(JSON.stringify(summary));
 await fs.writeFile(path.join(temp,name+'.audit.json'),JSON.stringify(summary,null,2));
 // Keep failed frames reviewable; export video only after layout passes.
 for(const [i,t] of [0,duration*.27,duration*.55,duration*.8,duration].entries()){
  await sharp(Buffer.from(runtime.render(t,true)),{raw:{width,height,channels:4}}).png().toFile(path.join(temp,`${name}-${i}.png`));
 }
 for (const t of [duration*.55,duration]) sheets.push(await sharp(Buffer.from(runtime.render(t,true)),{raw:{width,height,channels:4}}).resize(480,270).jpeg({quality:80}).toBuffer());
 await sharp(Buffer.from(runtime.render(duration,true)),{raw:{width,height,channels:4}}).webp({quality:90}).toFile(path.join(out,name.replace('.lua','.webp')));
 if(!preview&&issues.size)throw Error('Layout failed: '+name);
 if (preview || !process.argv.includes('--video')) continue;
 const ffmpeg=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','rawvideo','-pix_fmt','rgba','-s',`${width}x${height}`,'-r',String(fps),'-i','pipe:0','-an','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',path.join(out,name.replace('.lua','.mp4'))],{stdio:['pipe','inherit','inherit']});
 const done=once(ffmpeg,'close');
 for(let frame=0;frame<frames;frame++)if(!ffmpeg.stdin.write(Buffer.from(runtime.render(Math.min(frame/fps,duration),true))))await once(ffmpeg.stdin,'drain');
 ffmpeg.stdin.end();const [code]=await done;if(code!==0)throw Error(`ffmpeg ${code}`);
 console.log('Exported '+name);
}
await sharp({create:{width:960,height:Math.ceil(sheets.length/2)*270,channels:3,background:'#fff'}}).composite(sheets.map((input,i)=>({input,left:i%2*480,top:Math.floor(i/2)*270}))).jpeg({quality:80}).toFile(path.join(temp,preview?'preview-sheet.jpg':'final-sheet.jpg'));
await fs.writeFile(path.join(temp,'summary.json'),JSON.stringify(summaries,null,2));
}finally{runtime.destroy();}
