-- Generated by scripts/render-simd-scenes.mjs; edit scenes.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=11,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=1100,["loop"]=false,["theme"]={["background"]="#f7f7f7",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-0",["layer"]=40,["point"]={0,5.02},["size"]=30,["text"]="DownScale · Before | After"}
refs[2] = scene:line {["from"]={-6,4.18},["id"]="simd-1",["layer"]=5,["stroke"]="#cccccc",["to"]={6,4.18},["width"]=1}
refs[3] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-2",["layer"]=40,["point"]={-3.2,3.69},["size"]=25,["text"]="BEFORE · Scalar"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-3",["layer"]=40,["point"]={3.1,3.69},["size"]=25,["text"]="AFTER · NEON"}
refs[5] = scene:line {["from"]={0,3.9},["id"]="simd-4",["layer"]=5,["stroke"]="#cccccc",["to"]={0,-5.2},["width"]=1}
refs[6] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-5",["layer"]=40,["point"]={-1.65,2.21},["size"]=22,["text"]="size_t c[4]"}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-6",["layer"]=40,["point"]={-5.28,1.45},["size"]=21,["text"]="A(*p)"}
refs[8] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-7",["layer"]=40,["point"]={-3.01,1.45},["size"]=23,["text"]="+"}
refs[9] = scene:rectangle {["center"]={-1.65,1.45},["fill"]="#ffffff",["id"]="simd-8",["layer"]=15,["size"]={1.72,0.58},["stroke"]="#bcbcbc",["width"]=1.3}
refs[10] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-9",["layer"]=40,["point"]={-0.5,1.45},["size"]=17,["text"]="c[0]"}
refs[11] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-10",["layer"]=40,["point"]={-5.28,0.59},["size"]=21,["text"]="C1(*p)"}
refs[12] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-11",["layer"]=40,["point"]={-3.01,0.59},["size"]=23,["text"]="+"}
refs[13] = scene:rectangle {["center"]={-1.65,0.59},["fill"]="#ffffff",["id"]="simd-12",["layer"]=15,["size"]={1.72,0.58},["stroke"]="#bcbcbc",["width"]=1.3}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-13",["layer"]=40,["point"]={-0.5,0.59},["size"]=17,["text"]="c[1]"}
refs[15] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-14",["layer"]=40,["point"]={-5.28,-0.27},["size"]=21,["text"]="C2(*p)"}
refs[16] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-15",["layer"]=40,["point"]={-3.01,-0.27},["size"]=23,["text"]="+"}
refs[17] = scene:rectangle {["center"]={-1.65,-0.27},["fill"]="#ffffff",["id"]="simd-16",["layer"]=15,["size"]={1.72,0.58},["stroke"]="#bcbcbc",["width"]=1.3}
refs[18] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-17",["layer"]=40,["point"]={-0.5,-0.27},["size"]=17,["text"]="c[2]"}
refs[19] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-18",["layer"]=40,["point"]={-5.28,-1.13},["size"]=21,["text"]="C3(*p)"}
refs[20] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-19",["layer"]=40,["point"]={-3.01,-1.13},["size"]=23,["text"]="+"}
refs[21] = scene:rectangle {["center"]={-1.65,-1.13},["fill"]="#ffffff",["id"]="simd-20",["layer"]=15,["size"]={1.72,0.58},["stroke"]="#bcbcbc",["width"]=1.3}
refs[22] = scene:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-21",["layer"]=40,["point"]={-0.5,-1.13},["size"]=17,["text"]="c[3]"}
refs[23] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-22",["layer"]=40,["point"]={3.1,2.21},["size"]=19,["text"]="vdup_n_u32 → vreinterpret_u8_u32"}
refs[24] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-23",["layer"]=40,["point"]={0.7,1.76},["size"]=15,["text"]="C3"}
refs[25] = scene:rectangle {["center"]={0.7,1.37},["fill"]="#ffffff",["id"]="simd-24",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[26] = scene:route {["dash"]={5,4},["id"]="simd-25",["layer"]=8,["points"]={{0.7,0.95},{0.7,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[27] = scene:rectangle {["center"]={0.7,-0.09},["fill"]="#ffffff",["id"]="simd-26",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[28] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-27",["layer"]=40,["point"]={1.4,1.76},["size"]=15,["text"]="C2"}
refs[29] = scene:rectangle {["center"]={1.4,1.37},["fill"]="#ffffff",["id"]="simd-28",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[30] = scene:route {["dash"]={5,4},["id"]="simd-29",["layer"]=8,["points"]={{1.4,0.95},{1.4,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[31] = scene:rectangle {["center"]={1.4,-0.09},["fill"]="#ffffff",["id"]="simd-30",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[32] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-31",["layer"]=40,["point"]={2.1,1.76},["size"]=15,["text"]="C1"}
refs[33] = scene:rectangle {["center"]={2.1,1.37},["fill"]="#ffffff",["id"]="simd-32",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[34] = scene:route {["dash"]={5,4},["id"]="simd-33",["layer"]=8,["points"]={{2.1,0.95},{2.1,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[35] = scene:rectangle {["center"]={2.1,-0.09},["fill"]="#ffffff",["id"]="simd-34",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[36] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-35",["layer"]=40,["point"]={2.8,1.76},["size"]=15,["text"]="A"}
refs[37] = scene:rectangle {["center"]={2.8,1.37},["fill"]="#ffffff",["id"]="simd-36",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[38] = scene:route {["dash"]={5,4},["id"]="simd-37",["layer"]=8,["points"]={{2.8,0.95},{2.8,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[39] = scene:rectangle {["center"]={2.8,-0.09},["fill"]="#ffffff",["id"]="simd-38",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[40] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-39",["layer"]=40,["point"]={3.5,1.76},["size"]=15,["text"]="C3"}
refs[41] = scene:rectangle {["center"]={3.5,1.37},["fill"]="#ffffff",["id"]="simd-40",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[42] = scene:route {["dash"]={5,4},["id"]="simd-41",["layer"]=8,["points"]={{3.5,0.95},{3.5,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[43] = scene:rectangle {["center"]={3.5,-0.09},["fill"]="#ffffff",["id"]="simd-42",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[44] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-43",["layer"]=40,["point"]={4.2,1.76},["size"]=15,["text"]="C2"}
refs[45] = scene:rectangle {["center"]={4.2,1.37},["fill"]="#ffffff",["id"]="simd-44",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[46] = scene:route {["dash"]={5,4},["id"]="simd-45",["layer"]=8,["points"]={{4.2,0.95},{4.2,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[47] = scene:rectangle {["center"]={4.2,-0.09},["fill"]="#ffffff",["id"]="simd-46",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[48] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-47",["layer"]=40,["point"]={4.9,1.76},["size"]=15,["text"]="C1"}
refs[49] = scene:rectangle {["center"]={4.9,1.37},["fill"]="#ffffff",["id"]="simd-48",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[50] = scene:route {["dash"]={5,4},["id"]="simd-49",["layer"]=8,["points"]={{4.9,0.95},{4.9,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[51] = scene:rectangle {["center"]={4.9,-0.09},["fill"]="#ffffff",["id"]="simd-50",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[52] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-51",["layer"]=40,["point"]={5.6,1.76},["size"]=15,["text"]="A"}
refs[53] = scene:rectangle {["center"]={5.6,1.37},["fill"]="#ffffff",["id"]="simd-52",["layer"]=15,["size"]={0.7,0.56},["stroke"]="#bcbcbc",["width"]=1.3}
refs[54] = scene:route {["dash"]={5,4},["id"]="simd-53",["layer"]=8,["points"]={{5.6,0.95},{5.6,0.35}},["stroke"]="#202020",["tip"]=8,["width"]=1.5}
refs[55] = scene:rectangle {["center"]={5.6,-0.09},["fill"]="#ffffff",["id"]="simd-54",["layer"]=15,["size"]={0.7,0.64},["stroke"]="#bcbcbc",["width"]=1.3}
refs[56] = scene:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-55",["layer"]=40,["point"]={3.1,-0.73},["size"]=22,["text"]="uint16x8_t sum"}
refs[57] = scene:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-56",["layer"]=40,["point"]={3.1,-1.21},["size"]=20,["text"]="vaddw_u8 · 8 → 16 bits"}
refs[58] = scene:group {["id"]="simd-57",["opacity"]=0}
refs[59] = refs[58]:rectangle {["center"]={1.75,-0.09},["fill"]="#00000000",["id"]="simd-58",["layer"]=15,["size"]={2.8,0.88},["stroke"]="#1f66c4",["width"]=1.3}
refs[60] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-59",["layer"]=40,["point"]={1.75,-1.8},["size"]=18,["text"]="low 4 lanes"}
refs[61] = refs[58]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-60",["layer"]=40,["point"]={4.55,-1.8},["size"]=18,["text"]="duplicate half"}
refs[62] = scene:line {["from"]={-5.76,-2.17},["id"]="simd-61",["layer"]=5,["stroke"]="#cccccc",["to"]={5.76,-2.17},["width"]=1}
refs[63] = scene:group {["id"]="simd-62",["opacity"]=1}
refs[64] = refs[63]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-63",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="0"}
refs[65] = scene:group {["id"]="simd-64",["opacity"]=1}
refs[66] = refs[65]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-65",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="0"}
refs[67] = scene:group {["id"]="simd-66",["opacity"]=1}
refs[68] = refs[67]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-67",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="0"}
refs[69] = scene:group {["id"]="simd-68",["opacity"]=1}
refs[70] = refs[69]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-69",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="0"}
refs[71] = scene:group {["id"]="simd-70",["opacity"]=1}
refs[72] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-71",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="0"}
refs[73] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-72",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="0"}
refs[74] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-73",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="0"}
refs[75] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-74",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="0"}
refs[76] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-75",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="0"}
refs[77] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-76",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="0"}
refs[78] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-77",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="0"}
refs[79] = refs[71]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-78",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="0"}
refs[80] = scene:group {["id"]="simd-79",["opacity"]=1}
refs[81] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-80",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE8F3FB"}
refs[82] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-81",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE8F3FB"}
refs[83] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-82",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="1 / 9"}
refs[84] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-83",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[85] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-84",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="232"}
refs[86] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-85",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="243"}
refs[87] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-86",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="251"}
refs[88] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-87",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="251"}
refs[89] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-88",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="243"}
refs[90] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-89",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="232"}
refs[91] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-90",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[92] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-91",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="251"}
refs[93] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-92",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="243"}
refs[94] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-93",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="232"}
refs[95] = refs[80]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-94",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
scene:wait(1)
refs[96] = scene:group {["id"]="simd-95",["opacity"]=0}
refs[97] = refs[96]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-96",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="255"}
refs[98] = scene:group {["id"]="simd-97",["opacity"]=0}
refs[99] = refs[98]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-98",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="232"}
refs[100] = scene:group {["id"]="simd-99",["opacity"]=0}
refs[101] = refs[100]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-100",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="243"}
refs[102] = scene:group {["id"]="simd-101",["opacity"]=0}
refs[103] = refs[102]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-102",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="251"}
refs[104] = scene:group {["id"]="simd-103",["opacity"]=0}
refs[105] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-104",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="251"}
refs[106] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-105",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="243"}
refs[107] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-106",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="232"}
refs[108] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-107",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="255"}
refs[109] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-108",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="251"}
refs[110] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-109",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="243"}
refs[111] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-110",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="232"}
refs[112] = refs[104]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-111",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="255"}
scene:play({{target=refs[63],opacity=0},{target=refs[65],opacity=0},{target=refs[67],opacity=0},{target=refs[69],opacity=0},{target=refs[71],opacity=0},{target=refs[96],opacity=1},{target=refs[98],opacity=1},{target=refs[100],opacity=1},{target=refs[102],opacity=1},{target=refs[104],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[113] = scene:group {["id"]="simd-112",["opacity"]=0}
refs[114] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-113",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[115] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-114",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[116] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-115",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="2 / 9"}
refs[117] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-116",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[118] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-117",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[119] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-118",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[120] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-119",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[121] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-120",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[122] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-121",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[123] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-122",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[124] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-123",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[125] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-124",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[126] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-125",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[127] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-126",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[128] = refs[113]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-127",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[129] = scene:group {["id"]="simd-128",["opacity"]=0}
refs[130] = refs[129]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-129",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="510"}
refs[131] = scene:group {["id"]="simd-130",["opacity"]=0}
refs[132] = refs[131]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-131",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="462"}
refs[133] = scene:group {["id"]="simd-132",["opacity"]=0}
refs[134] = refs[133]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-133",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="340"}
refs[135] = scene:group {["id"]="simd-134",["opacity"]=0}
refs[136] = refs[135]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-135",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="284"}
refs[137] = scene:group {["id"]="simd-136",["opacity"]=0}
refs[138] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-137",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="284"}
refs[139] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-138",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="340"}
refs[140] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-139",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="462"}
refs[141] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-140",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="510"}
refs[142] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-141",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="284"}
refs[143] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-142",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="340"}
refs[144] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-143",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="462"}
refs[145] = refs[137]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-144",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="510"}
scene:play({{target=refs[96],opacity=0},{target=refs[98],opacity=0},{target=refs[100],opacity=0},{target=refs[102],opacity=0},{target=refs[104],opacity=0},{target=refs[80],opacity=0},{target=refs[129],opacity=1},{target=refs[131],opacity=1},{target=refs[133],opacity=1},{target=refs[135],opacity=1},{target=refs[137],opacity=1},{target=refs[113],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[146] = scene:group {["id"]="simd-145",["opacity"]=0}
refs[147] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-146",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[148] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-147",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[149] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-148",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="3 / 9"}
refs[150] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-149",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[151] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-150",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[152] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-151",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[153] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-152",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[154] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-153",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[155] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-154",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[156] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-155",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[157] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-156",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[158] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-157",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[159] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-158",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[160] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-159",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[161] = refs[146]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-160",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[162] = scene:group {["id"]="simd-161",["opacity"]=0}
refs[163] = refs[162]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-162",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="765"}
refs[164] = scene:group {["id"]="simd-163",["opacity"]=0}
refs[165] = refs[164]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-164",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="692"}
refs[166] = scene:group {["id"]="simd-165",["opacity"]=0}
refs[167] = refs[166]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-166",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="437"}
refs[168] = scene:group {["id"]="simd-167",["opacity"]=0}
refs[169] = refs[168]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-168",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="317"}
refs[170] = scene:group {["id"]="simd-169",["opacity"]=0}
refs[171] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-170",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="317"}
refs[172] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-171",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="437"}
refs[173] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-172",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="692"}
refs[174] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-173",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="765"}
refs[175] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-174",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="317"}
refs[176] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-175",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="437"}
refs[177] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-176",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="692"}
refs[178] = refs[170]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-177",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="765"}
scene:play({{target=refs[129],opacity=0},{target=refs[131],opacity=0},{target=refs[133],opacity=0},{target=refs[135],opacity=0},{target=refs[137],opacity=0},{target=refs[113],opacity=0},{target=refs[162],opacity=1},{target=refs[164],opacity=1},{target=refs[166],opacity=1},{target=refs[168],opacity=1},{target=refs[170],opacity=1},{target=refs[146],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[179] = scene:group {["id"]="simd-178",["opacity"]=0}
refs[180] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-179",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[181] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-180",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[182] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-181",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="4 / 9"}
refs[183] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-182",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[184] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-183",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[185] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-184",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[186] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-185",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[187] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-186",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[188] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-187",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[189] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-188",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[190] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-189",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[191] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-190",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[192] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-191",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[193] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-192",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[194] = refs[179]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-193",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[195] = scene:group {["id"]="simd-194",["opacity"]=0}
refs[196] = refs[195]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-195",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="1020"}
refs[197] = scene:group {["id"]="simd-196",["opacity"]=0}
refs[198] = refs[197]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-197",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="922"}
refs[199] = scene:group {["id"]="simd-198",["opacity"]=0}
refs[200] = refs[199]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-199",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="534"}
refs[201] = scene:group {["id"]="simd-200",["opacity"]=0}
refs[202] = refs[201]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-201",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="350"}
refs[203] = scene:group {["id"]="simd-202",["opacity"]=0}
refs[204] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-203",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="350"}
refs[205] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-204",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="534"}
refs[206] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-205",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="922"}
refs[207] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-206",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="1020"}
refs[208] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-207",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="350"}
refs[209] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-208",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="534"}
refs[210] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-209",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="922"}
refs[211] = refs[203]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-210",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="1020"}
scene:play({{target=refs[162],opacity=0},{target=refs[164],opacity=0},{target=refs[166],opacity=0},{target=refs[168],opacity=0},{target=refs[170],opacity=0},{target=refs[146],opacity=0},{target=refs[195],opacity=1},{target=refs[197],opacity=1},{target=refs[199],opacity=1},{target=refs[201],opacity=1},{target=refs[203],opacity=1},{target=refs[179],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[212] = scene:group {["id"]="simd-211",["opacity"]=0}
refs[213] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-212",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[214] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-213",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[215] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-214",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="5 / 9"}
refs[216] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-215",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[217] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-216",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[218] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-217",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[219] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-218",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[220] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-219",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[221] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-220",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[222] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-221",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[223] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-222",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[224] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-223",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[225] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-224",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[226] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-225",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[227] = refs[212]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-226",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[228] = scene:group {["id"]="simd-227",["opacity"]=0}
refs[229] = refs[228]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-228",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="1275"}
refs[230] = scene:group {["id"]="simd-229",["opacity"]=0}
refs[231] = refs[230]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-230",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="1152"}
refs[232] = scene:group {["id"]="simd-231",["opacity"]=0}
refs[233] = refs[232]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-232",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="631"}
refs[234] = scene:group {["id"]="simd-233",["opacity"]=0}
refs[235] = refs[234]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-234",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="383"}
refs[236] = scene:group {["id"]="simd-235",["opacity"]=0}
refs[237] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-236",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="383"}
refs[238] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-237",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="631"}
refs[239] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-238",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="1152"}
refs[240] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-239",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="1275"}
refs[241] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-240",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="383"}
refs[242] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-241",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="631"}
refs[243] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-242",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="1152"}
refs[244] = refs[236]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-243",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="1275"}
scene:play({{target=refs[195],opacity=0},{target=refs[197],opacity=0},{target=refs[199],opacity=0},{target=refs[201],opacity=0},{target=refs[203],opacity=0},{target=refs[179],opacity=0},{target=refs[228],opacity=1},{target=refs[230],opacity=1},{target=refs[232],opacity=1},{target=refs[234],opacity=1},{target=refs[236],opacity=1},{target=refs[212],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[245] = scene:group {["id"]="simd-244",["opacity"]=0}
refs[246] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-245",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[247] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-246",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[248] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-247",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="6 / 9"}
refs[249] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-248",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[250] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-249",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[251] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-250",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[252] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-251",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[253] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-252",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[254] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-253",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[255] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-254",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[256] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-255",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[257] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-256",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[258] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-257",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[259] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-258",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[260] = refs[245]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-259",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[261] = scene:group {["id"]="simd-260",["opacity"]=0}
refs[262] = refs[261]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-261",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="1530"}
refs[263] = scene:group {["id"]="simd-262",["opacity"]=0}
refs[264] = refs[263]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-263",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="1382"}
refs[265] = scene:group {["id"]="simd-264",["opacity"]=0}
refs[266] = refs[265]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-265",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="728"}
refs[267] = scene:group {["id"]="simd-266",["opacity"]=0}
refs[268] = refs[267]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-267",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="416"}
refs[269] = scene:group {["id"]="simd-268",["opacity"]=0}
refs[270] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-269",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="416"}
refs[271] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-270",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="728"}
refs[272] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-271",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="1382"}
refs[273] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-272",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="1530"}
refs[274] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-273",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="416"}
refs[275] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-274",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="728"}
refs[276] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-275",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="1382"}
refs[277] = refs[269]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-276",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="1530"}
scene:play({{target=refs[228],opacity=0},{target=refs[230],opacity=0},{target=refs[232],opacity=0},{target=refs[234],opacity=0},{target=refs[236],opacity=0},{target=refs[212],opacity=0},{target=refs[261],opacity=1},{target=refs[263],opacity=1},{target=refs[265],opacity=1},{target=refs[267],opacity=1},{target=refs[269],opacity=1},{target=refs[245],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[278] = scene:group {["id"]="simd-277",["opacity"]=0}
refs[279] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-278",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[280] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-279",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[281] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-280",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="7 / 9"}
refs[282] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-281",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[283] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-282",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[284] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-283",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[285] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-284",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[286] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-285",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[287] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-286",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[288] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-287",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[289] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-288",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[290] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-289",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[291] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-290",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[292] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-291",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[293] = refs[278]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-292",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[294] = scene:group {["id"]="simd-293",["opacity"]=0}
refs[295] = refs[294]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-294",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="1785"}
refs[296] = scene:group {["id"]="simd-295",["opacity"]=0}
refs[297] = refs[296]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-296",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="1612"}
refs[298] = scene:group {["id"]="simd-297",["opacity"]=0}
refs[299] = refs[298]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-298",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="825"}
refs[300] = scene:group {["id"]="simd-299",["opacity"]=0}
refs[301] = refs[300]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-300",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="449"}
refs[302] = scene:group {["id"]="simd-301",["opacity"]=0}
refs[303] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-302",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="449"}
refs[304] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-303",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="825"}
refs[305] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-304",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="1612"}
refs[306] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-305",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="1785"}
refs[307] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-306",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="449"}
refs[308] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-307",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="825"}
refs[309] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-308",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="1612"}
refs[310] = refs[302]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-309",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="1785"}
scene:play({{target=refs[261],opacity=0},{target=refs[263],opacity=0},{target=refs[265],opacity=0},{target=refs[267],opacity=0},{target=refs[269],opacity=0},{target=refs[245],opacity=0},{target=refs[294],opacity=1},{target=refs[296],opacity=1},{target=refs[298],opacity=1},{target=refs[300],opacity=1},{target=refs[302],opacity=1},{target=refs[278],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[311] = scene:group {["id"]="simd-310",["opacity"]=0}
refs[312] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-311",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[313] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-312",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[314] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-313",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="8 / 9"}
refs[315] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-314",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[316] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-315",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[317] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-316",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[318] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-317",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[319] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-318",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[320] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-319",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[321] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-320",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[322] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-321",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[323] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-322",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[324] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-323",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[325] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-324",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[326] = refs[311]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-325",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[327] = scene:group {["id"]="simd-326",["opacity"]=0}
refs[328] = refs[327]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-327",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="2040"}
refs[329] = scene:group {["id"]="simd-328",["opacity"]=0}
refs[330] = refs[329]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-329",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="1842"}
refs[331] = scene:group {["id"]="simd-330",["opacity"]=0}
refs[332] = refs[331]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-331",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="922"}
refs[333] = scene:group {["id"]="simd-332",["opacity"]=0}
refs[334] = refs[333]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-333",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="482"}
refs[335] = scene:group {["id"]="simd-334",["opacity"]=0}
refs[336] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-335",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="482"}
refs[337] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-336",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="922"}
refs[338] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-337",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="1842"}
refs[339] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-338",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="2040"}
refs[340] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-339",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="482"}
refs[341] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-340",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="922"}
refs[342] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-341",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="1842"}
refs[343] = refs[335]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-342",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="2040"}
scene:play({{target=refs[294],opacity=0},{target=refs[296],opacity=0},{target=refs[298],opacity=0},{target=refs[300],opacity=0},{target=refs[302],opacity=0},{target=refs[278],opacity=0},{target=refs[327],opacity=1},{target=refs[329],opacity=1},{target=refs[331],opacity=1},{target=refs[333],opacity=1},{target=refs[335],opacity=1},{target=refs[311],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
refs[344] = scene:group {["id"]="simd-343",["opacity"]=0}
refs[345] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-344",["layer"]=40,["point"]={-3.2,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[346] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-345",["layer"]=40,["point"]={3.1,2.99},["size"]=25,["text"]="0xFFE66121"}
refs[347] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-346",["layer"]=40,["point"]={0,4.5},["size"]=20,["text"]="9 / 9"}
refs[348] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-347",["layer"]=40,["point"]={-3.92,1.45},["size"]=22,["text"]="255"}
refs[349] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-348",["layer"]=40,["point"]={-3.92,0.59},["size"]=22,["text"]="230"}
refs[350] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-349",["layer"]=40,["point"]={-3.92,-0.27},["size"]=22,["text"]="97"}
refs[351] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-350",["layer"]=40,["point"]={-3.92,-1.13},["size"]=22,["text"]="33"}
refs[352] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-351",["layer"]=40,["point"]={0.7,1.37},["size"]=16,["text"]="33"}
refs[353] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-352",["layer"]=40,["point"]={1.4,1.37},["size"]=16,["text"]="97"}
refs[354] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-353",["layer"]=40,["point"]={2.1,1.37},["size"]=16,["text"]="230"}
refs[355] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-354",["layer"]=40,["point"]={2.8,1.37},["size"]=16,["text"]="255"}
refs[356] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-355",["layer"]=40,["point"]={3.5,1.37},["size"]=16,["text"]="33"}
refs[357] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-356",["layer"]=40,["point"]={4.2,1.37},["size"]=16,["text"]="97"}
refs[358] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-357",["layer"]=40,["point"]={4.9,1.37},["size"]=16,["text"]="230"}
refs[359] = refs[344]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-358",["layer"]=40,["point"]={5.6,1.37},["size"]=16,["text"]="255"}
refs[360] = scene:group {["id"]="simd-359",["opacity"]=0}
refs[361] = refs[360]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-360",["layer"]=40,["point"]={-1.65,1.45},["size"]=22,["text"]="2295"}
refs[362] = scene:group {["id"]="simd-361",["opacity"]=0}
refs[363] = refs[362]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-362",["layer"]=40,["point"]={-1.65,0.59},["size"]=22,["text"]="2072"}
refs[364] = scene:group {["id"]="simd-363",["opacity"]=0}
refs[365] = refs[364]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-364",["layer"]=40,["point"]={-1.65,-0.27},["size"]=22,["text"]="1019"}
refs[366] = scene:group {["id"]="simd-365",["opacity"]=0}
refs[367] = refs[366]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-366",["layer"]=40,["point"]={-1.65,-1.13},["size"]=22,["text"]="515"}
refs[368] = scene:group {["id"]="simd-367",["opacity"]=0}
refs[369] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-368",["layer"]=40,["point"]={0.7,-0.09},["size"]=15,["text"]="515"}
refs[370] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-369",["layer"]=40,["point"]={1.4,-0.09},["size"]=15,["text"]="1019"}
refs[371] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-370",["layer"]=40,["point"]={2.1,-0.09},["size"]=15,["text"]="2072"}
refs[372] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-371",["layer"]=40,["point"]={2.8,-0.09},["size"]=15,["text"]="2295"}
refs[373] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-372",["layer"]=40,["point"]={3.5,-0.09},["size"]=15,["text"]="515"}
refs[374] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-373",["layer"]=40,["point"]={4.2,-0.09},["size"]=15,["text"]="1019"}
refs[375] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-374",["layer"]=40,["point"]={4.9,-0.09},["size"]=15,["text"]="2072"}
refs[376] = refs[368]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-375",["layer"]=40,["point"]={5.6,-0.09},["size"]=15,["text"]="2295"}
scene:play({{target=refs[327],opacity=0},{target=refs[329],opacity=0},{target=refs[331],opacity=0},{target=refs[333],opacity=0},{target=refs[335],opacity=0},{target=refs[311],opacity=0},{target=refs[360],opacity=1},{target=refs[362],opacity=1},{target=refs[364],opacity=1},{target=refs[366],opacity=1},{target=refs[368],opacity=1},{target=refs[344],opacity=1}},0.000001,"ease_in_out",0)
scene:wait(0.22)
scene:play({{target=refs[58],opacity=1}},0.3,"ease_in_out",0)
scene:wait(1)
refs[377] = scene:group {["id"]="simd-376",["opacity"]=0}
refs[378] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-377",["layer"]=40,["point"]={-3.2,-2.5},["size"]=21,["text"]="c[4]"}
refs[379] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-378",["layer"]=40,["point"]={3.1,-2.5},["size"]=19,["text"]="sum → low → reverse → widen → c[4]"}
refs[380] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-379",["layer"]=40,["point"]={-4.94,-2.9},["size"]=15,["text"]="A"}
refs[381] = refs[377]:rectangle {["center"]={-4.94,-3.29},["fill"]="#ffffff",["id"]="simd-380",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[382] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-381",["layer"]=40,["point"]={-4.94,-3.29},["size"]=21,["text"]="2295"}
refs[383] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-382",["layer"]=40,["point"]={-3.78,-2.9},["size"]=15,["text"]="C1"}
refs[384] = refs[377]:rectangle {["center"]={-3.78,-3.29},["fill"]="#ffffff",["id"]="simd-383",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[385] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-384",["layer"]=40,["point"]={-3.78,-3.29},["size"]=21,["text"]="2072"}
refs[386] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-385",["layer"]=40,["point"]={-2.62,-2.9},["size"]=15,["text"]="C2"}
refs[387] = refs[377]:rectangle {["center"]={-2.62,-3.29},["fill"]="#ffffff",["id"]="simd-386",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[388] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-387",["layer"]=40,["point"]={-2.62,-3.29},["size"]=21,["text"]="1019"}
refs[389] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-388",["layer"]=40,["point"]={-1.46,-2.9},["size"]=15,["text"]="C3"}
refs[390] = refs[377]:rectangle {["center"]={-1.46,-3.29},["fill"]="#ffffff",["id"]="simd-389",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[391] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#e66121",["font"]="Pretendard",["id"]="simd-390",["layer"]=40,["point"]={-1.46,-3.29},["size"]=21,["text"]="515"}
refs[392] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-391",["layer"]=40,["point"]={1.36,-2.9},["size"]=15,["text"]="A"}
refs[393] = refs[377]:rectangle {["center"]={1.36,-3.29},["fill"]="#ffffff",["id"]="simd-392",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[394] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-393",["layer"]=40,["point"]={1.36,-3.29},["size"]=21,["text"]="2295"}
refs[395] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-394",["layer"]=40,["point"]={2.52,-2.9},["size"]=15,["text"]="C1"}
refs[396] = refs[377]:rectangle {["center"]={2.52,-3.29},["fill"]="#ffffff",["id"]="simd-395",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[397] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-396",["layer"]=40,["point"]={2.52,-3.29},["size"]=21,["text"]="2072"}
refs[398] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-397",["layer"]=40,["point"]={3.68,-2.9},["size"]=15,["text"]="C2"}
refs[399] = refs[377]:rectangle {["center"]={3.68,-3.29},["fill"]="#ffffff",["id"]="simd-398",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[400] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-399",["layer"]=40,["point"]={3.68,-3.29},["size"]=21,["text"]="1019"}
refs[401] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-400",["layer"]=40,["point"]={4.84,-2.9},["size"]=15,["text"]="C3"}
refs[402] = refs[377]:rectangle {["center"]={4.84,-3.29},["fill"]="#ffffff",["id"]="simd-401",["layer"]=15,["size"]={1.06,0.54},["stroke"]="#bcbcbc",["width"]=1.3}
refs[403] = refs[377]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-402",["layer"]=40,["point"]={4.84,-3.29},["size"]=21,["text"]="515"}
scene:play({{target=refs[377],opacity=1}},0.6,"ease_in_out",0)
scene:wait(1)
refs[404] = scene:group {["id"]="simd-403",["opacity"]=0}
refs[405] = scene:group {["id"]="simd-404",["opacity"]=0}
refs[406] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-405",["layer"]=40,["point"]={-3.2,-3.88},["size"]=21,["text"]="c[i] / 9"}
refs[407] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-406",["layer"]=40,["point"]={-4.94,-4.29},["size"]=21,["text"]="255"}
refs[408] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-407",["layer"]=40,["point"]={-3.78,-4.29},["size"]=21,["text"]="230"}
refs[409] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-408",["layer"]=40,["point"]={-2.62,-4.29},["size"]=21,["text"]="113"}
refs[410] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-409",["layer"]=40,["point"]={-1.46,-4.29},["size"]=21,["text"]="57"}
refs[411] = refs[405]:rectangle {["center"]={-4.5,-4.9},["fill"]="#e67139",["id"]="simd-410",["layer"]=15,["size"]={0.4,0.4},["stroke"]="#202020",["width"]=1.3}
refs[412] = refs[405]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-411",["layer"]=40,["point"]={-2.95,-4.9},["size"]=23,["text"]="0xFFE67139"}
refs[413] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#737373",["font"]="Pretendard",["id"]="simd-412",["layer"]=40,["point"]={3.1,-3.88},["size"]=21,["text"]="c[i] / 9"}
refs[414] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-413",["layer"]=40,["point"]={1.36,-4.29},["size"]=21,["text"]="255"}
refs[415] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-414",["layer"]=40,["point"]={2.52,-4.29},["size"]=21,["text"]="230"}
refs[416] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-415",["layer"]=40,["point"]={3.68,-4.29},["size"]=21,["text"]="113"}
refs[417] = refs[404]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="simd-416",["layer"]=40,["point"]={4.84,-4.29},["size"]=21,["text"]="57"}
refs[418] = refs[405]:rectangle {["center"]={1.8,-4.9},["fill"]="#e67139",["id"]="simd-417",["layer"]=15,["size"]={0.4,0.4},["stroke"]="#202020",["width"]=1.3}
refs[419] = refs[405]:text {["align"]={0.5,0.5},["fill"]="#1f66c4",["font"]="Pretendard",["id"]="simd-418",["layer"]=40,["point"]={3.35,-4.9},["size"]=23,["text"]="0xFFE67139"}
scene:play({{target=refs[404],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1)
scene:play({{target=refs[405],opacity=1}},0.45,"ease_in_out",0)
scene:wait(1)
scene:wait(0.8)
return scene
