import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {hex,model,radialAt,revision} from '../public/tmath/gl-fill/model.mjs';
import {createTMath,compileScene} from '../public/tmath/runtime/client.js';
import {buildOverview} from '../public/tmath/gl-fill/overview.mjs';
import {buildRepeatAA} from '../public/tmath/gl-fill/repeat-aa.mjs';
const root=path.resolve(import.meta.dirname,'..'),output=path.join(root,'public/tmath/gl-fill');
const temp=process.env.GL_FILL_REVIEW_DIR || '/tmp/thorvg-gl-fill-review';
await fs.mkdir(temp,{recursive:true});
const variant=process.argv.includes('--variant');
const repeatAA=process.argv.includes('--repeat-aa'),assetName=repeatAA?'repeat-aa':'overview';
const captureDir=variant?temp:output,name=variant?'variant':'example';
const capture=JSON.parse(await fs.readFile(path.join(captureDir,name+'.json'),'utf8'));
if(capture.revision!==revision)throw Error('Native capture revision differs from model');
const nativeModel=model({scale:capture.scale});let nativeChecks=0;
for(const [i,c] of nativeModel.cases.entries())for(let y=0;y<capture.crop.height;y++)for(let x=0;x<capture.crop.width;x++){
 const expected=capture.cases[i].cropPixels[y*capture.crop.width+x];
 const actual=radialAt(c,[c.offset[0]+capture.crop.x+x+.5,c.offset[1]+capture.crop.y+y+.5]).premultiplied;
 if(actual.some((v,k)=>Math.abs(Math.round(v)-expected[k])>2))throw Error('Native shader/capture mismatch');nativeChecks++;
}
const thumbnails=await Promise.all(capture.cases.map(async (_,i)=>{
 const {data,info}=await sharp(path.join(captureDir,name+'.png')).extract({left:16+i*528,top:16,width:512,height:512}).resize(128,128).ensureAlpha().raw().toBuffer({resolveWithObject:true});
 return {width:info.width,height:info.height,pixels:Array.from({length:info.width*info.height},(_,j)=>hex([...data.subarray(j*4,j*4+4)]))};
}));
const build=(still=false)=>(repeatAA?buildRepeatAA:buildOverview)(capture,thumbnails,{scale:capture.scale},{still});
const episode=build();
const quick=process.argv.includes('--quick')||process.argv.includes('--still');
const reviewName=variant?(repeatAA?'repeat-aa-variant':'variant'):assetName;
const compile=e=>`-- Generated by scripts/render-gl-fill.mjs; edit ${assetName}.mjs.\nlocal refs = {}\n`+compileScene(e.scene).replace(/^local (object\d+) = /gm,'$1 = ').replace(/\bobject(\d+)\b/g,'refs[$1]');
const source=compile(episode);
const runtime=await createTMath('return tmath.scene {}','bootstrap.lua',{renderEngine:'cpu',wasmBinary:await fs.readFile(path.join(root,'public/tmath/runtime/tmath-wasm.wasm'))});
const intersects=(a,b)=>a.x<b.x+b.width+4&&a.x+a.width+4>b.x&&a.y<b.y+b.height+4&&a.y+a.height+4>b.y;
try {
  runtime.font('Pretendard',await fs.readFile(path.join(root,'public/tmath/runtime/Pretendard.ttf')),'ttf');
  runtime.loadLua(source,'gl-fill.lua');
  const [width,height]=runtime.size(),errors=new Set(),seen=new Set(),frames=Math.ceil(runtime.duration*30);
  const times=quick?[0,2,4,6,runtime.duration]:Array.from({length:frames+1},(_,i)=>Math.min(i/30,runtime.duration));
  function audit(e,time) {
    const report=runtime.layoutReport(time,4);
    const texts=report.objects.filter(o=>o.type==='text'&&o.visible&&o.paintBounds?.width>0);
    const objects=new Map(report.objects.map(o=>[o.id,o]));
    if(texts.length!==e.textIds.length)errors.add('Explanatory text hidden');
    for(const t of texts) {
      const b=t.paintBounds,policy=e.textPolicies[t.id];seen.add(t.id);
      for(const region of e.imageRegions)if(intersects(b,region))errors.add('Text/grid overlap: '+t.id);
      if(!policy)errors.add('Missing policy: '+t.id);
      if(b.x<4||b.y<4||b.x+b.width>width-4||b.y+b.height>height-4||t.clipped)errors.add('Clipped text: '+t.id);
      if(policy?.owner) {
        const owner=objects.get(policy.owner)?.paintBounds,n=policy.inset;
        if(!owner||b.x<owner.x+n||b.y<owner.y+n||b.x+b.width>owner.x+owner.width-n||b.y+b.height>owner.y+owner.height-n)errors.add('Containment: '+t.id);
      }
    }
    for(let a=0;a<texts.length;a++)for(let b=a+1;b<texts.length;b++)if(intersects(texts[a].paintBounds,texts[b].paintBounds))errors.add('Text overlap: '+texts[a].id+' / '+texts[b].id);
    // Fixed pipeline connectors must stay clear of explanatory text.
    for(const route of e.routes) {
      if(!objects.get(route.id)?.visible)continue;
      for(let i=1;i<route.points.length;i++) {
        const a=route.points[i-1],b=route.points[i];
        for(const text of texts) {
          const q=text.paintBounds,gap=4;
          const hit=a[0]===b[0]
            ? a[0]>q.x-gap && a[0]<q.x+q.width+gap && Math.max(a[1],b[1])>q.y-gap && Math.min(a[1],b[1])<q.y+q.height+gap
            : a[1]===b[1] && a[1]>q.y-gap && a[1]<q.y+q.height+gap && Math.max(a[0],b[0])>q.x-gap && Math.min(a[0],b[0])<q.x+q.width+gap;
          if(hit)errors.add('Route/text overlap: '+route.id+' / '+text.id);
        }
      }
    }
  }
  for(const time of times)audit(episode,time);
  for(const key of episode.textIds)if(!seen.has(key))errors.add('Never visible: '+key);
  for(const check of episode.geometryChecks){
    const b=runtime.layoutReport(check.time,4).objects.find(o=>o.id===check.id)?.paintBounds;
    if(!b||['x','y','width','height'].some(k=>Math.abs(b[k]-check[k])>1))errors.add('Channel geometry: '+check.id);
  }
  function probe(pixels,check){
    const offset=(Math.round(check.y)*width+Math.round(check.x))*4,expected=check.color.slice(1).match(/../g).map(v=>parseInt(v,16));
    if(expected.some((v,i)=>Math.abs(pixels[offset+i]-v)>1))errors.add('Pixel mismatch: '+JSON.stringify(check));
  }
  for(const time of new Set(episode.sampleChecks.map(c=>c.time))){
    const pixels=runtime.render(time,true);
    for(const check of episode.sampleChecks.filter(c=>c.time===time))probe(pixels,check);
  }
  const first=Buffer.from(runtime.render(0,true)),last=Buffer.from(runtime.render(runtime.duration,true));
  if(!first.equals(last))errors.add('Loop seam mismatch');
  const reviews=[...episode.reviewTimes,runtime.duration],regions=episode.regions.map(r=>({...r,states:new Set()})),fixed=[];
  for(const [index,time] of reviews.entries()){
    const pixels=runtime.render(time,true);
    for(const check of episode.pixelChecks.filter(p=>p.fixed))probe(pixels,check);
    for(const r of regions){let hash=2166136261;for(let y=r.y;y<r.y+r.height;y+=3)for(let x=r.x;x<r.x+r.width;x+=3){const offset=(y*width+x)*4;hash=Math.imul(hash^pixels[offset],16777619);hash=Math.imul(hash^pixels[offset+1],16777619);}r.states.add(hash>>>0);}
    for(const [i,r] of episode.fixedRegions.entries()){
      const crop=await sharp(Buffer.from(pixels),{raw:{width,height,channels:4}}).extract({left:r.x,top:r.y,width:r.width,height:r.height}).raw().toBuffer();
      fixed[i]??=crop;if(!fixed[i].equals(crop))errors.add('Final comparison pixels changed');
    }
    await sharp(Buffer.from(pixels),{raw:{width,height,channels:4}}).png().toFile(path.join(temp,`${reviewName}-${index}.png`));
  }
  for(const r of regions)if(r.states.size<3)errors.add('Missing local motion: '+r.name);
  const complete=build(true);runtime.loadLua(compile(complete),'gl-fill-poster.lua');
  audit(complete,0);
  const finalPixels=runtime.render(0,true);
  for(const check of complete.pixelChecks)probe(finalPixels,check);
  await fs.writeFile(path.join(temp,`${reviewName}-layout.json`),JSON.stringify(runtime.layoutReport(0,4)));
  await sharp(Buffer.from(finalPixels),{raw:{width,height,channels:4}}).png().toFile(path.join(temp,`${reviewName}-complete.png`));
  const summary={width,height,duration:runtime.duration,frames:times.length,pixelProbes:complete.pixelChecks.length,nativeChecks,geometryChecks:episode.geometryChecks.length,sampleChecks:episode.sampleChecks.length,errors:[...errors],regions:regions.map(r=>({name:r.name,states:r.states.size})),beats:episode.beats,reviewTimes:reviews};
  await fs.writeFile(path.join(temp,`${reviewName}-audit.json`),JSON.stringify(summary,null,2));
  console.log(JSON.stringify(summary));
  if(errors.size)process.exitCode=1;
  else if(!variant&&!quick){
    await fs.writeFile(path.join(output,`${assetName}.lua`),source);
    await sharp(Buffer.from(finalPixels),{raw:{width,height,channels:4}}).webp({quality:94}).toFile(path.join(output,`${assetName}.webp`));
    // The article now displays only section 07's fixed GL comparison.
    // Exclude the pipeline column and the former animated row-writing strip.
    if(!repeatAA)await sharp(Buffer.from(finalPixels),{raw:{width,height,channels:4}})
      .extract({left:455,top:3060,width:950,height:750})
      .webp({lossless:true}).toFile(path.join(output,'result.webp'));
  }
} finally {runtime.destroy();}
