-- Generated by scripts/render-effect-details.mjs; edit alpha-internal.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=9.8,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=980,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white"},["width"]=1120}
refs[1] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="alpha-internal-0",["layer"]=40,["point"]={-5.1,4.48},["role"]="text",["size"]=28,["text"]="1. Source-over · store RGB × alpha"}
refs[2] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-1",["layer"]=40,["point"]={0,4.15},["role"]="text",["size"]=16,["text"]="C: RGB   A: alpha   s: source   d: destination"}
refs[3] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-2",["layer"]=40,["point"]={-5.1,3.82},["role"]="text",["size"]=21,["text"]="Straight RGB"}
refs[4] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="alpha-internal-3",["layer"]=40,["point"]={0.75,3.82},["role"]="text",["size"]=24,["text"]="Cout = (Cs × As + Cd × Ad × (1 − As)) / Aout"}
refs[5] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-4",["layer"]=40,["point"]={0,3.33},["role"]="text",["size"]=20,["text"]="Aout = As + Ad × (1 − As)     (Aout > 0)"}
refs[6] = scene:group {["id"]="alpha-internal-5",["opacity"]=0}
refs[7] = refs[6]:arrow {["from"]={0,3.05},["id"]="alpha-internal-6",["layer"]=10,["stroke"]="#202020",["tip"]=9,["to"]={0,2.66},["width"]=2}
refs[8] = refs[6]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-7",["layer"]=40,["point"]={2.45,2.86},["role"]="text",["size"]=21,["text"]="Store C'out = Cout × Aout"}
refs[9] = scene:group {["id"]="alpha-internal-8",["opacity"]=0}
refs[10] = refs[9]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="alpha-internal-9",["layer"]=40,["point"]={0,2.26},["role"]="text",["size"]=26,["text"]="C'out = Cs × As + Cd × Ad × (1 − As)"}
refs[11] = scene:group {["id"]="alpha-internal-10",["opacity"]=0}
refs[12] = refs[11]:text {["align"]={0.5,0.5},["fill"]="#23896d",["font"]="Pretendard",["id"]="alpha-internal-11",["layer"]=40,["point"]={0,2.26},["role"]="text",["size"]=28,["text"]="C'out = C's + C'd × (1 − As)"}
refs[13] = refs[11]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-12",["layer"]=40,["point"]={0,1.77},["role"]="text",["size"]=21,["text"]="C's and C'd already contain alpha · no RGB division by Aout"}
refs[14] = scene:line {["from"]={-5.1,1.35},["id"]="alpha-internal-13",["layer"]=5,["stroke"]="#cccccc",["to"]={5.1,1.35},["width"]=1}
refs[15] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="alpha-internal-14",["layer"]=40,["point"]={-5.1,0.95},["role"]="text",["size"]=28,["text"]="2. Filtering · neighboring samples"}
refs[16] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-15",["layer"]=40,["point"]={-3.85,0.32},["role"]="text",["size"]=21,["text"]="Visible pixels"}
refs[17] = scene:rectangle {["center"]={-1.4,0.32},["fill"]="#00ff00",["id"]="alpha-internal-16",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[18] = scene:rectangle {["center"]={-0.425,0.445},["fill"]="#ffffff",["id"]="alpha-internal-17",["layer"]=15,["size"]={0.25,0.25},["stroke"]="#00000000",["width"]=0}
refs[19] = scene:rectangle {["center"]={-0.175,0.445},["fill"]="#dddddd",["id"]="alpha-internal-18",["layer"]=15,["size"]={0.25,0.25},["stroke"]="#00000000",["width"]=0}
refs[20] = scene:rectangle {["center"]={-0.425,0.195},["fill"]="#dddddd",["id"]="alpha-internal-19",["layer"]=15,["size"]={0.25,0.25},["stroke"]="#00000000",["width"]=0}
refs[21] = scene:rectangle {["center"]={-0.175,0.195},["fill"]="#ffffff",["id"]="alpha-internal-20",["layer"]=15,["size"]={0.25,0.25},["stroke"]="#00000000",["width"]=0}
refs[22] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-21",["layer"]=40,["point"]={-1.4,-0.17},["role"]="text",["size"]=18,["text"]="A = 1"}
refs[23] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-22",["layer"]=40,["point"]={-0.3,-0.17},["role"]="text",["size"]=18,["text"]="A = 0"}
refs[24] = scene:group {["id"]="alpha-internal-23",["opacity"]=0}
refs[25] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-24",["layer"]=40,["point"]={-3.85,-0.62},["role"]="text",["size"]=21,["text"]="Stored RGB"}
refs[26] = refs[24]:rectangle {["center"]={-1.4,-0.62},["fill"]="#00ff00",["id"]="alpha-internal-25",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[27] = refs[24]:rectangle {["center"]={-0.3,-0.62},["fill"]="#ff0000",["id"]="alpha-internal-26",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[28] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-27",["layer"]=40,["point"]={2.65,0.28},["role"]="text",["size"]=21,["text"]="Transparent pixels can still store red."}
refs[29] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-28",["layer"]=40,["point"]={2.65,-0.2},["role"]="text",["size"]=19,["text"]="Interpolation / blur mix neighbors."}
refs[30] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-29",["layer"]=40,["point"]={1.9,-0.95},["role"]="text",["size"]=19,["text"]="Channel average"}
refs[31] = refs[24]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-30",["layer"]=40,["point"]={4.2,-0.95},["role"]="text",["size"]=19,["text"]="On white"}
refs[32] = scene:group {["id"]="alpha-internal-31",["opacity"]=0}
refs[33] = refs[32]:text {["align"]={0,0.5},["fill"]="#bc573a",["font"]="Pretendard",["id"]="alpha-internal-32",["layer"]=40,["point"]={-5.1,-1.57},["role"]="text",["size"]=23,["text"]="Straight RGB average"}
refs[34] = refs[32]:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-33",["layer"]=40,["point"]={-5.1,-1.94},["role"]="text",["size"]=18,["text"]="No alpha weighting"}
refs[35] = refs[32]:rectangle {["center"]={-1.4,-1.75},["fill"]="#00ff00",["id"]="alpha-internal-34",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[36] = refs[32]:group {["id"]="alpha-internal-35",["matrix"]={1,0,0,-1.4,0,1,0,-1.75,0,0,1,0,0,0,0,1}}
refs[37] = refs[36]:rectangle {["center"]={0,0},["fill"]="#00ff00",["id"]="alpha-internal-36",["layer"]=25,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[38] = refs[32]:rectangle {["center"]={-0.3,-1.75},["fill"]="#ff0000",["id"]="alpha-internal-37",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[39] = refs[32]:group {["id"]="alpha-internal-38",["matrix"]={1,0,0,-0.3,0,1,0,-1.75,0,0,1,0,0,0,0,1}}
refs[40] = refs[39]:rectangle {["center"]={0,0},["fill"]="#ff0000",["id"]="alpha-internal-39",["layer"]=25,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[41] = refs[32]:arrow {["from"]={0.35,-1.75},["id"]="alpha-internal-40",["layer"]=10,["stroke"]="#202020",["tip"]=9,["to"]={1.3,-1.75},["width"]=2}
refs[42] = refs[32]:arrow {["from"]={2.5,-1.75},["id"]="alpha-internal-41",["layer"]=10,["stroke"]="#202020",["tip"]=9,["to"]={3.6,-1.75},["width"]=2}
refs[43] = scene:group {["id"]="alpha-internal-42",["opacity"]=0}
refs[44] = refs[43]:rectangle {["center"]={1.9,-1.75},["fill"]="#808000",["id"]="alpha-internal-43",["layer"]=15,["size"]={0.8,0.5},["stroke"]="#00000000",["width"]=0}
refs[45] = scene:group {["id"]="alpha-internal-44",["opacity"]=0}
refs[46] = refs[45]:rectangle {["center"]={4.2,-1.75},["fill"]="#bfbf80",["id"]="alpha-internal-45",["layer"]=15,["size"]={0.8,0.8},["stroke"]="#202020",["width"]=1.5}
refs[47] = refs[45]:text {["align"]={0.5,0.5},["fill"]="#bc573a",["font"]="Pretendard",["id"]="alpha-internal-46",["layer"]=40,["point"]={4.2,-2.43},["role"]="text",["size"]=18,["text"]="Hidden red mixed in"}
refs[48] = refs[43]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-47",["layer"]=40,["point"]={1.9,-2.25},["role"]="text",["size"]=18,["text"]="A = 0.5"}
refs[49] = scene:group {["id"]="alpha-internal-48",["opacity"]=0}
refs[50] = refs[49]:text {["align"]={0,0.5},["fill"]="#23896d",["font"]="Pretendard",["id"]="alpha-internal-49",["layer"]=40,["point"]={-5.1,-3.32},["role"]="text",["size"]=23,["text"]="Premultiply → average"}
refs[51] = refs[49]:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-50",["layer"]=40,["point"]={-5.1,-3.69},["role"]="text",["size"]=18,["text"]="RGB × A before averaging"}
refs[52] = refs[49]:rectangle {["center"]={-1.4,-3.5},["fill"]="#00ff00",["id"]="alpha-internal-51",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[53] = refs[49]:group {["id"]="alpha-internal-52",["matrix"]={1,0,0,-1.4,0,1,0,-3.5,0,0,1,0,0,0,0,1}}
refs[54] = refs[53]:rectangle {["center"]={0,0},["fill"]="#00ff00",["id"]="alpha-internal-53",["layer"]=25,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[55] = refs[49]:rectangle {["center"]={-0.3,-3.5},["fill"]="#ff0000",["id"]="alpha-internal-54",["layer"]=15,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[56] = refs[49]:group {["id"]="alpha-internal-55",["matrix"]={1,0,0,-0.3,0,1,0,-3.5,0,0,1,0,0,0,0,1}}
refs[57] = refs[56]:rectangle {["center"]={0,0},["fill"]="#ff0000",["id"]="alpha-internal-56",["layer"]=25,["size"]={0.5,0.5},["stroke"]="#00000000",["width"]=0}
refs[58] = refs[49]:arrow {["from"]={0.35,-3.5},["id"]="alpha-internal-57",["layer"]=10,["stroke"]="#202020",["tip"]=9,["to"]={1.3,-3.5},["width"]=2}
refs[59] = refs[49]:arrow {["from"]={2.5,-3.5},["id"]="alpha-internal-58",["layer"]=10,["stroke"]="#202020",["tip"]=9,["to"]={3.6,-3.5},["width"]=2}
refs[60] = scene:group {["id"]="alpha-internal-59",["opacity"]=0}
refs[61] = refs[60]:rectangle {["center"]={1.9,-3.5},["fill"]="#008000",["id"]="alpha-internal-60",["layer"]=15,["size"]={0.8,0.5},["stroke"]="#00000000",["width"]=0}
refs[62] = scene:group {["id"]="alpha-internal-61",["opacity"]=0}
refs[63] = refs[62]:rectangle {["center"]={4.2,-3.5},["fill"]="#80ff80",["id"]="alpha-internal-62",["layer"]=15,["size"]={0.8,0.8},["stroke"]="#202020",["width"]=1.5}
refs[64] = refs[62]:text {["align"]={0.5,0.5},["fill"]="#23896d",["font"]="Pretendard",["id"]="alpha-internal-63",["layer"]=40,["point"]={4.2,-4.18},["role"]="text",["size"]=18,["text"]="Green edge"}
refs[65] = refs[60]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-64",["layer"]=40,["point"]={1.9,-4},["role"]="text",["size"]=18,["text"]="A = 0.5"}
refs[66] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="alpha-internal-65",["layer"]=40,["point"]={0,-4.6},["role"]="text",["size"]=18,["text"]="Two-sample weighted average · Straight is also correct with explicit alpha weighting."}
scene:wait(1.1)
scene:play({{target=refs[6],opacity=1}},0.4,"smooth",0)
scene:play({{target=refs[9],opacity=1}},0.4,"smooth",0)
scene:wait(1.5)
scene:play({{target=refs[9],opacity=0}},0.001,"smooth",0)
scene:play({{target=refs[11],opacity=1}},0.4,"smooth",0)
scene:wait(1.5)
scene:play({{target=refs[24],opacity=1}},0.4,"smooth",0)
scene:wait(1.5)
scene:play({{target=refs[32],opacity=1}},0.4,"smooth",0)
scene:play({{target=refs[36],transform={0.8,0,0,1.7,0,1,0,-1.75,0,0,1,0,0,0,0,1}},{target=refs[39],transform={0.8,0,0,2.1,0,1,0,-1.75,0,0,1,0,0,0,0,1}}},0.9,"ease_in_out",0)
scene:wait(0.6)
scene:play({{target=refs[36],opacity=0}},0.001,"smooth",0)
scene:play({{target=refs[39],opacity=0}},0.001,"smooth",0)
scene:play({{target=refs[43],opacity=1}},0.4,"smooth",0)
scene:play({{target=refs[45],opacity=1}},0.4,"smooth",0)
scene:wait(1.4)
scene:play({{target=refs[49],opacity=1}},0.4,"smooth",0)
scene:play({{target=refs[57],fill="#000000"},{target=refs[55],fill="#000000"}},0.65,"smooth",0)
scene:play({{target=refs[53],transform={0.8,0,0,1.7,0,1,0,-3.5,0,0,1,0,0,0,0,1}},{target=refs[56],transform={0.8,0,0,2.1,0,1,0,-3.5,0,0,1,0,0,0,0,1}}},0.9,"ease_in_out",0)
scene:wait(0.6)
scene:play({{target=refs[53],opacity=0}},0.001,"smooth",0)
scene:play({{target=refs[56],opacity=0}},0.001,"smooth",0)
scene:play({{target=refs[60],opacity=1}},0.4,"smooth",0)
scene:play({{target=refs[62],opacity=1}},0.4,"smooth",0)
scene:wait(1.4)
return scene
