-- Generated by scripts/render-canvas-lifecycle.mjs; edit overview.mjs.
local refs = {}
local scene = tmath.scene {["camera"]={["height"]=11.5,["mode"]="fixed",["view"]="2d"},["fps"]=30,["height"]=1150,["loop"]=false,["theme"]={["background"]="#f2f2f2",["preset"]="pro_white",["text"]={["code"]={["color"]="#202020",["font"]="Pretendard"},["h1"]={["color"]="#202020",["font"]="Pretendard"},["h2"]={["color"]="#202020",["font"]="Pretendard"},["h3"]={["color"]="#202020",["font"]="Pretendard"},["text"]={["color"]="#202020",["font"]="Pretendard"}}},["width"]=1280}
refs[1] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-0",["layer"]=50,["point"]={-5.9,5.31},["role"]="text",["size"]=32,["text"]="Canvas state machine"}
refs[2] = scene:text {["align"]={1,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-1",["layer"]=50,["point"]={5.9,5.31},["role"]="text",["size"]=23,["text"]="Canvas::Impl::status"}
refs[3] = scene:line {["from"]={-5.9,4.95},["id"]="canvas-state-line-2",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,4.95},["width"]=1}
refs[4] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-3",["layer"]=50,["point"]={-5.9,4.65},["role"]="text",["size"]=18,["text"]="Representative transitions · API state rules below"}
refs[5] = scene:text {["align"]={1,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-4",["layer"]=50,["point"]={5.9,4.65},["role"]="text",["size"]=18,["text"]="Black: current state"}
refs[6] = scene:rectangle {["center"]={-4.95,2},["fill"]="#202020",["id"]="canvas-state-node-5",["layer"]=30,["size"]={1.9,1},["stroke"]="#202020",["width"]=1.5}
refs[7] = scene:text {["align"]={0.5,0.5},["fill"]="#ffffff",["font"]="Pretendard",["id"]="canvas-state-text-6",["layer"]=50,["point"]={-4.95,2.19},["role"]="text",["size"]=24,["text"]="Synced"}
refs[8] = scene:text {["align"]={0.5,0.5},["fill"]="#dddddd",["font"]="Pretendard",["id"]="canvas-state-text-7",["layer"]=50,["point"]={-4.95,1.79},["role"]="text",["size"]=17,["text"]="Initial / synced"}
refs[9] = scene:rectangle {["center"]={-2.5,2},["fill"]="#ffffff",["id"]="canvas-state-node-8",["layer"]=30,["size"]={1.9,1},["stroke"]="#202020",["width"]=1.5}
refs[10] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-9",["layer"]=50,["point"]={-2.5,2.19},["role"]="text",["size"]=24,["text"]="Damaged"}
refs[11] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-10",["layer"]=50,["point"]={-2.5,1.79},["role"]="text",["size"]=17,["text"]="Target / viewport"}
refs[12] = scene:rectangle {["center"]={-0.05,2},["fill"]="#ffffff",["id"]="canvas-state-node-11",["layer"]=30,["size"]={1.9,1},["stroke"]="#202020",["width"]=1.5}
refs[13] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-12",["layer"]=50,["point"]={-0.05,2.19},["role"]="text",["size"]=24,["text"]="Painting"}
refs[14] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-13",["layer"]=50,["point"]={-0.05,1.79},["role"]="text",["size"]=17,["text"]="Paint list changed"}
refs[15] = scene:rectangle {["center"]={2.4,2},["fill"]="#ffffff",["id"]="canvas-state-node-14",["layer"]=30,["size"]={1.9,1},["stroke"]="#202020",["width"]=1.5}
refs[16] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-15",["layer"]=50,["point"]={2.4,2.19},["role"]="text",["size"]=24,["text"]="Updating"}
refs[17] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-16",["layer"]=50,["point"]={2.4,1.79},["role"]="text",["size"]=17,["text"]="Update requested"}
refs[18] = scene:rectangle {["center"]={4.85,2},["fill"]="#ffffff",["id"]="canvas-state-node-17",["layer"]=30,["size"]={1.9,1},["stroke"]="#202020",["width"]=1.5}
refs[19] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-18",["layer"]=50,["point"]={4.85,2.19},["role"]="text",["size"]=24,["text"]="Drawing"}
refs[20] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-19",["layer"]=50,["point"]={4.85,1.79},["role"]="text",["size"]=17,["text"]="Draw submitted"}
refs[21] = scene:route {["id"]="canvas-state-edge-20",["layer"]=15,["points"]={{-3.99,2},{-3.46,2}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[22] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-21",["layer"]=50,["point"]={-3.725,2.76},["role"]="text",["size"]=20,["text"]="target()"}
refs[23] = scene:route {["id"]="canvas-state-edge-22",["layer"]=15,["points"]={{-1.54,2},{-1.01,2}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[24] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-23",["layer"]=50,["point"]={-1.275,2.76},["role"]="text",["size"]=20,["text"]="add()"}
refs[25] = scene:route {["id"]="canvas-state-edge-24",["layer"]=15,["points"]={{0.91,2},{1.44,2}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[26] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-25",["layer"]=50,["point"]={1.175,2.76},["role"]="text",["size"]=20,["text"]="update()"}
refs[27] = scene:route {["id"]="canvas-state-edge-26",["layer"]=15,["points"]={{3.36,2},{3.89,2}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[28] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-27",["layer"]=50,["point"]={3.625,2.76},["role"]="text",["size"]=20,["text"]="draw()"}
refs[29] = scene:route {["id"]="canvas-state-edge-28",["layer"]=15,["points"]={{4.85,2.51},{4.85,4.1},{-4.95,4.1},{-4.95,2.51}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[30] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-29",["layer"]=50,["point"]={-0.05,4.35},["role"]="text",["size"]=20,["text"]="sync() · renderer succeeds"}
refs[31] = scene:route {["id"]="canvas-state-edge-30",["layer"]=15,["points"]={{-4.35,2.51},{-4.35,3.32},{2.4,3.32},{2.4,2.51}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[32] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-31",["layer"]=50,["point"]={-0.75,3.59},["role"]="text",["size"]=20,["text"]="update()"}
refs[33] = scene:route {["id"]="canvas-state-edge-32",["layer"]=15,["points"]={{-2.5,1.49},{-2.5,0.82},{2.4,0.82},{2.4,1.49}},["stroke"]="#999999",["tip"]=9,["width"]=1.8}
refs[34] = scene:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-33",["layer"]=50,["point"]={-0.05,0.53},["role"]="text",["size"]=20,["text"]="update() · RenderUpdateFlag::All"}
refs[35] = scene:line {["from"]={-5.9,-0.85},["id"]="canvas-state-line-34",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-0.85},["width"]=1}
refs[36] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-35",["layer"]=50,["point"]={-5.75,-1.23},["role"]="text",["size"]=22,["text"]="API"}
refs[37] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-36",["layer"]=50,["point"]={-3.25,-1.23},["role"]="text",["size"]=22,["text"]="Allowed states"}
refs[38] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-37",["layer"]=50,["point"]={4.7,-1.23},["role"]="text",["size"]=22,["text"]="State on success"}
refs[39] = scene:line {["from"]={-5.9,-1.47},["id"]="canvas-state-line-38",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-1.47},["width"]=1}
refs[40] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-39",["layer"]=50,["point"]={-5.75,-1.78},["role"]="text",["size"]=21,["text"]="update()"}
refs[41] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-40",["layer"]=50,["point"]={-3.25,-1.78},["role"]="text",["size"]=20,["text"]="Synced · Damaged · Painting · Updating"}
refs[42] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-41",["layer"]=50,["point"]={4.7,-1.78},["role"]="text",["size"]=22,["text"]="Updating"}
refs[43] = scene:line {["from"]={-5.9,-2.04},["id"]="canvas-state-line-42",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-2.04},["width"]=1}
refs[44] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-43",["layer"]=50,["point"]={-5.75,-2.3},["role"]="text",["size"]=21,["text"]="draw()"}
refs[45] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-44",["layer"]=50,["point"]={-3.25,-2.3},["role"]="text",["size"]=20,["text"]="Damaged · Painting · Updating"}
refs[46] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-45",["layer"]=50,["point"]={4.7,-2.3},["role"]="text",["size"]=22,["text"]="Drawing"}
refs[47] = scene:line {["from"]={-5.9,-2.56},["id"]="canvas-state-line-46",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-2.56},["width"]=1}
refs[48] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-47",["layer"]=50,["point"]={-5.75,-2.82},["role"]="text",["size"]=21,["text"]="sync()"}
refs[49] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-48",["layer"]=50,["point"]={-3.25,-2.82},["role"]="text",["size"]=20,["text"]="Synced · Damaged · Painting · Updating · Drawing"}
refs[50] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-49",["layer"]=50,["point"]={4.7,-2.82},["role"]="text",["size"]=22,["text"]="Synced"}
refs[51] = scene:line {["from"]={-5.9,-3.08},["id"]="canvas-state-line-50",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-3.08},["width"]=1}
refs[52] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-51",["layer"]=50,["point"]={-5.75,-3.34},["role"]="text",["size"]=21,["text"]="add() / remove()"}
refs[53] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-52",["layer"]=50,["point"]={-3.25,-3.34},["role"]="text",["size"]=20,["text"]="Synced · Damaged · Painting · Updating"}
refs[54] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-53",["layer"]=50,["point"]={4.7,-3.34},["role"]="text",["size"]=22,["text"]="Painting"}
refs[55] = scene:line {["from"]={-5.9,-3.6},["id"]="canvas-state-line-54",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-3.6},["width"]=1}
refs[56] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-55",["layer"]=50,["point"]={-5.75,-3.86},["role"]="text",["size"]=21,["text"]="target()"}
refs[57] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-56",["layer"]=50,["point"]={-3.25,-3.86},["role"]="text",["size"]=20,["text"]="Synced · Damaged · Painting"}
refs[58] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-57",["layer"]=50,["point"]={4.7,-3.86},["role"]="text",["size"]=22,["text"]="Damaged"}
refs[59] = scene:line {["from"]={-5.9,-4.12},["id"]="canvas-state-line-58",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-4.12},["width"]=1}
refs[60] = scene:text {["align"]={0,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-59",["layer"]=50,["point"]={-5.75,-4.38},["role"]="text",["size"]=21,["text"]="viewport() change"}
refs[61] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-60",["layer"]=50,["point"]={-3.25,-4.38},["role"]="text",["size"]=20,["text"]="Synced · Damaged"}
refs[62] = scene:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-61",["layer"]=50,["point"]={4.7,-4.38},["role"]="text",["size"]=22,["text"]="Damaged"}
refs[63] = scene:line {["from"]={-5.9,-4.64},["id"]="canvas-state-line-62",["layer"]=5,["stroke"]="#cccccc",["to"]={5.9,-4.64},["width"]=1}
refs[64] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-63",["layer"]=50,["point"]={-5.9,-4.86},["role"]="text",["size"]=18,["text"]="Valid arguments and successful backend calls · viewport requires a changed region"}
refs[65] = scene:text {["align"]={0,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-64",["layer"]=50,["point"]={-5.9,-5.26},["role"]="text",["size"]=20,["text"]="No state change: update() in Updating, sync() in Synced, or an unchanged viewport."}
refs[66] = scene:group {["id"]="canvas-state-event-65",["opacity"]=0}
refs[67] = refs[66]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-66",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="Canvas construction"}
refs[68] = refs[66]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-67",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="The initial status is Synced."}
refs[69] = scene:group {["id"]="canvas-state-event-68",["opacity"]=0}
refs[70] = refs[69]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-69",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="target()"}
refs[71] = refs[69]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-70",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="Target setup succeeds → Damaged requires a full update."}
refs[72] = scene:group {["id"]="canvas-state-event-71",["opacity"]=0}
refs[73] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-72",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="add()"}
refs[74] = refs[72]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-73",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="Add to the Paint list → Painting."}
refs[75] = scene:group {["id"]="canvas-state-event-74",["opacity"]=0}
refs[76] = refs[75]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-75",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="draw() → internal update()"}
refs[77] = refs[75]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-76",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="Painting and Damaged call update() first."}
refs[78] = scene:group {["id"]="canvas-state-event-77",["opacity"]=0}
refs[79] = refs[78]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-78",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="draw() → render"}
refs[80] = refs[78]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-79",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="Scene render and postRender() succeed → Drawing."}
refs[81] = scene:group {["id"]="canvas-state-event-80",["opacity"]=0}
refs[82] = refs[81]:text {["align"]={0.5,0.5},["fill"]="#b33a32",["font"]="Pretendard",["id"]="canvas-state-text-81",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="update()"}
refs[83] = refs[81]:text {["align"]={0.5,0.5},["fill"]="#b33a32",["font"]="Pretendard",["id"]="canvas-state-text-82",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="InsufficientCondition · status remains Drawing."}
refs[84] = scene:group {["id"]="canvas-state-event-83",["opacity"]=0}
refs[85] = refs[84]:text {["align"]={0.5,0.5},["fill"]="#202020",["font"]="Pretendard",["id"]="canvas-state-text-84",["layer"]=50,["point"]={0,-0.1},["role"]="text",["size"]=27,["text"]="sync()"}
refs[86] = refs[84]:text {["align"]={0.5,0.5},["fill"]="#626262",["font"]="Pretendard",["id"]="canvas-state-text-85",["layer"]=50,["point"]={0,-0.53},["role"]="text",["size"]=21,["text"]="renderer->sync() succeeds → return to Synced."}
scene:play({{target=refs[66],opacity=1}},0.01,"smooth",0)
scene:wait(1.5)
scene:remove(refs[66])
scene:play({{target=refs[69],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[21],stroke="#1f66c4"}},0.75,"ease_in_out",0)
scene:play({{target=refs[6],fill="#ffffff"},{target=refs[7],fill="#202020"},{target=refs[8],fill="#626262"},{target=refs[9],fill="#202020"},{target=refs[10],fill="#ffffff"},{target=refs[11],fill="#dddddd"}},0.3,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[21],stroke="#999999"}},0.25,"ease_in_out",0)
scene:remove(refs[69])
scene:play({{target=refs[72],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[23],stroke="#1f66c4"}},0.75,"ease_in_out",0)
scene:play({{target=refs[9],fill="#ffffff"},{target=refs[10],fill="#202020"},{target=refs[11],fill="#626262"},{target=refs[12],fill="#202020"},{target=refs[13],fill="#ffffff"},{target=refs[14],fill="#dddddd"}},0.3,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[23],stroke="#999999"}},0.25,"ease_in_out",0)
scene:remove(refs[72])
scene:play({{target=refs[75],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[25],stroke="#1f66c4"}},0.75,"ease_in_out",0)
scene:play({{target=refs[12],fill="#ffffff"},{target=refs[13],fill="#202020"},{target=refs[14],fill="#626262"},{target=refs[15],fill="#202020"},{target=refs[16],fill="#ffffff"},{target=refs[17],fill="#dddddd"}},0.3,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[25],stroke="#999999"}},0.25,"ease_in_out",0)
scene:remove(refs[75])
scene:play({{target=refs[78],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[27],stroke="#1f66c4"}},0.75,"ease_in_out",0)
scene:play({{target=refs[15],fill="#ffffff"},{target=refs[16],fill="#202020"},{target=refs[17],fill="#626262"},{target=refs[18],fill="#202020"},{target=refs[19],fill="#ffffff"},{target=refs[20],fill="#dddddd"}},0.3,"ease_in_out",0)
scene:wait(1.5)
scene:play({{target=refs[27],stroke="#999999"}},0.25,"ease_in_out",0)
scene:remove(refs[78])
scene:play({{target=refs[81],opacity=1}},0.3,"ease_in_out",0)
scene:wait(2.2)
scene:remove(refs[81])
scene:play({{target=refs[84],opacity=1}},0.3,"ease_in_out",0)
scene:play({{target=refs[29],stroke="#1f66c4"}},0.75,"ease_in_out",0)
scene:play({{target=refs[18],fill="#ffffff"},{target=refs[19],fill="#202020"},{target=refs[20],fill="#626262"},{target=refs[6],fill="#202020"},{target=refs[7],fill="#ffffff"},{target=refs[8],fill="#dddddd"}},0.3,"ease_in_out",0)
scene:wait(2.7)
scene:play({{target=refs[29],stroke="#999999"}},0.25,"ease_in_out",0)
return scene
